CREATE TABLE "DEV_META"."CHG_HIST_META_MSTR" 
   (	"CHG_HIST_META_MSTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TBLNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CLMNNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CHG_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CHG_ITM" VARCHAR2(4000), 
	"PREV_VL" VARCHAR2(4000), 
	"CURR_VL" VARCHAR2(4000), 
	"CHNG_VL" VARCHAR2(4000), 
	"CHGR_ID" VARCHAR2(30), 
	"REG_DT" VARCHAR2(14), 
	 CONSTRAINT "CHK_CHMM_01" CHECK (CHG_TYCD IN ('신규', '수정', '삭제', '유지')) ENABLE, 
	 CONSTRAINT "PK_CHMM_01" PRIMARY KEY ("TBLNM", "CLMNNM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_CHMM_01" ON "DEV_META"."CHG_HIST_META_MSTR" ("TBLNM", "CLMNNM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
