CREATE TABLE "DEV_META"."META_MSTR" 
   (	"GRPNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CLCTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TBLNM" VARCHAR2(100) NOT NULL ENABLE, 
	"TBL_EXPLN" VARCHAR2(200), 
	"CLMNNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CLMN_EXPLN" VARCHAR2(200), 
	"ENTYNM" VARCHAR2(200), 
	"ATTRNM" VARCHAR2(200), 
	"DATA_LENGTH" NUMBER(10,0), 
	"DATA_TYCD" VARCHAR2(100), 
	"DATA_DEFAULT" VARCHAR2(4000), 
	"DATA_PRECISION" VARCHAR2(4000), 
	"DATA_SCALE" NUMBER(10,0), 
	"ETC_INFO_JSON" VARCHAR2(4000), 
	"CLCTR_ID" VARCHAR2(30), 
	"REG_DT" VARCHAR2(14), 
	 CONSTRAINT "PK_MM_01" PRIMARY KEY ("TBLNM", "CLMNNM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_MM_01" ON "DEV_META"."META_MSTR" ("TBLNM", "CLMNNM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "DEV_META"."IDX_MM_01" ON "DEV_META"."META_MSTR" ("CLMNNM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.META_MSTR IS '메타마스터';
COMMENT ON COLUMN DEV_META.META_MSTR.GRPNM IS '그룹명'
COMMENT ON COLUMN DEV_META.META_MSTR.CLCTN_ID IS '수집ID'
COMMENT ON COLUMN DEV_META.META_MSTR.TBLNM IS '테이블명'
COMMENT ON COLUMN DEV_META.META_MSTR.TBL_EXPLN IS '테이블설명'
COMMENT ON COLUMN DEV_META.META_MSTR.CLMNNM IS '컬럼명'
COMMENT ON COLUMN DEV_META.META_MSTR.CLMN_EXPLN IS '컬럼설명'
COMMENT ON COLUMN DEV_META.META_MSTR.ENTYNM IS '엔터티명'
COMMENT ON COLUMN DEV_META.META_MSTR.ATTRNM IS '속성명'
COMMENT ON COLUMN DEV_META.META_MSTR.DATA_LENGTH IS '데이터길이'
COMMENT ON COLUMN DEV_META.META_MSTR.DATA_TYCD IS '데이터유형코드'
COMMENT ON COLUMN DEV_META.META_MSTR.DATA_DEFAULT IS '데이터기본값'
COMMENT ON COLUMN DEV_META.META_MSTR.DATA_PRECISION IS '데이터정밀도'
COMMENT ON COLUMN DEV_META.META_MSTR.DATA_SCALE IS '데이터소수점길이'
COMMENT ON COLUMN DEV_META.META_MSTR.ETC_INFO_JSON IS '기타정보JSON'
COMMENT ON COLUMN DEV_META.META_MSTR.CLCTR_ID IS '수집자ID'
COMMENT ON COLUMN DEV_META.META_MSTR.REG_DT IS '등록일시'