CREATE TABLE "DEV_META"."STD_ENTY_TB" 
   (	"LGICL_DBNM" VARCHAR2(30), 
	"PHSCL_DBNM" VARCHAR2(30), 
	"TB_OWNER" VARCHAR2(30), 
	"ENTYNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ENTY_ENG_ABBRNM" VARCHAR2(100) NOT NULL ENABLE, 
	"TB_TYCDNM" VARCHAR2(200), 
	"ENTY_EXPLN" VARCHAR2(1000), 
	"TB_EXPLN" VARCHAR2(1000), 
	"TSK_CLSFCD" VARCHAR2(10), 
	"STRG_PRD" NUMBER(2,0), 
	"TB_VLMN" NUMBER(15,0), 
	"MN_IDNTFR" VARCHAR2(200) NOT NULL ENABLE, 
	"MN_IDNTFR_ENG_ABBRNM" VARCHAR2(100) NOT NULL ENABLE, 
	"SPR_ENTYNM" VARCHAR2(200), 
	"SYNM_LST" VARCHAR2(200), 
	"ENTY_TYNM" VARCHAR2(30), 
	"ENTY_CLSFNM" VARCHAR2(30), 
	"RELATED_ATTR" VARCHAR2(200), 
	"OCCR_CYCLNM" VARCHAR2(200), 
	"OPN_NOPN_RSN" VARCHAR2(200), 
	"RMRKS" VARCHAR2(4000), 
	 CONSTRAINT "CHK_SED_01" CHECK (ENTY_CLSFNM IN ('기본', '중심', '행위')) ENABLE, 
	 CONSTRAINT "CHK_SED_02" CHECK (ENTY_TYNM IN ('개체', '관계')) ENABLE, 
	 CONSTRAINT "CHK_STD_01" CHECK (TB_TYCDNM IN ('일반', '파티션', '클러스터', '뷰')) ENABLE, 
	 CONSTRAINT "CHK_STD_02" CHECK (OCCR_CYCLNM IN ('실시간', '일', '주', '월', '분기', '반기', '년', '기타')) ENABLE, 
	 CONSTRAINT "PK_STD_ENTY_01" PRIMARY KEY ("ENTYNM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_STD_ENTY_01" ON "DEV_META"."STD_ENTY_TB" ("ENTYNM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.STD_ENTY_TB IS '표준엔터티테이블';
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.LGICL_DBNM IS '논리DB명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.PHSCL_DBNM IS '물리DB명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.TB_OWNER IS '테이블소유자'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.ENTYNM IS '엔터티명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.ENTY_ENG_ABBRNM IS '엔터티영문약어명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.TB_TYCDNM IS '테이블유형명(일반,파티션,클러스터,뷰)'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.ENTY_EXPLN IS '엔터티설명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.TB_EXPLN IS '테이블설명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.TSK_CLSFCD IS '작업분류코드'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.STRG_PRD IS '저장기간'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.TB_VLMN IS '테이블볼륨(저장건수)'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.MN_IDNTFR IS '주식별자'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.MN_IDNTFR_ENG_ABBRNM IS '주식별자영문약어명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.SPR_ENTYNM IS '수퍼타입엔터티명'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.SYNM_LST IS '이음동의어목록'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.ENTY_TYNM IS '엔터티유형명(개체,관계)'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.ENTY_CLSFNM IS '엔터티분류명(기본,중심,행위)'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.RELATED_ATTR IS '관련속성'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.OCCR_CYCLNM IS '발생주기(실시간,일,주,월,분기,반기,년,기타)'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.OPN_NOPN_RSN IS '공개비공개사유'
COMMENT ON COLUMN DEV_META.STD_ENTY_TB.RMRKS IS '비고'