CREATE TABLE "DEV_META"."STD_DMN" 
   (	"DMN_GRPNM" VARCHAR2(100) NOT NULL ENABLE, 
	"DMN_CLSFNM" VARCHAR2(100) NOT NULL ENABLE, 
	"DMN_CD" VARCHAR2(100) NOT NULL ENABLE, 
	"DMNNM" VARCHAR2(100) NOT NULL ENABLE, 
	"DMN_EXPLN" VARCHAR2(1000), 
	"DATA_TYCD" VARCHAR2(100), 
	"DATA_LEN" NUMBER(10,0), 
	"DATA_DCPT_LEN" NUMBER(2,0), 
	"STRG_FRM" VARCHAR2(200), 
	"RPRSNT_FRM" VARCHAR2(200), 
	"UNIT" VARCHAR2(50), 
	"PRM_VL" VARCHAR2(300), 
	 CONSTRAINT "PK_STD_DMN_01" PRIMARY KEY ("DMN_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_STD_DMN_01" ON "DEV_META"."STD_DMN" ("DMN_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.STD_DMN IS '표준도메인';
COMMENT ON COLUMN DEV_META.STD_DMN.DMN_GRPNM IS '도메인그룹명'
COMMENT ON COLUMN DEV_META.STD_DMN.DMN_CLSFNM IS '도메인분류명'
COMMENT ON COLUMN DEV_META.STD_DMN.DMN_CD IS '도메인코드'
COMMENT ON COLUMN DEV_META.STD_DMN.DMNNM IS '도메인명'
COMMENT ON COLUMN DEV_META.STD_DMN.DMN_EXPLN IS '도메인설명'
COMMENT ON COLUMN DEV_META.STD_DMN.DATA_TYCD IS '자료유형코드'
COMMENT ON COLUMN DEV_META.STD_DMN.DATA_LEN IS '자료길이'
COMMENT ON COLUMN DEV_META.STD_DMN.DATA_DCPT_LEN IS '자료소수점길이'
COMMENT ON COLUMN DEV_META.STD_DMN.STRG_FRM IS '저장형식'
COMMENT ON COLUMN DEV_META.STD_DMN.RPRSNT_FRM IS '표현형식'
COMMENT ON COLUMN DEV_META.STD_DMN.UNIT IS '단위'
COMMENT ON COLUMN DEV_META.STD_DMN.PRM_VL IS '허용값'