CREATE TABLE "DEV_META"."STD_TRM_WRD" 
   (	"TRM_WRD_CLSFNM" VARCHAR2(100), 
	"TRM_WRDNM" VARCHAR2(200) NOT NULL ENABLE, 
	"TRM_WRD_ENGNM" VARCHAR2(200) NOT NULL ENABLE, 
	"TRM_WRD_ENG_ABBRNM" VARCHAR2(200) NOT NULL ENABLE, 
	"TRM_WRD_EXPLN" VARCHAR2(2000), 
	"TRM_WRD_STD_DMN_CD" VARCHAR2(100), 
	"TRM_STD_DMNNM" VARCHAR2(200), 
	"TRM_PRM_VL" VARCHAR2(1000), 
	"TRM_MNG_DEPTNM" VARCHAR2(200), 
	"TRM_STD_CDNM" VARCHAR2(200), 
	"TRM_WRK_DVSN" VARCHAR2(200), 
	"WRD_FRMT_WRDYN" CHAR(1) DEFAULT 'N', 
	"WRD_DMN_CLSFNM" VARCHAR2(200), 
	"WRD_SYNMWRD_LST" VARCHAR2(1000), 
	"WRD_BANWRD_LST" VARCHAR2(1000), 
	 CONSTRAINT "CHK_STW_01" CHECK (TRM_WRD_CLSFNM IN ('표준용어', '표준단어')) ENABLE, 
	 CONSTRAINT "CHK_STW_02" CHECK (WRD_FRMT_WRDYN IN ('Y', 'N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.STD_TRM_WRD IS '표준용어단어';
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRD_CLSFNM IS '용어단어분류명(표준용어,표준단어)'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRDNM IS '용어단어명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRD_ENGNM IS '용어단어영문명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRD_ENG_ABBRNM IS '용어단어영문약어명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRD_EXPLN IS '용어단어설명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRD_STD_DMN_CD IS '용어단어표준도메인코드'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_STD_DMNNM IS '용어표준도메인명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_PRM_VL IS '용어허용값'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_MNG_DEPTNM IS '용어관리부서명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_STD_CDNM IS '용어표준코드명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.TRM_WRK_DVSN IS '용어업무분야'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.WRD_FRMT_WRDYN IS '단어형식단어여부'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.WRD_DMN_CLSFNM IS '단어도메인분류명'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.WRD_SYNMWRD_LST IS '단어이음동의어목록'
COMMENT ON COLUMN DEV_META.STD_TRM_WRD.WRD_BANWRD_LST IS '단어금칙어목록'