CREATE TABLE "DEV_META"."STD_ATTR_CLMN" 
   (	"ENTYNM" VARCHAR2(200) NOT NULL ENABLE, 
	"TB_ENGNM" VARCHAR2(30) NOT NULL ENABLE, 
	"ATTRNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ATTR_ENG_ABBRNM" VARCHAR2(100) NOT NULL ENABLE, 
	"ATTR_TYNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ESNTL_INPT_TYNM" VARCHAR2(50), 
	"IDNTFR_TYNM" VARCHAR2(50), 
	"REF_ENTYNM" VARCHAR2(200), 
	"REF_ENTY_ENG_ABBRNM" VARCHAR2(100), 
	"REF_ATTRNM" VARCHAR2(200), 
	"REF_ATTR_ENG_ABBRNM" VARCHAR2(100), 
	"ATTR_EXPLN" VARCHAR2(1000), 
	"CLMN_EXPLN" VARCHAR2(1000) NOT NULL ENABLE, 
	"DATA_TYCD" VARCHAR2(100), 
	"DATA_LEN" VARCHAR2(200), 
	"DATA_FMT" VARCHAR2(200), 
	"NOT_NULLYN" CHAR(1) DEFAULT 'N', 
	"PK_INFO" VARCHAR2(100), 
	"FK_INFO" VARCHAR2(100), 
	"AK_INFO" VARCHAR2(100), 
	"CNSTRNT_COND" VARCHAR2(200), 
	"PRIVC_INFOYN" CHAR(1) DEFAULT 'N', 
	"ENCRYP_INFOYN" CHAR(1) DEFAULT 'N', 
	"OPN_NOPNYN" CHAR(1) DEFAULT 'N', 
	"RMRKS" VARCHAR2(4000), 
	 CONSTRAINT "CHK_SAD_01" CHECK (ESNTL_INPT_TYNM IN ('필수입력', '조건부필수입력')) ENABLE, 
	 CONSTRAINT "CHK_SAD_02" CHECK (IDNTFR_TYNM IN ('주식별자', '부식별자', '외래식별자')) ENABLE, 
	 CONSTRAINT "CHK_SCD_01" CHECK (NOT_NULLYN        IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CHK_SCD_02" CHECK (PRIVC_INFOYN     IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CHK_SCD_03" CHECK (ENCRYP_INFOYN    IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CHK_SCD_04" CHECK (OPN_NOPNYN     IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_STD_ATTR_01" PRIMARY KEY ("ENTYNM", "ATTRNM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_STD_ATTR_01" ON "DEV_META"."STD_ATTR_CLMN" ("ENTYNM", "ATTRNM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.STD_ATTR_CLMN IS '표준속성컬럼';
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ENTYNM IS '엔터티명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.TB_ENGNM IS '테이블영문명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ATTRNM IS '속성명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ATTR_ENG_ABBRNM IS '속성영문약어명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ATTR_TYNM IS '속성유형명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ESNTL_INPT_TYNM IS '필수입력유형명(필수입력,조건부필수입력)'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.IDNTFR_TYNM IS '식별자유형명(주식별자,부식별자,외래식별자)'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.REF_ENTYNM IS '참조엔터티명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.REF_ENTY_ENG_ABBRNM IS '참조엔터티영문약어명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.REF_ATTRNM IS '참조속성명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.REF_ATTR_ENG_ABBRNM IS '참조속성영문약어명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ATTR_EXPLN IS '속성설명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.CLMN_EXPLN IS '컬럼설명'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.DATA_TYCD IS '데이터유형코드'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.DATA_LEN IS '데이터길이'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.DATA_FMT IS '데이터형식'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.NOT_NULLYN IS 'NOTNULL여부'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.PK_INFO IS 'PK정보'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.FK_INFO IS 'FK정보'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.AK_INFO IS 'AK정보'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.CNSTRNT_COND IS '제약조건'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.PRIVC_INFOYN IS '개인정보여부'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.ENCRYP_INFOYN IS '암호화여부'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.OPN_NOPNYN IS '공개비공개여부'
COMMENT ON COLUMN DEV_META.STD_ATTR_CLMN.RMRKS IS '비고'