CREATE TABLE "DEV_META"."STD_CD" 
   (	"MNG_DEPTNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CDNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CD_ENGNM" VARCHAR2(100) NOT NULL ENABLE, 
	"CD_EXPLN" VARCHAR2(1000) NOT NULL ENABLE, 
	"DATA_TYCD" VARCHAR2(100) NOT NULL ENABLE, 
	"DATA_LEN" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_STD_CD_01" PRIMARY KEY ("CDNM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_STD_CD_01" ON "DEV_META"."STD_CD" ("CDNM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.STD_CD IS '표준코드';
COMMENT ON COLUMN DEV_META.STD_CD.MNG_DEPTNM IS '관리부서명'
COMMENT ON COLUMN DEV_META.STD_CD.CDNM IS '코드명'
COMMENT ON COLUMN DEV_META.STD_CD.CD_ENGNM IS '코드영문명'
COMMENT ON COLUMN DEV_META.STD_CD.CD_EXPLN IS '코드설명'
COMMENT ON COLUMN DEV_META.STD_CD.DATA_TYCD IS '데이터유형코드'
COMMENT ON COLUMN DEV_META.STD_CD.DATA_LEN IS '데이터길이'