CREATE TABLE "DEV_META"."STD_CD_DTL" 
   (	"CDNM" VARCHAR2(30) NOT NULL ENABLE, 
	"CD_VL" VARCHAR2(30) NOT NULL ENABLE, 
	"CD" VARCHAR2(100) NOT NULL ENABLE, 
	"CD_VL_EXPLN" VARCHAR2(1000) NOT NULL ENABLE, 
	 CONSTRAINT "PK_STD_CD_DTL_01" PRIMARY KEY ("CDNM", "CD_VL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_META"."PK_STD_CD_DTL_01" ON "DEV_META"."STD_CD_DTL" ("CDNM", "CD_VL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_META.STD_CD_DTL IS '표준코드상세';
COMMENT ON COLUMN DEV_META.STD_CD_DTL.CDNM IS '코드명'
COMMENT ON COLUMN DEV_META.STD_CD_DTL.CD_VL IS '코드값'
COMMENT ON COLUMN DEV_META.STD_CD_DTL.CD IS '코드'
COMMENT ON COLUMN DEV_META.STD_CD_DTL.CD_VL_EXPLN IS '코드값설명'