# the path of the directory where temporary files are stored
dextuploadnj.uploadFilter.tempRepository=
# the path of the default directory where the files are saved
dextuploadnj.uploadFilter.defaultRepository=

dextuploadnj.uploadFilter.autoMakingDirectory=true

dextuploadnj.uploadFilter.maxFileSize=
dextuploadnj.uploadFilter.maxTotalSize=

# the list of allowed file extensions
# ex. jpg,png,gif,docx
dextuploadnj.uploadFilter.whiteExtensions=

# whether or not to use the cleaner to delete temporary files and meta information files
dextuploadnj.uploadFilter.enableCleaner=true
# the time(hour) required to select files to be deleted when the cleaner is running
dextuploadnj.uploadFilter.timeAgo=24

# whether to verify the checksum of files(DEXTUploadX5 required)
dextuploadnj.uploadFilter.checksumEnable=false

# the path of the license file for DEXTUploadNJ Server license 
dextuploadnj.uploadFilter.licenseFilePath=WEB-INF/dextuploadnj/dextuploadnj.config

# the path of the license managment XML file for DEXTuploadNJ Server license
#dextuploadnj.uploadFilter.licenseConfigXmlPath=

# the authentication key string for DEXTUploadNJ Domain license or Combination license
#dextuploadnj.uploadFilter.licenseAuthKey=