-- 종합교육연수원 과목
CREATE OR REPLACE VIEW VW_HAK_SBJT_INF_CITT
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, SBJT_NM
	, SBJT_ENG_NM
	, COUR_DC
	, SBJT_DECD
	, SBJT_GPA
	, THYR_SEME_CLLC_YN
	, INF_ID_INFO
)
AS
(
	SELECT
		  A.COE_CD || B.COE_ESTB_Y || B.COE_GRNO AS INF_ID
		, B.COE_ESTB_Y AS YOSA
		, B.COE_GRNO AS SEME
		, A.COE_CD || B.COE_ESTB_Y || B.COE_GRNO AS SBJT_CD
		, A.COE_NM AS SBJT_NM
		, A.COE_ENM AS SBJT_ENG_NM
		, A.EDU_CRS_DC AS COUR_DC /* 교과목구분코드(과정구분코드 1:사이버연수과정, 2:학점은행제, 3:일반연수과정) */
		, '' AS SBJT_DECD
		, '' AS SBJT_GPA
		, '' AS THYR_SEME_CLLC_YN
		, B.COE_ESTB_Y || '년도 ' || A.COE_NM || ' 과정 '|| B.COE_GRNO ||'기수 인터페이스ID' AS INF_ID_INFO
	FROM CLEMGR.TB_AEI_TRAI_CRS A, CLEMGR.TB_AEI_TRAI_CRS_BASS_INFO B
	WHERE 1=1
		AND A.COE_CD = B.COE_CD
		AND B.COE_ESTB_Y > '2017'
	/* ORDER BY NVL(B.REG_DTTM, SYSDATE-7300) DESC, B.COE_ESTB_Y DESC */
);


COMMENT ON TABLE VW_HAK_SBJT_INF_CITT IS '종합교육연수원 과목';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.SBJT_ENG_NM IS '영문 과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.COUR_DC IS '교과목구분코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.SBJT_DECD IS '교과목학과코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.SBJT_GPA IS '학점';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.THYR_SEME_CLLC_YN IS '폐강여부';
COMMENT ON COLUMN VW_HAK_SBJT_INF_CITT.INF_ID_INFO IS '인터페이스 설명';