-- 방송대 수강생
CREATE OR REPLACE VIEW VW_HAK_ATLC_INF_KNOU
(
	  INF_ID
	, YOSA
	, SEME
	, STNO
	, DECD
	, ATLC_DECD
	, SBJT_CD
	, SPRC_NO
	, USER_TP_ID
	, INTG_NO
	, PNN
	, SEX
	, BIRD
	, JOB_CD
)
AS
(
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.STNO
		, S.STST_DECD AS DECD
		, A.DEPT_MAJR_CD AS ATLC_DECD
		, A.SBJT_NO AS SBJT_CD
		, '' AS SPRC_NO
		, B.USER_TP_ID
		, B.INTG_NO
		, B.PNN
		, U.SEX
		, U.BIRD
		, U.JOB_CD
	FROM  UNIV.TB_ALE_ATLC_APLC A
	INNER JOIN UNIV.TB_ASM_SREG S
		ON A.STNO = S.STNO
	INNER JOIN EP.TB_EPO_USER_TP B
		ON A.STNO = B.STNO
		AND B.USER_TC = '2'
	INNER JOIN EP.TB_EPO_USER U
		ON B.INTG_NO = U.INTG_NO
	WHERE A.YOSA > '2017'
		AND A.SBJT_NO = '00500'
		AND A.ATLC_APLC_STCD = '3' /* 수강_신청_상태코드 : 3 수강확정 */
		AND S.SREG_ST_DC IN ('1','2','3')  /* 학적상태구분코드 1 입학예정, 2 재학, 3 휴학 */
);

COMMENT ON TABLE VW_HAK_ATLC_INF_KNOU IS '방송대 수강생';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.STNO IS '학번';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.DECD IS '학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.ATLC_DECD IS '수강학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.SPRC_NO IS '분반';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.BIRD IS '생년월일';
COMMENT ON COLUMN VW_HAK_ATLC_INF_KNOU.JOB_CD IS 'JOB코드';