-- 방송대 교수
CREATE OR REPLACE VIEW VW_HAK_PROF_INF_KNOU
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, RSPB_PROF_YN
	, LOGIN_ID
	, INTG_NO
	, SEX
	, USER_TP_ID
	, PNN
	, USER_DTL_TC
)
AS
(
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, SBJT_NO AS SBJT_CD
		, 'N' AS RSPB_PROF_YN
		, C.LOGIN_ID
		, C.INTG_NO
		, C.SEX
		, B.USER_TP_ID
		, B.PNN
		, B.USER_DTL_TC
	FROM UNIV.TB_ALE_CHRG_SBJT A
	INNER JOIN EP.TB_EPO_USER_TP B
		ON A.PROF_NO = B.EDPS_NO
	INNER JOIN EP.TB_EPO_USER C
		ON B.INTG_NO = C.INTG_NO
	WHERE 1=1
		AND YOSA > '2017'
		AND SBJT_NO = '00500'
);

COMMENT ON TABLE VW_HAK_PROF_INF_KNOU IS '방송대 교수';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.RSPB_PROF_YN IS '책임교수여부';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_PROF_INF_KNOU.USER_DTL_TC IS '사용자상세유형코드';