-- 종합교육연수원 수강생
CREATE OR REPLACE VIEW VW_HAK_ATLC_INF_CITT
(
	  INF_ID
	, YOSA
	, SEME
	, STNO
	, DECD
	, ATLC_DECD
	, SBJT_CD
	, SPRC_NO
	, USER_TP_ID
	, INTG_NO
	, PNN
	, SEX
	, BIRD
	, JOB_CD
)
AS
(
	SELECT
		  A.COE_CD||A.COE_ESTB_Y||A.COE_GRNO AS INF_ID
		, A.COE_ESTB_Y AS YOSA
		, A.COE_GRNO AS SEME
		, A.USID AS STNO
		, '' AS DECD
		, '' AS ATLC_DECD
		, A.COE_CD||A.COE_ESTB_Y||A.COE_GRNO AS SBJT_CD
		, A.SPRC_NO
		, A.USID AS USER_TP_ID
		, B.INTG_NO
		, B.PNN
		, U.SEX
		, U.BIRD
		, U.JOB_CD
	FROM CLEMGR.TB_AEI_TRAI_SREG A
		INNER JOIN CLEMGR.TB_AEI_TRAI_APPC_INFO AA  /* 취소자가 생기면 지원자 테이블에서 삭제됨 */
			ON A.COE_RCV_NO = AA.COE_RCV_NO
		INNER JOIN EP.TB_EPO_USER_TP B
			ON A.USID = B.USER_TP_ID
		INNER JOIN EP.TB_EPO_USER U
			ON B.INTG_NO = U.INTG_NO
	WHERE 1=1
		AND A.COE_ESTB_Y > '2017'
		AND AA.PAY_STCD = '1' /* 환불자가 발생되면 PAY_STCD 널값으로 변경된다고 하여 환불자 아닌경우만 추출되도록 추가함 */
);

COMMENT ON TABLE VW_HAK_ATLC_INF_CITT IS '종합교육연수원 수강생';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.STNO IS '학번';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.DECD IS '학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.ATLC_DECD IS '수강학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.SPRC_NO IS '분반';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.BIRD IS '생년월일';
COMMENT ON COLUMN VW_HAK_ATLC_INF_CITT.JOB_CD IS 'JOB코드';