-- 프라임칼리지 학위과정 수강생
CREATE OR REPLACE VIEW VW_HAK_ATLC_INF_SMART
(
	  INF_ID
	, YOSA
	, SEME
	, STNO
	, DECD
	, ATLC_DECD
	, SBJT_CD
	, SPRC_NO
	, USER_TP_ID
	, INTG_NO
	, PNN
	, SEX
	, BIRD
	, JOB_CD
)
AS
(
	SELECT
		  DISTINCT A.CRS_GB||A.YYYY||A.SHTM_CD AS INF_ID
		, A.YYYY AS YOSA
		, A.SHTM_CD AS SEME
		, B.STU_NO AS STNO
		, B.MAJ_CD AS DECD
		, A.OPN_MAJ_CD AS ATLC_DECD
		, A.LEC_CD AS SBJT_CD
		, '' AS SPRC_NO
		, F.USER_TP_ID
		, E.INTG_NO
		, E.PNN
		, E.SEX
		, E.BIRD
		, E.JOB_CD
	FROM HAKUSER.HAK_LEC_T A
	INNER JOIN HAKUSER.HAK_LECAPPL_T B
		ON A.LEC_CD = B.LEC_CD
	INNER JOIN HAKUSER.HAK_USERSTUNO_T K
		ON K.STU_NO = B.STU_NO
		AND ( ((A.SHTM_CD != '11' AND A.SHTM_CD != '21') AND HAKJUK_STAT_GB = 'HST001')
			OR ((A.SHTM_CD = '11' OR A.SHTM_CD = '21') AND (HAKJUK_STAT_GB IN ('HST001','HST002')))
		)
	INNER JOIN (SELECT MAX(USER_SEQNO) AS USER_SEQNO, STU_NO FROM HAKUSER.HAK_USERSTUNO_T GROUP BY STU_NO)D ON K.STU_NO = D.STU_NO
	LEFT OUTER JOIN EP.TB_EPO_USER_TP F
		ON D.USER_SEQNO = F.USER_SEQNO
	LEFT OUTER JOIN EP.TB_EPO_USER E
		ON E.INTG_NO=F.INTG_NO
	WHERE 1=1
		AND A.YYYY > '2017'
		AND EXISTS(
			SELECT SUBJ_CD FROM HAKUSER.HAK_SUBJ_T S WHERE A.SUBJ_CD = S.SUBJ_CD AND S.BHAK_YN = 'N'
		)
		AND EXISTS(
			SELECT SUBJ_CD FROM HAKUSER.HAK_LECAPPL_CONFM_T P WHERE
				A.CRS_GB = P.CRS_GB AND A.YYYY=P.YYYY AND A.SHTM_CD=P.SHTM_CD AND B.STU_NO=P.STU_NO AND P.LECAPPL_CONFM_YN = 'Y'
		)
		AND EXISTS(
			SELECT STU_NO FROM HAKUSER.HAK_PAYRECPT_T S
			WHERE A.CRS_GB = S.CRS_GB AND A.YYYY=s.YYYY AND A.SHTM_CD=s.SHTM_CD AND B.STU_NO = S.STU_NO AND S.RECPT_DT IS NOT NULL
		)
);

COMMENT ON TABLE VW_HAK_ATLC_INF_SMART IS '프라임칼리지 학위과정 수강생';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.STNO IS '학번';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.DECD IS '학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.ATLC_DECD IS '수강학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.SPRC_NO IS '분반';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.BIRD IS '생년월일';
COMMENT ON COLUMN VW_HAK_ATLC_INF_SMART.JOB_CD IS 'JOB코드';