-- 프라임칼리지 평생교육과정 수강생 취소
CREATE OR REPLACE VIEW VW_HAK_ATLC_CAN_INF_PRIME
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
)
AS
(
	SELECT
		  DISTINCT A.COURSE_TERM_ID AS INF_ID
		, A.HAKSA_YEAR AS YOSA
		, A.HAKSA_TERM AS SEME
		, B.COURSE_ID AS SBJT_CD
		, D.USER_ID AS STNO
	FROM
		BLHAKSA.LM_COR_COURSE_TERM A,
		BLHAKSA.LM_COR_COURSE B,
		BLHAKSA.LM_CLS_LEARNER C,
		BLHAKSA.LM_SYS_PAYMENT_LEARNER D
	WHERE 1=1
		AND A.COURSE_TERM_ID = B.COURSE_TERM_ID
		AND B.COURSE_ID = D.COURSE_ID
		AND C.USER_ID(+) = D.USER_ID
		AND C.COURSE_ID(+) = D.COURSE_ID
		AND D.STATUS_TYPE IN ('C', 'F', 'T')
		AND (C.LEARNER_STATUS <> 'normal' OR C.LEARNER_STATUS IS NULL)
		AND A.HAKSA_YEAR > '2017'
);

COMMENT ON TABLE VW_HAK_ATLC_CAN_INF_PRIME IS '프라임칼리지 평생교육과정 수강생 취소';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_PRIME.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_PRIME.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_PRIME.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_PRIME.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_PRIME.STNO IS '학번';