-- 프라임칼리지 학위과정 수강생 취소
CREATE OR REPLACE FORCE VIEW VW_HAK_ATLC_CAN_INF_SMART
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
)
AS
(
	SELECT
		  DISTINCT A.CRS_GB || A.YYYY || A.SHTM_CD AS INF_ID
	    , A.YYYY AS YOSA
	    , A.SHTM_CD AS SEME
	    , A.LEC_CD AS SBJT_CD
	    , B.STU_NO AS STNO
	FROM HAKUSER.HAK_LECAPPL_CANCEL_T B
		INNER JOIN HAKUSER.HAK_LEC_T A
			ON A.LEC_CD = B.LEC_CD
	WHERE 1=1
		AND A.YYYY > '2017'
);

COMMENT ON TABLE VW_HAK_ATLC_CAN_INF_SMART IS '프라임칼리지 학위과정 수강생 취소';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_SMART.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_SMART.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_SMART.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_SMART.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_SMART.STNO IS '학번';