-- 대학원 수강생
CREATE OR REPLACE VIEW VW_HAK_ATLC_INF_GRSC
(
	  INF_ID
	, YOSA
	, SEME
	, STNO
	, DECD
	, ATLC_DECD
	, SBJT_CD
	, SPRC_NO
	, USER_TP_ID
	, INTG_NO
	, PNN
	, SEX
	, BIRD
	, JOB_CD
)
AS
(
	/* 대학원 */
	SELECT
		A.YOSA || A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.GRSC_STNO AS STNO
		, S.GRSC_DECD AS DECD
		, '' AS ATLC_DECD
		, A.GRSC_SBJT_CD AS SBJT_CD
		, '' AS SPRC_NO
		, B.USER_TP_ID
		, B.INTG_NO
		, B.PNN
		, U.SEX
		, U.BIRD
		, S.JOB_CD
	FROM GRADMGR.TB_AGS_THYR_SEME_ATLC_SCOR A
	INNER JOIN EP.TB_EPO_USER_TP B
		ON A.GRSC_STNO = B.STNO
		AND B.USER_TC = 'G'
	INNER JOIN EP.TB_EPO_USER U
		ON B.INTG_NO = U.INTG_NO
	INNER JOIN GRADMGR.TB_AGS_REG_MNG C
		ON A.GRSC_STNO = C.GRSC_STNO
		AND A.YOSA = C.YOSA
		AND A.SEME = C.SEME
		AND C.REG_STCD IN ('11', '12', '13') /* 등록생, 0원등록, 복학등록 */
	INNER JOIN GRADMGR.TB_AGS_SREG S
		ON A.GRSC_STNO = S.GRSC_STNO
	UNION ALL
	/* 경영대학원 */
	SELECT
		A.YOSA || A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.GRSC_STNO AS STNO
		, S.GRSC_DC AS DECD
		, '' AS ATLC_DECD
		, A.GRSC_SBJT_CD AS SBJT_CD
		, '' AS SPRC_NO
		, B.USER_TP_ID
		, B.INTG_NO
		, B.PNN
		, U.SEX
		, U.BIRD
		, S.JOB_CD
	FROM SGRADMGR.TB_AGB_THYR_SEME_ATLC_SCOR A
	INNER JOIN EP.TB_EPO_USER_TP B
		ON A.GRSC_STNO = B.STNO
		AND B.USER_TC = 'S'
	INNER JOIN EP.TB_EPO_USER U
		ON B.INTG_NO = U.INTG_NO
	INNER JOIN SGRADMGR.TB_AGB_REG_MNG C
		ON A.GRSC_STNO = C.GRSC_STNO
		AND A.YOSA = C.YOSA
		AND A.SEME = C.SEME
		AND C.REG_STCD IN ('11', '12', '13') /* 등록생, 0원등록, 복학등록 */
	INNER JOIN SGRADMGR.TB_AGB_SREG S
		ON A.GRSC_STNO = S.GRSC_STNO
);

COMMENT ON TABLE VW_HAK_ATLC_INF_GRSC IS '대학원 수강생';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.STNO IS '학번';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.DECD IS '학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.ATLC_DECD IS '수강학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.SPRC_NO IS '분반';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.BIRD IS '생년월일';
COMMENT ON COLUMN VW_HAK_ATLC_INF_GRSC.JOB_CD IS 'JOB코드';
