-- 종합교육연수원 교수
CREATE OR REPLACE VIEW VW_HAK_PROF_INF_CITT
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, RSPB_PROF_YN
	, LOGIN_ID
	, INTG_NO
	, SEX
	, USER_TP_ID
	, PNN
	, USER_DTL_TC
)
AS
(
	SELECT
		  '' AS INF_ID
		, '' AS YOSA
		, '' AS SEME
		, '' AS SBJT_CD
		, '' AS RSPB_PROF_YN
		, '' AS LOGIN_ID
		, '' AS INTG_NO
		, '' AS SEX
		, '' AS USER_TP_ID
		, '' AS PNN
		, '' AS USER_DTL_TC
	FROM DUAL
);

COMMENT ON TABLE VW_HAK_PROF_INF_CITT IS '종합교육연수원 교수';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.RSPB_PROF_YN IS '책임교수여부';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_PROF_INF_CITT.USER_DTL_TC IS '사용자상세유형코드';