-- 방송대 수강생 취소
CREATE OR REPLACE VIEW VW_HAK_ATLC_CAN_INF_KNOU
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
)
AS
(
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.SBJT_NO
		, A.STNO
    FROM UNIV.TB_ALE_ATLC_APLC A
	WHERE 1=1
		AND A.YOSA > '2017'
		AND A.SBJT_NO = '00500'
		AND A.ATLC_APLC_STCD IN ('1', '2')
);

COMMENT ON TABLE VW_HAK_ATLC_CAN_INF_KNOU IS '방송대 수강생 취소';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_KNOU.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_KNOU.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_KNOU.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_KNOU.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_KNOU.STNO IS '학번';