-- 학과 정보
CREATE OR REPLACE VIEW VW_HAK_DEPT_INF
(
	  UP_DEPT_ID
	, DEPT_ID
	, DEPTNM
)
AS
(
	SELECT
		  (CASE WHEN CD_ID = 'GRSC_DECD' THEN 'GRSC'
			WHEN CD_ID = 'STST_DECD' THEN 'KNOU' ELSE '' END
		  ) AS UP_DEPT_ID
		, CD_INSV AS DEPT_ID
		, CD_INS_NM AS DEPTNM
	FROM COMMON.TB_COM_INTG_CD_INS
	WHERE 1=1
		AND CD_ID IN ('GRSC_DECD', 'STST_DECD')
);

COMMENT ON TABLE VW_HAK_DEPT_INF IS '학과 정보';
COMMENT ON COLUMN VW_HAK_DEPT_INF.UP_DEPT_ID IS '상위학과부서아이디';
COMMENT ON COLUMN VW_HAK_DEPT_INF.DEPT_ID IS '학과부서아이디';
COMMENT ON COLUMN VW_HAK_DEPT_INF.DEPTNM IS '학과부서명';