-- 대학원 종합시험 교수
CREATE OR REPLACE VIEW VW_HAK_PROF_INF_GRSCEX
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, RSPB_PROF_YN
	, LOGIN_ID
	, INTG_NO
	, SEX
	, USER_TP_ID
	, PNN
	, USER_DTL_TC
)
AS
(
	SELECT
		  DISTINCT INF_ID
		, YOSA
		, SEME
		, SBJT_CD
		, RSPB_PROF_YN
		, LOGIN_ID
		, INTG_NO
		, SEX
		, USER_TP_ID
		, PNN
		, USER_DTL_TC
	FROM (
		/* 대학원 */
		SELECT
			  'EXAM'||A.YOSA||A.SEME AS INF_ID
			, A.YOSA
			, A.SEME
			, DEGRE_EXAM_SBJT_NO AS SBJT_CD
			, 'Y' AS RSPB_PROF_YN
			, B.LOGIN_ID
			, B.INTG_NO
			, B.SEX
			, C.USER_TP_ID
			, C.PNN
			, C.USER_DTL_TC
		FROM GRADMGR.TB_AGS_DEGRE_EXAM_SBJT A
		INNER JOIN EP.TB_EPO_USER B
			ON (A.PRPB_CMTT_RRNO = B.RRNO
				OR A.SCRG_CMTT_RRNO = B.RRNO
				OR A.CNFM_INVS_CMTT_RRNO = B.RRNO)
		INNER JOIN EP.TB_EPO_USER_TP C
			ON B.INTG_NO = C.INTG_NO
			AND C.USER_DTL_TC IN  ('31010', '41501', '41502', '41503', '41504', '41505', '41509',
				'41506', '52001', '52002','M4503','K6002','M4501')
		WHERE
			A.YOSA > '2017'
		UNION ALL
		/* 경영대학원 */
		SELECT
			  'EXAM'||A.YOSA||A.SEME AS INF_ID
			, A.YOSA
			, A.SEME
			, DEGRE_EXAM_SBJT_NO AS SBJT_CD
			, 'Y' AS RSPB_PROF_YN
			, B.LOGIN_ID
			, B.INTG_NO
			, B.SEX
			, C.USER_TP_ID
			, C.PNN
			, C.USER_DTL_TC
		FROM SGRADMGR.TB_AGB_DEGRE_EXAM_SBJT A
		INNER JOIN EP.TB_EPO_USER B
			ON (A.PRPB_CMTT_RRNO = B.RRNO
				OR A.SCRG_CMTT_RRNO = B.RRNO
				OR A.CNFM_INVS_CMTT_RRNO = B.RRNO)
		INNER JOIN EP.TB_EPO_USER_TP C
			ON B.INTG_NO = C.INTG_NO
			AND C.USER_DTL_TC IN  ('31010', '41501', '41502', '41503', '41504', '41505', '41509',
				'41506', '52001', '52002','M4503','K6002','M4501')
		WHERE
			A.YOSA > '2017'
	)
);

COMMENT ON TABLE VW_HAK_PROF_INF_GRSCEX IS '대학원 종합시험 교수';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.RSPB_PROF_YN IS '책임교수여부';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSCEX.USER_DTL_TC IS '사용자상세유형코드';
