-- 대학원 교수
CREATE OR REPLACE VIEW VW_HAK_PROF_INF_GRSC
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, RSPB_PROF_YN
	, LOGIN_ID
	, INTG_NO
	, SEX
	, USER_TP_ID
	, PNN
	, USER_DTL_TC
)
AS
(
	/* 대학원 */
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.GRSC_SBJT_CD AS SBJT_CD
		, A.RSPB_PROF_YN
		, B.LOGIN_ID
		, B.INTG_NO
		, B.SEX
		, C.USER_TP_ID
		, C.PNN
		, C.USER_DTL_TC
	FROM  GRADMGR.TB_AGS_SBJT_CHRG_PROF A
	INNER JOIN EP.TB_EPO_USER B
		ON A.CHRG_PROF_RRNO = B.RRNO
	INNER JOIN EP.TB_EPO_USER_TP C
		ON B.INTG_NO = C.INTG_NO
		AND C.USER_DTL_TC IN ('31010', '41501', '41502', '41503', '41504', '41505', '41509',
			'41506', '52001', '52002','M4503','K6002','M4501')
	UNION ALL
	/* 경영대학원 */
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.GRSC_SBJT_CD AS SBJT_CD
		, A.RSPB_PROF_YN
		, B.LOGIN_ID
		, B.INTG_NO
		, B.SEX
		, C.USER_TP_ID
		, C.PNN
		, C.USER_DTL_TC
	FROM SGRADMGR.TB_AGB_SBJT_CHRG_PROF A
	INNER JOIN EP.TB_EPO_USER B
		ON A.CHRG_PROF_RRNO = B.RRNO
	INNER JOIN EP.TB_EPO_USER_TP C
		ON B.INTG_NO = C.INTG_NO
		AND C.USER_DTL_TC IN  ('31010', '41501', '41502', '41503', '41504', '41505', '41509',
			'41506', '52001', '52002','M4503','K6002','M4501')
);

COMMENT ON TABLE VW_HAK_PROF_INF_GRSC IS '대학원 교수';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.RSPB_PROF_YN IS '책임교수여부';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_PROF_INF_GRSC.USER_DTL_TC IS '사용자상세유형코드';