-- 대학원 과목
CREATE OR REPLACE VIEW VW_HAK_SBJT_INF_GRSC
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, SBJT_NM
	, SBJT_ENG_NM
	, COUR_DC
	, SBJT_DECD
	, SBJT_GPA
	, THYR_SEME_CLLC_YN
	, INF_ID_INFO
)
AS
(
	SELECT
		  INF_ID
		, YOSA
		, SEME
		, SBJT_CD
		, SBJT_NM
		, SBJT_ENG_NM
		, COUR_DC
		, SBJT_DECD
		, SBJT_GPA
		, THYR_SEME_CLLC_YN
		, INF_ID_INFO
	FROM (
		/* 대학원 */
		SELECT
			  (A.YOSA||A.SEME) AS INF_ID
			, A.YOSA
			, A.SEME
			, A.GRSC_SBJT_CD AS SBJT_CD
			, (SELECT CD_INS_NM FROM COMMON.TB_COM_INTG_CD_INS T
				WHERE A.GRSC_SBJT_CD = T.CD_INSV
			  ) AS SBJT_NM
			, (SELECT CD_INS_ENM FROM COMMON.TB_COM_INTG_CD_INS T
				WHERE A.GRSC_SBJT_CD = T.CD_INSV
			  ) AS SBJT_ENG_NM
			, B.GRSC_COUR_DC AS COUR_DC
			, A.GRSC_DECD AS SBJT_DECD
			, B.SBJT_GPA AS SBJT_GPA
			, A.THYR_SEME_CLLC_YN
			, A.YOSA||'년도 '||A.SEME||'학기 교과목 인터페이스ID' AS INF_ID_INFO
		FROM GRADMGR.TB_AGS_ESTB_SBJT A, GRADMGR.TB_AGS_GRSC_SBJT B
		WHERE 1=1
			AND A.GRSC_SBJT_CD = B.GRSC_SBJT_CD
			AND A.YOSA > '2017'
		UNION
		/* 경영대학원 */
		SELECT
			  (A.YOSA||A.SEME) AS INF_ID
			, A.YOSA
			, A.SEME
			, A.GRSC_SBJT_CD AS SBJT_CD
			, (SELECT CD_INS_NM FROM COMMON.TB_COM_INTG_CD_INS T
				WHERE A.GRSC_SBJT_CD = T.CD_INSV
			  ) AS SBJT_NM
			, (SELECT CD_INS_ENM FROM COMMON.TB_COM_INTG_CD_INS T
				WHERE A.GRSC_SBJT_CD = T.CD_INSV
			  ) AS SBJT_ENG_NM
			, B.GRSC_COUR_DC AS COUR_DC
			, A.GRSC_DC AS SBJT_DECD
			, B.SBJT_GPA AS SBJT_GPA
			, A.THYR_SEME_CLLC_YN
			, A.YOSA||'년도 '||A.SEME||'학기 교과목 인터페이스ID' AS INF_ID_INFO
		FROM SGRADMGR.TB_AGb_ESTB_SBJT A, SGRADMGR.TB_AGB_GRSC_SBJT B
		WHERE 1=1
			AND A.GRSC_SBJT_CD = B.GRSC_SBJT_CD
			AND A.YOSA > '2017'
		ORDER BY YOSA, SEME
	)
);

COMMENT ON TABLE VW_HAK_SBJT_INF_GRSC IS '대학원 과목';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.SBJT_ENG_NM IS '영문 과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.COUR_DC IS '교과목구분코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.SBJT_DECD IS '교과목학과코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.SBJT_GPA IS '학점';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.THYR_SEME_CLLC_YN IS '폐강여부';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSC.INF_ID_INFO IS '인터페이스 설명';