-- 프라임칼리지 학위과정 튜터
CREATE OR REPLACE VIEW VW_HAK_TUTR_INF_SMART
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, RSPB_PROF_YN
	, LOGIN_ID
	, INTG_NO
	, SEX
	, USER_TP_ID
	, PNN
	, USER_DTL_TC
)
AS
(
	SELECT
		  A.CRS_GB||A.YYYY||A.SHTM_CD AS INF_ID
		, A.YYYY AS YOSA
		, A.SHTM_CD AS SEME
		, A.LEC_CD AS SBJT_CD
		, X.MNG_YN AS RSPB_PROF_YN
		, X.LOGIN_ID
		, X.INTG_NO
		, X.SEX
		, X.USER_TP_ID
		, X.PNN
		, X.USER_DTL_TC
	FROM HAKUSER.HAK_LEC_T A
	LEFT OUTER JOIN (
		SELECT P.LEC_CD, C.PROF_NO, E.PNN, D.USER_SEQNO, E.LOGIN_ID, F.USER_TP_ID, E.SEX, E.INTG_NO, F.USER_DTL_TC, P.MNG_YN
		FROM HAKUSER.HAK_LECPROF_T P
		LEFT OUTER  JOIN HAKUSER.HAK_PROF_T C
			ON C.PROF_NO = P.PROF_NO
		LEFT OUTER JOIN EP.TB_EPO_USER_TP D
			ON D.USER_DTL_TC = 'P4200'
			AND P.PROF_NO = D.EDPS_NO
		LEFT OUTER JOIN EP.TB_EPO_USER E
			ON D.USER_SEQNO = E.USER_SEQNO
		LEFT OUTER JOIN EP.TB_EPO_USER_TP F
			ON E.USER_SEQNO = F.USER_SEQNO
			AND E.INTG_NO=F.INTG_NO
		) X ON A.LEC_CD = X.LEC_CD
	WHERE 1=1
		AND A.YYYY > '2017'
		AND X.USER_DTL_TC IS NOT NULL AND EXISTS(
			SELECT SUBJ_CD FROM HAKUSER.HAK_SUBJ_T B WHERE A.SUBJ_CD = B.SUBJ_CD AND B.BHAK_YN = 'N'
		)
);

COMMENT ON TABLE VW_HAK_TUTR_INF_SMART IS '프라임칼리지 학위과정 튜터';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.RSPB_PROF_YN IS '책임교수여부';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_TUTR_INF_SMART.USER_DTL_TC IS '사용자상세유형코드';