-- 프라임칼리지 평생교육과정 과목
CREATE OR REPLACE VIEW VW_HAK_SBJT_INF_PRIME
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, SBJT_NM
	, SBJT_ENG_NM
	, COUR_DC
	, SBJT_DECD
	, SBJT_GPA
	, THYR_SEME_CLLC_YN
	, INF_ID_INFO
)
AS
(
	SELECT
		  B.COURSE_ID AS INF_ID
		, A.HAKSA_YEAR AS YOSA
		, A.HAKSA_TERM AS SEME
		, B.COURSE_ID AS SBJT_CD
		, B.COURSE_NAME AS SBJT_NM
		, NVL(B.COURSE_NAME_ENG, B.COURSE_NAME) AS SBJT_ENG_NM
		, B.COURSE_TYPE AS COUR_DC
		, B.DEPARTMENT_ID AS SBJT_DECD
		, B.CREDIT AS SBJT_GPA
		, B.CLLC_YN AS THYR_SEME_CLLC_YN
		, A.COURSE_TERM_NAME AS INF_ID_INFO
	FROM BLHAKSA.LM_COR_COURSE_TERM A, BLHAKSA.LM_COR_COURSE B
	WHERE 1=1
		AND A.COURSE_TERM_ID = B.COURSE_TERM_ID
		AND A.HAKSA_YEAR > '2017'
);

COMMENT ON TABLE VW_HAK_SBJT_INF_PRIME IS '프라임칼리지 평생교육과정 과목';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.SBJT_ENG_NM IS '영문 과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.COUR_DC IS '교과목구분코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.SBJT_DECD IS '교과목학과코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.SBJT_GPA IS '학점';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.THYR_SEME_CLLC_YN IS '폐강여부';
COMMENT ON COLUMN VW_HAK_SBJT_INF_PRIME.INF_ID_INFO IS '인터페이스 설명';