-- 방송대 과목
CREATE OR REPLACE VIEW VW_HAK_SBJT_INF_KNOU
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, SBJT_NM
	, SBJT_ENG_NM
	, COUR_DC
	, SBJT_DECD
	, SBJT_GPA
	, THYR_SEME_CLLC_YN
	, INF_ID_INFO
)
AS
(
	SELECT
		  B.YOSA||B.SEME AS INF_ID
		, B.YOSA
		, B.SEME
		, A.SBJT_NO AS SBJT_CD
		, A.SBJT_NM
		, A.SBJT_ENM AS SBJT_ENG_NM
		, '' AS COUR_DC
		, A.MNG_DEPT_MAJR_CD AS SBJT_DECD
		, MAX(B.GPA) AS SBJT_GPA
		, CASE WHEN MAX(B.ESTB_STCD) = '3' THEN 'N' ELSE 'Y' END AS THYR_SEME_CLLC_YN
		, B.YOSA||'년도 '||B.SEME||'학기 교과목 인터페이스ID' AS INF_ID_INFO
	FROM  UNIV.TB_ALE_SBJT_BASS A, UNIV.TB_ALE_ESTB_SBJT B
	WHERE 1=1
		AND (A.DUSE_YN = 'N' OR A.DUSE_YN IS NULL)
		AND A.SBJT_NO = '00500'
		AND A.SBJT_NO = B.SBJT_NO
		AND B.ESTB_STCD = '3'
		AND B.YOSA > '2017'
	GROUP BY B.YOSA, B.SEME, A.SBJT_NO, A.SBJT_NM, A.SBJT_ENM, A.MNG_DEPT_MAJR_CD
);

COMMENT ON TABLE VW_HAK_SBJT_INF_KNOU IS '방송대 과목';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.SBJT_ENG_NM IS '영문 과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.COUR_DC IS '교과목구분코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.SBJT_DECD IS '교과목학과코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.SBJT_GPA IS '학점';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.THYR_SEME_CLLC_YN IS '폐강여부';
COMMENT ON COLUMN VW_HAK_SBJT_INF_KNOU.INF_ID_INFO IS '인터페이스 설명';