-- 프라임칼리지 평생교육과정 튜터
CREATE OR REPLACE VIEW VW_HAK_TUTR_INF_PRIME
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, RSPB_PROF_YN
	, LOGIN_ID
	, INTG_NO
	, SEX
	, USER_TP_ID
	, PNN
	, USER_DTL_TC
)
AS
(
	SELECT
		A.COURSE_TERM_ID AS INF_ID
		, A.HAKSA_YEAR AS YOSA
		, A.HAKSA_TERM AS SEME
		, B.COURSE_ID AS SBJT_CD
		,  DECODE(C.OWNER_TYPE, 'prof', 'Y', 'N') AS RSPB_PROF_YN
		, F.LOGIN_ID
		, F.INTG_NO
		, (CASE WHEN (D.SEX = 'M' OR D.SEX = '1') THEN 1 WHEN (D.SEX = 'F' OR D.SEX = 'W' OR D.SEX = '2') THEN 2 ELSE 0 END) AS SEX
		, D.USER_TP_ID
		, D.USER_NAME AS PNN
		, E.USER_DTL_TC
	FROM BLHAKSA.LM_COR_COURSE_TERM A,
		BLHAKSA.LM_COR_COURSE B,
		BLHAKSA.LM_COR_COURSE_OWNER C,
		BLHAKSA.LM_PRM_USERS D,
		EP.TB_EPO_USER_TP E,
		EP.TB_EPO_USER F
	WHERE 1=1
		AND A.COURSE_TERM_ID = B.COURSE_TERM_ID
		AND B.COURSE_ID = C.COURSE_ID
		AND C.USER_ID = D.USER_ID
		AND D.USER_TP_ID = E.USER_TP_ID
		AND E.INTG_NO = F.INTG_NO
		AND A.HAKSA_YEAR > '2017'
		AND E.USER_DTL_TC = 'B4200' /* 튜터 */
);

COMMENT ON TABLE VW_HAK_TUTR_INF_PRIME IS '프라임칼리지 평생교육과정 튜터';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.RSPB_PROF_YN IS '책임교수여부';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_TUTR_INF_PRIME.USER_DTL_TC IS '사용자상세유형코드';