-- 대학원 종합시험 과목
CREATE OR REPLACE VIEW VW_HAK_SBJT_INF_GRSCEX
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, SBJT_NM
	, SBJT_ENG_NM
	, COUR_DC
	, SBJT_DECD
	, SBJT_GPA
	, THYR_SEME_CLLC_YN
	, INF_ID_INFO
)
AS
(
	/* 대학원 */
	SELECT
		  ('EXAM' || A.YOSA || A.SEME) AS INF_ID
		, A.YOSA
		, A.SEME
		, A.DEGRE_EXAM_SBJT_NO AS SBJT_CD
		, '(학위취득시험)' || DEGRE_EXAM_SBJT_NM AS SBJT_NM
		, '(학위취득시험)' || DEGRE_EXAM_SBJT_NM AS SBJT_ENG_NM
		, '' AS COUR_DC
		, GRSC_DECD AS SBJT_DECD
		, '0' AS SBJT_GPA
		, 'N' AS THYR_SEME_CLLC_YN
		, A.YOSA || '년도 ' || A.SEME || '학기 - 종합시험' AS INF_ID_INFO
	FROM GRADMGR.TB_AGS_DEGRE_EXAM_SBJT A
	WHERE 1=1
		AND A.YOSA > '2017'
	UNION ALL
	/* 경영대학원 */
	SELECT
		  ('EXAM' || A.YOSA || A.SEME) AS INF_ID
		, A.YOSA
		, A.SEME
		, A.DEGRE_EXAM_SBJT_NO AS SBJT_CD
		, '(학위취득시험)' || DEGRE_EXAM_SBJT_NM AS SBJT_NM
		, '(학위취득시험)' || DEGRE_EXAM_SBJT_NM AS SBJT_ENG_NM
		, '' AS COUR_DC
		, GRSC_DC AS SBJT_DECD
		, '0' AS SBJT_GPA
		, 'N' AS THYR_SEME_CLLC_YN
		, A.YOSA || '년도 ' || A.SEME || '학기 - 종합시험' AS INF_ID_INFO
	FROM SGRADMGR.TB_AGB_DEGRE_EXAM_SBJT A
	WHERE 1=1
		AND A.YOSA > '2017'
);

COMMENT ON TABLE VW_HAK_SBJT_INF_GRSCEX IS '대학원 종합시험 과목';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.SBJT_ENG_NM IS '영문 과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.COUR_DC IS '교과목구분코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.SBJT_DECD IS '교과목학과코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.SBJT_GPA IS '학점';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.THYR_SEME_CLLC_YN IS '폐강여부';
COMMENT ON COLUMN VW_HAK_SBJT_INF_GRSCEX.INF_ID_INFO IS '인터페이스 설명';