-- 프라임칼리지 평생교육과정 수강생
CREATE OR REPLACE VIEW VW_HAK_ATLC_INF_PRIME
(
	  INF_ID
	, YOSA
	, SEME
	, STNO
	, DECD
	, ATLC_DECD
	, SBJT_CD
	, SPRC_NO
	, USER_TP_ID
	, INTG_NO
	, PNN
	, SEX
	, BIRD
	, JOB_CD
)
AS
(
	SELECT
		  DISTINCT A.COURSE_TERM_ID AS INF_ID
		, A.HAKSA_YEAR AS YOSA
		, A.HAKSA_TERM AS SEME
		, C.USER_ID AS STNO
		, '' AS DECD
		, '' AS ATLC_DECD
		, B.COURSE_ID AS SBJT_CD
		, '' AS SPRC_NO
		, D.USER_TP_ID
		, F.INTG_NO
		, D.USER_NAME
		, (CASE WHEN (D.SEX = 'M' OR D.SEX = '1') THEN 1 WHEN (D.SEX = 'F' OR D.SEX = 'W' OR D.SEX = '2') THEN 2 ELSE 0 END) AS SEX
		, F.BIRD
		, F.JOB_CD
	FROM BLHAKSA.LM_COR_COURSE_TERM A,
		BLHAKSA.LM_COR_COURSE B,
		BLHAKSA.LM_CLS_LEARNER C,
		BLHAKSA.LM_PRM_USERS D,
		EP.TB_EPO_USER_TP E,
		EP.TB_EPO_USER F
	WHERE A.COURSE_TERM_ID = B.COURSE_TERM_ID
		AND B.COURSE_ID = C.COURSE_ID
		AND C.USER_ID = D.USER_ID
		AND D.USER_TP_ID = E.USER_TP_ID
		AND E.INTG_NO = F.INTG_NO
		AND C.LEARNER_STATUS = 'normal'
		AND A.HAKSA_YEAR > '2017'
);

COMMENT ON TABLE VW_HAK_ATLC_INF_PRIME IS '프라임칼리지 평생교육과정 수강생';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.STNO IS '학번';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.DECD IS '학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.ATLC_DECD IS '수강학과';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.SPRC_NO IS '분반';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.PNN IS '성명';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.SEX IS '성별';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.BIRD IS '생년월일';
COMMENT ON COLUMN VW_HAK_ATLC_INF_PRIME.JOB_CD IS 'JOB코드';