-- 대학원 수강생 취소
CREATE OR REPLACE VIEW VW_HAK_ATLC_CAN_INF_GRSC
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
)
AS
(
	/* 대학원 */
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.GRSC_SBJT_CD AS SBJT_CD
		, A.GRSC_STNO AS STNO
	FROM GRADMGR.TB_AGS_THYR_SEME_ATLC_SCOR A
	INNER JOIN EP.TB_EPO_USER_TP B
		ON A.GRSC_STNO = B.STNO
		AND B.USER_TC = 'G'
	INNER JOIN GRADMGR.TB_AGS_REG_MNG C
		ON A.GRSC_STNO = C.GRSC_STNO
		AND A.YOSA = C.YOSA
		AND A.SEME = C.SEME
		AND C.REG_STCD IN ('11', '12', '13') /* 등록생, 0원등록, 복학등록 */
	INNER JOIN GRADMGR.TB_AGS_SREG S
		ON A.GRSC_STNO = S.GRSC_STNO
		AND S.SREG_STCD IN ('0', '1')  /* 지원자, 재학생 */
	UNION ALL
	/* 경영대학원 */
	SELECT
		  A.YOSA||A.SEME AS INF_ID
		, A.YOSA
		, A.SEME
		, A.GRSC_SBJT_CD AS SBJT_CD
		, A.GRSC_STNO AS STNO
	FROM SGRADMGR.TB_AGB_THYR_SEME_ATLC_SCOR A
	INNER JOIN EP.TB_EPO_USER_TP B
		ON A.GRSC_STNO = B.STNO
		AND B.USER_TC = 'S'
	INNER JOIN SGRADMGR.TB_AGB_REG_MNG C
		ON A.GRSC_STNO = C.GRSC_STNO
		AND A.YOSA = C.YOSA
		AND A.SEME = C.SEME
		AND C.REG_STCD IN ('11', '12', '13') /* 등록생, 0원등록, 복학등록 */
	INNER JOIN SGRADMGR.TB_AGB_SREG S
		ON A.GRSC_STNO = S.GRSC_STNO
		AND S.SREG_STCD IN ('0', '1')  /* 지원자, 재학생 */
);

COMMENT ON TABLE VW_HAK_ATLC_CAN_INF_GRSC IS '대학원 수강생 취소';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSC.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSC.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSC.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSC.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSC.STNO IS '학번';