-- 프라임칼리지 학위과정 과목
CREATE OR REPLACE VIEW VW_HAK_SBJT_INF_SMART
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, SBJT_NM
	, SBJT_ENG_NM
	, COUR_DC
	, SBJT_DECD
	, SBJT_GPA
	, THYR_SEME_CLLC_YN
	, INF_ID_INFO
)
AS
(
	SELECT
		  A.CRS_GB||A.YYYY||A.SHTM_CD AS INF_ID
		, A.YYYY AS YOSA
		, A.SHTM_CD AS SEME
		, A.LEC_CD AS SBJT_CD
		, B.SUBJ_NM AS SBJT_NM
		, B.SUBJ_NM_ENG AS SBJT_ENG_NM
		, '' AS COUR_DC
		, A.OPN_MAJ_CD AS SBJT_DECD
		, A.PNT AS SBJT_GPA
		, A.LEC_CLS_YN AS THYR_SEME_CLLC_YN
		, A.YYYY||'년도 '||A.SHTM_CD||'학기 '|| (SELECT CD_NM FROM HAKUSER.HAK_CODE_T WHERE CMB_CD = A.CRS_GB)||' 교과목 인터페이스ID' AS INF_ID_INFO
	FROM HAKUSER.HAK_LEC_T A, HAKUSER.HAK_SUBJ_T B
	WHERE 1=1
		AND A.SUBJ_CD = B.SUBJ_CD
		AND A.YYYY > '2017'
		AND B.BHAK_YN = 'N'
);

COMMENT ON TABLE VW_HAK_SBJT_INF_SMART IS '프라임칼리지 학위과정 과목';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.SBJT_ENG_NM IS '영문 과목명';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.COUR_DC IS '교과목구분코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.SBJT_DECD IS '교과목학과코드';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.SBJT_GPA IS '학점';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.THYR_SEME_CLLC_YN IS '폐강여부';
COMMENT ON COLUMN VW_HAK_SBJT_INF_SMART.INF_ID_INFO IS '인터페이스 설명';