-- 대학원 종합시험 수강생 취소
CREATE OR REPLACE VIEW VW_HAK_ATLC_CAN_INF_GRSCEX
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
)
AS
(
	/* 수강취소 데이터 없음 */
	SELECT
		  '' AS INF_ID
		, '' AS YOSA
		, '' AS SEME
		, '' AS GRSC_SBJT_CD
		, '' AS GRSC_STNO
	FROM DUAL WHERE 1=0
);

COMMENT ON TABLE VW_HAK_ATLC_CAN_INF_GRSCEX IS '대학원 종합시험 수강생 취소';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSCEX.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSCEX.YOSA IS '학년도';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSCEX.SEME IS '학기';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSCEX.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_HAK_ATLC_CAN_INF_GRSCEX.STNO IS '학번';