-- 프라임칼리지 학위과정 성적
CREATE OR REPLACE VIEW VW_LMS_SCOR_INF_PRIME
(
      INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
	, INTG_NO
	, USER_TP_ID
	, INTG_ID
	, ATND_SC
	, TASK_SC
	, EXAM_SC
	, DISC_SC
	, PATR_SC
	, ETC_SC
	, TOSC
	, SBJT_CLAS_NO
)
AS
(
	/* LMS 성적 테이블에 맞추어 수정 */
	SELECT
		  '' AS INF_ID
		, '' AS YOSA
		, '' AS SEME
		, '' AS SBJT_CD
		, '' AS STNO
		, '' AS INTG_NO
		, '' AS USER_TP_ID
		, '' AS INTG_ID
		, 0 AS ATND_SC
		, 0 AS TASK_SC
		, 0 AS EXAM_SC
		, 0 AS DISC_SC
		, 0 AS PATR_SC
		, 0 AS ETC_SC
		, 0 AS TOSC
		, '' AS SBJT_CLAS_NO
	FROM dual
);

COMMENT ON TABLE VW_LMS_SCOR_INF_PRIME IS '프라임칼리지 학위과정 성적';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.YOSA IS '학년도';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.SEME IS '학기';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.STNO IS '학번';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.INTG_ID IS '통합ID';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.ATND_SC IS '출석점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.TASK_SC IS '과제점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.EXAM_SC IS '시험점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.DISC_SC IS '토론점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.PATR_SC IS '??점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.ETC_SC IS '기타점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.TOSC IS '총점';
COMMENT ON COLUMN VW_LMS_SCOR_INF_PRIME.SBJT_CLAS_NO IS '분반번호';