-- 대학원 성적
CREATE OR REPLACE VIEW VW_LMS_SCOR_INF_GRSC
(
      INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
	, INTG_NO
	, USER_TP_ID
	, INTG_ID
	, ATND_SC
	, TASK_SC
	, EXAM_SC
	, DISC_SC
	, PATR_SC
	, ETC_SC
	, TOSC
	, SBJT_CLAS_NO
)
AS
(
	/* LMS 성적 테이블에 맞추어 수정 */
	SELECT
		  '' AS INF_ID
		, '' AS YOSA
		, '' AS SEME
		, '' AS SBJT_CD
		, '' AS STNO
		, '' AS INTG_NO
		, '' AS USER_TP_ID
		, '' AS INTG_ID
		, 0 AS ATND_SC
		, 0 AS TASK_SC
		, 0 AS EXAM_SC
		, 0 AS DISC_SC
		, 0 AS PATR_SC
		, 0 AS ETC_SC
		, 0 AS TOSC
		, '' AS SBJT_CLAS_NO
	FROM dual
);

COMMENT ON TABLE VW_LMS_SCOR_INF_GRSC IS '대학원 성적';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.YOSA IS '학년도';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.SEME IS '학기';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.STNO IS '학번';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.INTG_ID IS '통합ID';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.ATND_SC IS '출석점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.TASK_SC IS '과제점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.EXAM_SC IS '시험점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.DISC_SC IS '토론점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.PATR_SC IS '??점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.ETC_SC IS '기타점수';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.TOSC IS '총점';
COMMENT ON COLUMN VW_LMS_SCOR_INF_GRSC.SBJT_CLAS_NO IS '분반번호';