
/* LMS에서 제공하는 VIEW, LMS 테이블 현행화하여 재작성 */

-- 대학원 시험 응시상태
CREATE OR REPLACE VIEW VW_LMS_EXAM_STAT_GRSC
(
	  INF_ID
	, YOSA
	, SEME
	, SBJT_CD
	, STNO
	, INTG_NO
	, USER_TP_ID
	, SBJT_NM
	, USER_NM
	, APEX_STCD
)
AS
(
	SELECT
		  '' AS INF_ID
		, '' AS YOSA
		, '' AS SEME
		, '' AS SBJT_CD
		, '' AS STNO
		, '' AS INTG_NO
		, '' AS USER_TP_ID
		, '' AS SBJT_NM
		, '' AS USER_NM
		, '' AS APEX_STCD
	FROM DUAL

);

COMMENT ON TABLE VW_LMS_EXAM_STAT_GRSC IS '대학원 시험 응시상태';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.INF_ID IS '인터페이스아이디';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.YOSA IS '학년도';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.SEME IS '학기';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.SBJT_CD IS '과목코드';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.STNO IS '학번';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.INTG_NO IS '통합번호';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.USER_TP_ID IS '사용자유형ID';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.SBJT_NM IS '과목명';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.USER_NM IS '이름';
COMMENT ON COLUMN VW_LMS_EXAM_STAT_GRSC.APEX_STCD IS '응시상태코드';
