-- FN_DEC
CREATE FUNCTION FN_DEC (
		inEncKey varchar(256), 
		inEncText varchar(2000)
	) RETURNS text
	DETERMINISTIC
	COMMENT '데이터 복호화'
BEGIN
	RETURN CONVERT(AES_DECRYPT(UNHEX(inEncText), SHA2(inEncKey,256)) using UTF8MB4);
END

-- FN_DT
CREATE FUNCTION FN_DT ()
	RETURNS varchar(8)
	READS SQL DATA
	COMMENT '현재날짜 문자열 가져오기(년월일)'
BEGIN
	RETURN DATE_FORMAT(NOW(), '%Y%m%d');
END

-- FN_DTTM
CREATE FUNCTION FN_DTTM () 
	RETURNS varchar(14)
	READS SQL DATA
	COMMENT '현재일시 문자열 가져오기'
BEGIN
	RETURN DATE_FORMAT(NOW(), '%Y%m%d%H%i%s');
END

-- FN_DTTM_ADD
CREATE FUNCTION FN_DTTM_ADD (
		days INT
	) RETURNS varchar(14)
	READS SQL DATA
	COMMENT '현재일시에 일수 더하여 문자열 가져오기'
BEGIN
	RETURN DATE_FORMAT(DATE_ADD(NOW(), INTERVAL days DAY), '%Y%m%d%H%i%s');
END

-- FN_DTTM_ADD_SEC
CREATE FUNCTION FN_DTTM_ADD_SEC (
	sec int
) RETURNS varchar(14)
	READS SQL DATA
	COMMENT '현재일시에 초를 더하여 문자열 가져오기'
BEGIN
    RETURN DATE_FORMAT(NOW() + INTERVAL sec SECOND, '%Y%m%d%H%i%s');
END

-- FN_DTTM_FORMAT
CREATE FUNCTION FN_DTTM_FORMAT (
		dateStr varchar(20)
	) RETURNS datetime
	DETERMINISTIC
	COMMENT '날짜형식의 문자열을 DTTM 형식으로 변환'
BEGIN
	RETURN DATE_FORMAT(dateStr,'%Y%m%d%H%i%s');
END

-- FN_DTTM_SUB
CREATE FUNCTION FN_DTTM_SUB (
		days INT
	) RETURNS varchar(14)
	READS SQL DATA
	COMMENT '현재일시에 일수 차감하여 문자열 가져오기'
BEGIN
	RETURN DATE_FORMAT(DATE_SUB(NOW(), INTERVAL days DAY), '%Y%m%d%H%i%s');
END

-- FN_ENC
CREATE FUNCTION FN_ENC (
		inEncKey varchar(256), 
		inEncText varchar(2000)
	) RETURNS varchar(2000)
	DETERMINISTIC
	COMMENT '데이터 암호화'
BEGIN
	RETURN HEX(AES_ENCRYPT(inEncText, SHA2(inEncKey,256)));
END

-- FN_GET_ASMNT_CNT
CREATE FUNCTION FN_GET_ASMNT_CNT (
		inCrsCreCd varchar(30), 
		inStdNo varchar(30)
	) RETURNS int
	READS SQL DATA
	COMMENT '수강생 과제수 조회'
BEGIN
	DECLARE asmntCnt int;

	SELECT IFNULL(SUM(R.CNT),0) INTO asmntCnt
	FROM ( 
		SELECT  
			CASE WHEN A.ASMNT_CTGR_CD = 'TEAM' THEN (
				SELECT COUNT(*) FROM tb_lms_asmnt_join_user B 
				WHERE B.ASMNT_CD = A.ASMNT_CD 
					AND B.TEAM_CD = FN_GET_STD_TEAM(inStdNo, A.CRS_CRE_CD) 
					AND B.STD_NO = inStdNo
					AND B.ASMNT_SUBMIT_STATUS_CD IN ('Submit', 'Late', 'ReSubmit')
			)
			ELSE (
				SELECT COUNT(*) FROM tb_lms_asmnt_join_user B 
				WHERE B.ASMNT_CD = A.ASMNT_CD 
					AND B.STD_NO = inStdNo 
					AND B.ASMNT_SUBMIT_STATUS_CD IN ('Submit', 'Late', 'ReSubmit')
			) 
			END AS CNT
		FROM tb_lms_asmnt A
		WHERE A.CRS_CRE_CD = inCrsCreCd
			AND A.DEL_YN = 'N'
	) R;

	RETURN asmntCnt;
END

-- FN_GET_CONFIG_VALUE
CREATE FUNCTION FN_GET_CONFIG_VALUE (
		inCfgCtgrCd varchar(10), 
		inCfgCd varchar(10)
	) RETURNS varchar(100)
	READS SQL DATA
	COMMENT '환경설정값 조회'
BEGIN
	DECLARE cfgVal varchar(100);
	SET cfgVal := '';

	SELECT CFG_VAL INTO cfgVal
	FROM tb_sys_cfg
	WHERE CFG_CTGR_CD = inCfgCtgrCd
		AND CFG_CD = inCfgCd;

	RETURN cfgVal;
END

-- FN_GET_DEPT_NM
CREATE FUNCTION FN_GET_DEPT_NM (
		inOrgId varchar(30), 
		inDeptCd varchar(30)
	) RETURNS varchar(200)
	READS SQL DATA
	COMMENT '소속명 조회'
BEGIN
	DECLARE deptNm varchar(200);

	SELECT DEPT_NM INTO deptNm
	FROM tb_home_user_dept_cd
	WHERE DEPT_CD = inDeptCd
		AND ORG_ID = inOrgId
		AND USE_YN = 'Y';
	
	RETURN deptNm;
END

-- FN_GET_ORG_CODE_NM
CREATE FUNCTION FN_GET_ORG_CODE_NM (
		inOrgId VARCHAR(30), 
		inCodeCtgrCd VARCHAR(30), 
		inCodeCd VARCHAR(30)
	) RETURNS varchar(200)
	READS SQL DATA
	COMMENT '기관 코드명 조회'
BEGIN
	DECLARE codeNm varchar(200) DEFAULT '';

	SELECT CODE_NM INTO codeNm
	FROM TB_ORG_CODE
    WHERE ORG_ID = inOrgId
		AND CODE_CTGR_CD = inCodeCtgrCd
		AND CODE_CD = inCodeCd;

	RETURN codeNm;
END

-- FN_GET_STD_DEPT_NM
CREATE FUNCTION FN_GET_STD_DEPT_NM (
		inStdNo varchar(40)
	) RETURNS varchar(200)
	READS SQL DATA
	COMMENT '수강생 소속명 조회'
BEGIN
	DECLARE deptNm varchar(200);

	SELECT DEPT.DEPT_NM INTO deptNm
	FROM tb_home_user_dept_cd DEPT, tb_home_user_info USR, tb_lms_std STD 
	WHERE 1=1
		AND DEPT.ORG_ID = USR.ORG_ID
		AND DEPT.DEPT_CD = USR.DEPT_CD
		AND USR.USER_ID = STD.USER_ID
		AND STD.STD_NO = inStdNo;

	RETURN deptNm;
END

-- FN_GET_STD_EMAIL
CREATE FUNCTION FN_GET_STD_EMAIL (
		inStdNo varchar(30)
	) RETURNS varchar(100)
	READS SQL DATA
	COMMENT '수강생 이메일 조회'
BEGIN
	DECLARE email varchar(100);

	SELECT A.EMAIL INTO email
	FROM tb_home_user_info A, tb_lms_std B
	WHERE A.USER_ID = B.USER_ID
		AND B.STD_NO = inStdNo;

   RETURN email;
END

-- FN_GET_STD_MOBILE_NO
CREATE FUNCTION FN_GET_STD_MOBILE_NO (
		inStdNo varchar(30)
	) RETURNS varchar(30)
	READS SQL DATA
	COMMENT '수강생 휴대폰번호 조회'
BEGIN
	DECLARE mobileNo varchar(30);

	SELECT A.MOBILE_NO INTO mobileNo
	FROM tb_home_user_info A, tb_lms_std B
	WHERE A.USER_ID = B.USER_ID
		AND B.STD_NO = inStdNo;

   RETURN mobileNo;
END

-- FN_GET_STD_NO
CREATE FUNCTION FN_GET_STD_NO (
		inUserId varchar(30), 
		inCrsCreCd varchar(30)
	) RETURNS varchar(40)
	READS SQL DATA
	COMMENT '수강생 번호 조회'
BEGIN
	DECLARE stdNo VARCHAR(40);

	SELECT STD_NO INTO stdNo
	FROM tb_lms_std
	WHERE USER_ID = inUserId   
		AND ENRL_STS = 'S'
		AND CRS_CRE_CD = inCrsCreCd;

   RETURN stdNo;
END

-- FN_GET_STD_TEAM
CREATE FUNCTION FN_GET_STD_TEAM (
		inStdNo varchar(30), 
		inCrsCreCd varchar(30)
	) RETURNS varchar(30)
	READS SQL DATA
	COMMENT '수강생 팀 조회'
BEGIN
	DECLARE teamCd varchar(30);
	
	SELECT A.TEAM_CD INTO teamCd
	FROM tb_lms_team A, tb_lms_team_ctgr B, tb_lms_team_member C
	WHERE 1=1
		AND A.TEAM_CD = C.TEAM_CD 
		AND A.TEAM_CTGR_CD = B.TEAM_CTGR_CD
		AND B.CRS_CRE_CD = inCrsCreCd
		AND C.STD_NO = inStdNo;

	RETURN teamCd;
END

-- FN_GET_STD_USER_ID
CREATE FUNCTION FN_GET_STD_USER_ID (
		inStdNo varchar(30)
	) RETURNS varchar(30)
	READS SQL DATA
	COMMENT '수강생 사용자 ID 조회'
BEGIN
	DECLARE userId varchar(30);

	SELECT A.USER_ID INTO userId
	FROM tb_home_user_login A, tb_lms_std B
	WHERE A.USER_ID = b.USER_ID 
		AND B.STD_NO = inStdNo;

	RETURN userId;
END

-- FN_GET_STD_USER_NM
CREATE FUNCTION FN_GET_STD_USER_NM (
		inStdNo varchar(30)
	) RETURNS varchar(200)
	READS SQL DATA
	COMMENT '수강생명 조회'
BEGIN
	DECLARE userNm VARCHAR(200);

	SELECT USR.USER_NM INTO userNm
	FROM tb_home_user_info USR, tb_lms_std STD 
	WHERE 1=1
		AND USR.USER_ID = STD.USER_ID
		AND STD.STD_NO = inStdNo;

	RETURN userNm;
END

-- FN_GET_USER_ID
CREATE FUNCTION FN_GET_USER_ID (
		IN_USER_ID varchar(30)
	) RETURNS varchar(200)
	READS SQL DATA
	COMMENT '사용자 ID 조회'
BEGIN
	DECLARE userId VARCHAR(50);

	SELECT USER_ID INTO userId
	FROM tb_home_user_login
	WHERE USER_ID = IN_USER_ID;

	RETURN userId;
END

-- FN_GET_USER_NM
CREATE FUNCTION FN_GET_USER_NM (
		inUserId VARCHAR(30)
	) RETURNS varchar(200)
	READS SQL DATA
	COMMENT '사용자명 조회'
BEGIN
	DECLARE userNm varchar(200) DEFAULT '';

	IF inUserId = '000000000000' THEN 
		SET userNm := '관리자';
	ELSE
		SELECT USER_NM INTO userNm
		FROM tb_home_user_info
		WHERE USER_ID = inUserId;
		
		IF userNm IS null THEN 
			SET userNm := 'UnKnown';
		END IF;
	END IF;
	
	RETURN userNm;
END

-- FN_NEW_ID
CREATE FUNCTION FN_NEW_ID (name varchar(10))
	RETURNS varchar(30)
	READS SQL DATA
	COMMENT '새 ID 생성'
BEGIN
	DECLARE digits CHAR(36) DEFAULT 'abcdefghijklmnopqrstuvwxyz0123456789';
	DECLARE id_buf VARCHAR(30) DEFAULT '';
	DECLARE time_str VARCHAR(10);
	DECLARE i INT DEFAULT 1;
	DECLARE char_index INT;
	
	IF CHAR_LENGTH(name) = 0 THEN
		SET name = 'ID';
	ELSE
		SET name = UCASE(LEFT(name, 5));
	END IF;
	
	SET time_str = CONCAT(LPAD(MINUTE(NOW()), 2, '0'), LPAD(SECOND(NOW()), 2, '0'), LPAD(RIGHT(NOW(3), 3), 3, '0'));

	SET id_buf = CONCAT(name, '_', 
		SUBSTRING(digits, MOD(YEAR(NOW()), 25) + 1, 1),
		SUBSTRING(digits, MONTH(NOW()) + 1, 1),
		SUBSTRING(digits, DAY(NOW()) + 1, 1),
		SUBSTRING(digits, HOUR(NOW()) + 1, 1));

	WHILE i <= CHAR_LENGTH(time_str) DO
		SET char_index = CAST(SUBSTRING(time_str, i, 1) AS UNSIGNED) + 1;
		SET id_buf = CONCAT(id_buf, SUBSTRING(digits, char_index, 1));
		SET i = i + 1;
	END WHILE;

	SET i = 1;

	WHILE i <= 8 DO
		SET id_buf = CONCAT(id_buf, MID(digits, FLOOR(1 + (RAND() * 36)), 1));
		SET i = i + 1;
	END WHILE;

	RETURN id_buf;
END

-- FN_SCOR_ATTEND_DETM_SCR
CREATE FUNCTION FN_SCOR_ATTEND_DETM_SCR (
		IN_CONT_CNT INT, 
		IN_ATTD_CNT INT
	) RETURNS float(5,2)
	DETERMINISTIC
	COMMENT '출석점수 계산'
BEGIN
	DECLARE V_RESULT FLOAT(5,2) DEFAULT 0;

	IF IN_CONT_CNT = 13 THEN
		IF IN_ATTD_CNT >= 13 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT >= 11 AND IN_ATTD_CNT < 13  THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT >= 10 AND IN_ATTD_CNT < 11  THEN
            SET V_RESULT := 60;
        ELSEIF IN_ATTD_CNT <= 9 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 12 THEN
		IF IN_ATTD_CNT >= 12 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT >= 10 AND IN_ATTD_CNT < 12  THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT >= 9  AND IN_ATTD_CNT < 10  THEN
            SET V_RESULT := 60;
        ELSEIF IN_ATTD_CNT <= 8 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 11 THEN
		IF IN_ATTD_CNT >= 11 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT >= 10 AND IN_ATTD_CNT < 11  THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT >= 9  AND IN_ATTD_CNT < 10  THEN
            SET V_RESULT := 60;
        ELSEIF IN_ATTD_CNT <= 8 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 10 THEN
		IF IN_ATTD_CNT >= 10 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT >= 9  AND IN_ATTD_CNT < 10  THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT >= 8  AND IN_ATTD_CNT <  9  THEN
            SET V_RESULT := 60;
        ELSEIF IN_ATTD_CNT <= 7 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 9 THEN
		IF IN_ATTD_CNT >= 9 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT >= 8  AND IN_ATTD_CNT <  9  THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT >= 7  AND IN_ATTD_CNT <  8  THEN
            SET V_RESULT := 60;
        ELSEIF IN_ATTD_CNT <= 6 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 8 THEN
		IF IN_ATTD_CNT >= 8 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT >= 7  AND IN_ATTD_CNT <  8  THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT >= 6  AND IN_ATTD_CNT <  7  THEN
            SET V_RESULT := 60;
        ELSEIF IN_ATTD_CNT <= 5 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 7 THEN
		IF IN_ATTD_CNT >= 7 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT = 6 THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT <= 5 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 6 THEN
		IF IN_ATTD_CNT >= 6 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT  = 5 THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT <= 4 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 5 THEN
		IF IN_ATTD_CNT >= 5 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT  = 4 THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT <= 3 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 4 THEN
		IF IN_ATTD_CNT >= 4 THEN 
            SET V_RESULT := 100;
        ELSEIF IN_ATTD_CNT  = 3 THEN
            SET V_RESULT := 80;
        ELSEIF IN_ATTD_CNT <= 2 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 3 THEN
		IF IN_ATTD_CNT >= 3 THEN 
            SET V_RESULT := 100;        
        ELSEIF IN_ATTD_CNT <= 2 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 2 THEN
		IF IN_ATTD_CNT >= 2 THEN 
            SET V_RESULT := 100;        
        ELSEIF IN_ATTD_CNT <= 1 THEN
            SET V_RESULT := 0;
        END IF;
	ELSEIF IN_CONT_CNT = 1 THEN
   		 IF IN_ATTD_CNT >= 1 THEN 
            SET V_RESULT := 100;        
        ELSEIF IN_ATTD_CNT < 1 THEN
            SET V_RESULT := 0;
        END IF;
    END IF;

    RETURN V_RESULT;
END

-- FN_SCOR_CINT
CREATE FUNCTION FN_SCOR_CINT (
		IN_SCR DOUBLE
	) RETURNS float(7,2)
	DETERMINISTIC
	COMMENT '성적 인원 계산'
BEGIN
	DECLARE V_RESULT FLOAT(7,2) DEFAULT 0;
	DECLARE V_TEMP_SCR FLOAT(7,2) DEFAULT 0;
    DECLARE V_ORI_CUT_SCR  FLOAT(7,2) DEFAULT 0;
    DECLARE V_UP_CUT_SCR FLOAT(7,2) DEFAULT 0;
    DECLARE V_TYPE VARCHAR(8);

    SET V_TYPE = 'CINT';

    IF V_TYPE = 'CINT' THEN
        SET V_ORI_CUT_SCR  := FLOOR(IN_SCR);
        SET V_TEMP_SCR     := ABS(FLOOR(IN_SCR) - IN_SCR) * 10;
        SET V_UP_CUT_SCR  := FLOOR(V_TEMP_SCR);

        IF V_UP_CUT_SCR = 5 THEN
            IF V_UP_CUT_SCR = V_TEMP_SCR THEN
                IF MOD(V_ORI_CUT_SCR,2) = 0 THEN
                    SET V_RESULT := V_ORI_CUT_SCR;
                ELSE
                    SET V_RESULT := V_ORI_CUT_SCR + 1;
                END IF;
            ELSE
                SET V_RESULT := ROUND(IN_SCR);
            END IF; 
        ELSE 
            SET V_RESULT := ROUND(IN_SCR);
        END IF;
    ELSE
        SET V_RESULT := ROUND(IN_SCR);
    END IF;        

	RETURN V_RESULT;
END

-- FN_SCOR_GRADE_RCNT_CAL
CREATE FUNCTION FN_SCOR_GRADE_RCNT_CAL (
		IN_CRS_CRE_CD VARCHAR(30),
		IN_MRKS_GRD_GBN VARCHAR(30),
		IN_GRD_RCNT INTEGER
	) RETURNS int
	READS SQL DATA
	COMMENT '성적 등급 인원 계산'
BEGIN
    DECLARE V_RESULT         FLOAT(7,2) DEFAULT 0;
    DECLARE V_STD_CNT        INTEGER DEFAULT 0;
    DECLARE V_APOBJ_RCNT     FLOAT(7,2) DEFAULT 0;
    DECLARE V_AOBJ_RCNT      FLOAT(7,2) DEFAULT 0;
    DECLARE V_BOBJ_RCNT      FLOAT(7,2) DEFAULT 0;
    DECLARE V_RNO            INTEGER DEFAULT 0;
    DECLARE V_MRKS_RANK      INTEGER DEFAULT 0;    
    DECLARE V_GRADE2         VARCHAR(8);
    DECLARE V_OVER_YN        VARCHAR(1);
    DECLARE V_GAP_RCNT       INTEGER DEFAULT 0;
    DECLARE V_RANK_RCNT      INTEGER DEFAULT 0;
    DECLARE V_MRKS_RANK_PLUS INTEGER DEFAULT 0;
    DECLARE V_MRKS_RANK_TEMP INTEGER DEFAULT 0;

	SELECT COUNT(1) INTO V_STD_CNT
	FROM TB_LMS_STD
	WHERE ENRL_STS = 'S'
		AND CRS_CRE_CD = IN_CRS_CRE_CD;

    SET V_APOBJ_RCNT    := FLOOR( V_STD_CNT * 0.2);
    SET V_AOBJ_RCNT     := FLOOR( V_STD_CNT * 0.4);
    SET V_BOBJ_RCNT     := FLOOR( V_STD_CNT * 0.8);

	SELECT MAX(YY.RNO), MAX(YY.MARK_RANK) INTO V_RNO, V_MRKS_RANK    
	FROM (
		SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			, Y.MARK_RANK
			, Y.RNO
		FROM (
			SELECT XXX.CRS_CRE_CD
			     , XXX.STD_NO
			     , XXX.CAL_TOT_SCR
			     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
			     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
			  FROM (
			   SELECT XX.CRS_CRE_CD
			        , XX.STD_NO
			        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
			     FROM (
			   	 	   SELECT  X.CRS_CRE_CD
						     , X.STD_NO
						     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
						     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
						     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
						     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
						     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
						     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
						     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
						     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
						  FROM 
						  (
							SELECT A.STD_NO
							     , C.CRS_CRE_CD
							     , A.SCORE_STATUS
							     , A.SCORE_GRADE 
							     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
							     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
							     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
							     , A.TOT_SCORE 
							     , A.FINAL_SCORE 
							     , A.ADD_SCORE AS ETC_SCORE
							     , A.PROF_MEMO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
							  FROM TB_LMS_STD_SCORE A
							  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
							  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
							  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
							 GROUP BY A.STD_NO, C.CRS_CRE_CD
							) X
						WHERE 1=1
						  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
					) XX
				) XXX
			 ) Y
			WHERE Y.RNO = IN_GRD_RCNT
			ORDER BY Y.RNO DESC
		) YY;

	IF IN_MRKS_GRD_GBN = 'B+' THEN
        SET V_GRADE2    := SUBSTR(IN_MRKS_GRD_GBN,1,1);
        SET V_OVER_YN   := 'N';

        IF IN_GRD_RCNT > V_BOBJ_RCNT AND V_GRADE2 = 'B' THEN
            SET V_OVER_YN   := 'Y';
        END IF;

        IF V_OVER_YN = 'Y' AND V_GRADE2 = 'B' THEN
            SELECT FN_SCOR_GRADE_RCNT_CAL(IN_CRS_CRE_CD,V_GRADE2,IN_GRD_RCNT) INTO V_MRKS_RANK;
        ELSE        
        	SELECT MAX(YY.RNO), MAX(YY.MARK_RANK) INTO V_RNO, V_MRKS_RANK      
		  FROM (
			SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			     , Y.MARK_RANK
			     , Y.RNO
			  FROM (
				SELECT XXX.CRS_CRE_CD
				     , XXX.STD_NO
				     , XXX.CAL_TOT_SCR
				     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
				     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
				  FROM (
				   SELECT XX.CRS_CRE_CD
				        , XX.STD_NO
				        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
				     FROM (
				   	 	   SELECT  X.CRS_CRE_CD
							     , X.STD_NO
							     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
							     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
							     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
							     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
							     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
							     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
							     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
							     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
							  FROM 
							  (
								SELECT A.STD_NO
								     , C.CRS_CRE_CD
								     , A.SCORE_STATUS
								     , A.SCORE_GRADE 
								     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
								     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
								     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
								     , A.TOT_SCORE 
								     , A.FINAL_SCORE 
								     , A.ADD_SCORE AS ETC_SCORE
								     , A.PROF_MEMO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
								  FROM TB_LMS_STD_SCORE A
								  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
								  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
								  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
								 GROUP BY A.STD_NO, C.CRS_CRE_CD
								) X
							WHERE 1=1
							  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
						) XX
					) XXX
				 ) Y
				WHERE Y.MARK_RANK = V_MRKS_RANK
				ORDER BY Y.RNO DESC
			) YY;
        END IF;

        SELECT MAX(YY.MARK_RANK) INTO V_MRKS_RANK_PLUS      
		  FROM (
			SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			     , Y.MARK_RANK
			     , Y.RNO
			  FROM (
				SELECT XXX.CRS_CRE_CD
				     , XXX.STD_NO
				     , XXX.CAL_TOT_SCR
				     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
				     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
				  FROM (
				   SELECT XX.CRS_CRE_CD
				        , XX.STD_NO
				        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
				     FROM (
				   	 	   SELECT  X.CRS_CRE_CD
							     , X.STD_NO
							     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
							     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
							     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
							     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
							     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
							     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
							     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
							     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
							  FROM 
							  (
								SELECT A.STD_NO
								     , C.CRS_CRE_CD
								     , A.SCORE_STATUS
								     , A.SCORE_GRADE 
								     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
								     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
								     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
								     , A.TOT_SCORE 
								     , A.FINAL_SCORE 
								     , A.ADD_SCORE AS ETC_SCORE
								     , A.PROF_MEMO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
								  FROM TB_LMS_STD_SCORE A
								  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
								  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
								  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
								 GROUP BY A.STD_NO, C.CRS_CRE_CD
								) X
							WHERE 1=1
							  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
						) XX
					) XXX
				 ) Y
			WHERE Y.RNO = (IN_GRD_RCNT + 1)
			ORDER BY Y.RNO DESC
		) YY ;

        IF V_RNO > V_MRKS_RANK AND V_GRADE2 = 'B' THEN
            IF V_MRKS_RANK = V_MRKS_RANK_PLUS THEN
                SET V_RNO := V_MRKS_RANK - 1;    
            END IF;
        END IF;

        SET V_MRKS_RANK := V_RNO;
    END IF;

    IF IN_MRKS_GRD_GBN IN ('A+','A','B') THEN
        IF IN_MRKS_GRD_GBN = 'A+' AND IN_GRD_RCNT < V_APOBJ_RCNT THEN
            SET V_GAP_RCNT := V_APOBJ_RCNT - IN_GRD_RCNT;               
        ELSEIF IN_MRKS_GRD_GBN = 'A' AND IN_GRD_RCNT < V_AOBJ_RCNT THEN
            SET V_GAP_RCNT := V_AOBJ_RCNT - IN_GRD_RCNT;
        ELSEIF IN_MRKS_GRD_GBN = 'B' AND IN_GRD_RCNT < V_BOBJ_RCNT THEN
            SET V_GAP_RCNT := V_BOBJ_RCNT - IN_GRD_RCNT;
        END IF;

        SELECT COUNT(1) INTO V_RANK_RCNT
		  FROM (
			SELECT XXX.CRS_CRE_CD
			     , XXX.STD_NO
			     , XXX.CAL_TOT_SCR
			     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
			     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
			  FROM (
			   SELECT XX.CRS_CRE_CD
			        , XX.STD_NO
			        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
			     FROM (
			   	 	   SELECT  X.CRS_CRE_CD
						     , X.STD_NO
						     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
						     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
						     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
						     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
						     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
						     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
						     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
						     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
						  FROM 
						  (
							SELECT A.STD_NO
							     , C.CRS_CRE_CD
							     , A.SCORE_STATUS
							     , A.SCORE_GRADE 
							     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
							     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
							     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
							     , A.TOT_SCORE 
							     , A.FINAL_SCORE 
							     , A.ADD_SCORE AS ETC_SCORE
							     , A.PROF_MEMO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
							  FROM TB_LMS_STD_SCORE A
							  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
							  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
							  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
							 GROUP BY A.STD_NO, C.CRS_CRE_CD
							) X
						WHERE 1=1
						  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
					) XX
				) XXX
			) Y
			WHERE Y.MARK_RANK = V_MRKS_RANK
			  AND Y.RNO >= IN_GRD_RCNT;

        IF V_RANK_RCNT > 1 THEN
            IF V_GAP_RCNT >  V_RANK_RCNT THEN
                SET V_MRKS_RANK := V_MRKS_RANK;
            ELSE
                SET V_MRKS_RANK := V_MRKS_RANK - 1;
            END IF;
        ELSE
            SET V_MRKS_RANK := V_MRKS_RANK;
        END IF;

        SELECT MAX(YY.RNO) INTO V_MRKS_RANK_TEMP      
		  FROM (
			SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			     , Y.RNO
			  FROM (
				SELECT XXX.CRS_CRE_CD
				     , XXX.STD_NO
				     , XXX.CAL_TOT_SCR
				     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
				     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
				  FROM (
				   SELECT XX.CRS_CRE_CD
				        , XX.STD_NO
				        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
				     FROM (
				   	 	   SELECT  X.CRS_CRE_CD
							     , X.STD_NO
							     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
							     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
							     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
							     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
							     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
							     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
							     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
							     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
							  FROM 
							  (
								SELECT A.STD_NO
								     , C.CRS_CRE_CD
								     , A.SCORE_STATUS
								     , A.SCORE_GRADE 
								     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
								     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
								     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
								     , A.TOT_SCORE 
								     , A.FINAL_SCORE 
								     , A.ADD_SCORE AS ETC_SCORE
								     , A.PROF_MEMO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
								  FROM TB_LMS_STD_SCORE A
								  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
								  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
								  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
								 GROUP BY A.STD_NO, C.CRS_CRE_CD
								) X
							WHERE 1=1
							  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
						) XX
					) XXX
				) Y
		 		WHERE Y.MARK_RANK = V_MRKS_RANK
				ORDER BY Y.RNO DESC
			) YY;

        IF V_MRKS_RANK_TEMP IS NOT NULL THEN
            SET V_MRKS_RANK := V_MRKS_RANK_TEMP;
        END IF;
    END IF;

    RETURN IFNULL(V_MRKS_RANK,0); 
END

-- FN_SCOR_LATE_DMARK_SCR
CREATE FUNCTION FN_SCOR_LATE_DMARK_SCR (
		IN_CONT_CNT INT, 
		IN_ATTD_SCR FLOAT, 
		IN_LATE_CNT INT
	) RETURNS float(5,2)
	DETERMINISTIC
	COMMENT '성적 등급 비율 계산'
BEGIN
	DECLARE V_RESULT FLOAT(5,2) DEFAULT 0;
	DECLARE V_RATE   FLOAT(5,2) DEFAULT 0;

	IF IN_LATE_CNT <= 1 THEN
        SET V_RATE := 1; 
    ELSEIF IN_LATE_CNT >= 2 AND  IN_LATE_CNT <= 3 THEN
        SET V_RATE := 0.95;
    ELSEIF IN_LATE_CNT >= 4 AND  IN_LATE_CNT <= 5 THEN
        SET V_RATE := 0.90;    
    ELSEIF IN_LATE_CNT >= 6 AND  IN_LATE_CNT <= 7 THEN
        SET V_RATE := 0.80;
    ELSEIF IN_LATE_CNT >= 8 AND  IN_LATE_CNT <= 9 THEN
        SET V_RATE := 0.70;
    ELSEIF IN_LATE_CNT >= 10 AND  IN_LATE_CNT <= 11 THEN
        SET V_RATE := 0.60;
    ELSEIF IN_LATE_CNT >= 12 AND  IN_LATE_CNT <= 13 THEN
        SET V_RATE := 0.50;
    END IF;

    SET V_RESULT := IN_ATTD_SCR * V_RATE;

    RETURN V_RESULT;
END

-- FN_PASSWORD
CREATE FUNCTION FN_PASSWORD (
		inText varchar(256)
	) RETURNS varchar(256)
    DETERMINISTIC
    COMMENT '비밀번호 암호화'
BEGIN
	RETURN SHA2(inText, 256);
END