-- FN_DTTM_ADD
CREATE FUNCTION FN_DTTM_ADD (
		days INT
	) RETURNS varchar(14)
	READS SQL DATA
	COMMENT '현재일시에 일수 더하여 문자열 가져오기'
BEGIN
	RETURN DATE_FORMAT(DATE_ADD(NOW(), INTERVAL days DAY), '%Y%m%d%H%i%s');
END