-- FN_SCOR_GRADE_RCNT_CAL
CREATE FUNCTION FN_SCOR_GRADE_RCNT_CAL (
		IN_CRS_CRE_CD VARCHAR(30),
		IN_MRKS_GRD_GBN VARCHAR(30),
		IN_GRD_RCNT INTEGER
	) RETURNS int
	READS SQL DATA
	COMMENT '성적 등급 인원 계산'
BEGIN
    DECLARE V_RESULT         FLOAT(7,2) DEFAULT 0;
    DECLARE V_STD_CNT        INTEGER DEFAULT 0;
    DECLARE V_APOBJ_RCNT     FLOAT(7,2) DEFAULT 0;
    DECLARE V_AOBJ_RCNT      FLOAT(7,2) DEFAULT 0;
    DECLARE V_BOBJ_RCNT      FLOAT(7,2) DEFAULT 0;
    DECLARE V_RNO            INTEGER DEFAULT 0;
    DECLARE V_MRKS_RANK      INTEGER DEFAULT 0;    
    DECLARE V_GRADE2         VARCHAR(8);
    DECLARE V_OVER_YN        VARCHAR(1);
    DECLARE V_GAP_RCNT       INTEGER DEFAULT 0;
    DECLARE V_RANK_RCNT      INTEGER DEFAULT 0;
    DECLARE V_MRKS_RANK_PLUS INTEGER DEFAULT 0;
    DECLARE V_MRKS_RANK_TEMP INTEGER DEFAULT 0;

	SELECT COUNT(1) INTO V_STD_CNT
	FROM TB_LMS_STD
	WHERE ENRL_STS = 'S'
		AND CRS_CRE_CD = IN_CRS_CRE_CD;

    SET V_APOBJ_RCNT    := FLOOR( V_STD_CNT * 0.2);
    SET V_AOBJ_RCNT     := FLOOR( V_STD_CNT * 0.4);
    SET V_BOBJ_RCNT     := FLOOR( V_STD_CNT * 0.8);

	SELECT MAX(YY.RNO), MAX(YY.MARK_RANK) INTO V_RNO, V_MRKS_RANK    
	FROM (
		SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			, Y.MARK_RANK
			, Y.RNO
		FROM (
			SELECT XXX.CRS_CRE_CD
			     , XXX.STD_NO
			     , XXX.CAL_TOT_SCR
			     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
			     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
			  FROM (
			   SELECT XX.CRS_CRE_CD
			        , XX.STD_NO
			        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
			     FROM (
			   	 	   SELECT  X.CRS_CRE_CD
						     , X.STD_NO
						     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
						     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
						     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
						     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
						     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
						     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
						     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
						     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
						  FROM 
						  (
							SELECT A.STD_NO
							     , C.CRS_CRE_CD
							     , A.SCORE_STATUS
							     , A.SCORE_GRADE 
							     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
							     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
							     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
							     , A.TOT_SCORE 
							     , A.FINAL_SCORE 
							     , A.ADD_SCORE AS ETC_SCORE
							     , A.PROF_MEMO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
							  FROM TB_LMS_STD_SCORE A
							  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
							  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
							  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
							 GROUP BY A.STD_NO, C.CRS_CRE_CD
							) X
						WHERE 1=1
						  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
					) XX
				) XXX
			 ) Y
			WHERE Y.RNO = IN_GRD_RCNT
			ORDER BY Y.RNO DESC
		) YY;

	IF IN_MRKS_GRD_GBN = 'B+' THEN
        SET V_GRADE2    := SUBSTR(IN_MRKS_GRD_GBN,1,1);
        SET V_OVER_YN   := 'N';

        IF IN_GRD_RCNT > V_BOBJ_RCNT AND V_GRADE2 = 'B' THEN
            SET V_OVER_YN   := 'Y';
        END IF;

        IF V_OVER_YN = 'Y' AND V_GRADE2 = 'B' THEN
            SELECT FN_SCOR_GRADE_RCNT_CAL(IN_CRS_CRE_CD,V_GRADE2,IN_GRD_RCNT) INTO V_MRKS_RANK;
        ELSE        
        	SELECT MAX(YY.RNO), MAX(YY.MARK_RANK) INTO V_RNO, V_MRKS_RANK      
		  FROM (
			SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			     , Y.MARK_RANK
			     , Y.RNO
			  FROM (
				SELECT XXX.CRS_CRE_CD
				     , XXX.STD_NO
				     , XXX.CAL_TOT_SCR
				     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
				     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
				  FROM (
				   SELECT XX.CRS_CRE_CD
				        , XX.STD_NO
				        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
				     FROM (
				   	 	   SELECT  X.CRS_CRE_CD
							     , X.STD_NO
							     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
							     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
							     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
							     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
							     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
							     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
							     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
							     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
							  FROM 
							  (
								SELECT A.STD_NO
								     , C.CRS_CRE_CD
								     , A.SCORE_STATUS
								     , A.SCORE_GRADE 
								     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
								     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
								     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
								     , A.TOT_SCORE 
								     , A.FINAL_SCORE 
								     , A.ADD_SCORE AS ETC_SCORE
								     , A.PROF_MEMO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
								  FROM TB_LMS_STD_SCORE A
								  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
								  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
								  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
								 GROUP BY A.STD_NO, C.CRS_CRE_CD
								) X
							WHERE 1=1
							  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
						) XX
					) XXX
				 ) Y
				WHERE Y.MARK_RANK = V_MRKS_RANK
				ORDER BY Y.RNO DESC
			) YY;
        END IF;

        SELECT MAX(YY.MARK_RANK) INTO V_MRKS_RANK_PLUS      
		  FROM (
			SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			     , Y.MARK_RANK
			     , Y.RNO
			  FROM (
				SELECT XXX.CRS_CRE_CD
				     , XXX.STD_NO
				     , XXX.CAL_TOT_SCR
				     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
				     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
				  FROM (
				   SELECT XX.CRS_CRE_CD
				        , XX.STD_NO
				        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
				     FROM (
				   	 	   SELECT  X.CRS_CRE_CD
							     , X.STD_NO
							     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
							     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
							     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
							     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
							     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
							     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
							     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
							     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
							  FROM 
							  (
								SELECT A.STD_NO
								     , C.CRS_CRE_CD
								     , A.SCORE_STATUS
								     , A.SCORE_GRADE 
								     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
								     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
								     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
								     , A.TOT_SCORE 
								     , A.FINAL_SCORE 
								     , A.ADD_SCORE AS ETC_SCORE
								     , A.PROF_MEMO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
								  FROM TB_LMS_STD_SCORE A
								  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
								  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
								  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
								 GROUP BY A.STD_NO, C.CRS_CRE_CD
								) X
							WHERE 1=1
							  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
						) XX
					) XXX
				 ) Y
			WHERE Y.RNO = (IN_GRD_RCNT + 1)
			ORDER BY Y.RNO DESC
		) YY ;

        IF V_RNO > V_MRKS_RANK AND V_GRADE2 = 'B' THEN
            IF V_MRKS_RANK = V_MRKS_RANK_PLUS THEN
                SET V_RNO := V_MRKS_RANK - 1;    
            END IF;
        END IF;

        SET V_MRKS_RANK := V_RNO;
    END IF;

    IF IN_MRKS_GRD_GBN IN ('A+','A','B') THEN
        IF IN_MRKS_GRD_GBN = 'A+' AND IN_GRD_RCNT < V_APOBJ_RCNT THEN
            SET V_GAP_RCNT := V_APOBJ_RCNT - IN_GRD_RCNT;               
        ELSEIF IN_MRKS_GRD_GBN = 'A' AND IN_GRD_RCNT < V_AOBJ_RCNT THEN
            SET V_GAP_RCNT := V_AOBJ_RCNT - IN_GRD_RCNT;
        ELSEIF IN_MRKS_GRD_GBN = 'B' AND IN_GRD_RCNT < V_BOBJ_RCNT THEN
            SET V_GAP_RCNT := V_BOBJ_RCNT - IN_GRD_RCNT;
        END IF;

        SELECT COUNT(1) INTO V_RANK_RCNT
		  FROM (
			SELECT XXX.CRS_CRE_CD
			     , XXX.STD_NO
			     , XXX.CAL_TOT_SCR
			     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
			     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
			  FROM (
			   SELECT XX.CRS_CRE_CD
			        , XX.STD_NO
			        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
			     FROM (
			   	 	   SELECT  X.CRS_CRE_CD
						     , X.STD_NO
						     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
						     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
						     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
						     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
						     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
						     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
						     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
						     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
						  FROM 
						  (
							SELECT A.STD_NO
							     , C.CRS_CRE_CD
							     , A.SCORE_STATUS
							     , A.SCORE_GRADE 
							     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
							     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
							     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
							     , A.TOT_SCORE 
							     , A.FINAL_SCORE 
							     , A.ADD_SCORE AS ETC_SCORE
							     , A.PROF_MEMO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
							     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
							  FROM TB_LMS_STD_SCORE A
							  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
							  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
							  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
							 GROUP BY A.STD_NO, C.CRS_CRE_CD
							) X
						WHERE 1=1
						  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
					) XX
				) XXX
			) Y
			WHERE Y.MARK_RANK = V_MRKS_RANK
			  AND Y.RNO >= IN_GRD_RCNT;

        IF V_RANK_RCNT > 1 THEN
            IF V_GAP_RCNT >  V_RANK_RCNT THEN
                SET V_MRKS_RANK := V_MRKS_RANK;
            ELSE
                SET V_MRKS_RANK := V_MRKS_RANK - 1;
            END IF;
        ELSE
            SET V_MRKS_RANK := V_MRKS_RANK;
        END IF;

        SELECT MAX(YY.RNO) INTO V_MRKS_RANK_TEMP      
		  FROM (
			SELECT DENSE_RANK() OVER(ORDER BY Y.RNO DESC) AS MARK_DENSE_RANK
			     , Y.RNO
			  FROM (
				SELECT XXX.CRS_CRE_CD
				     , XXX.STD_NO
				     , XXX.CAL_TOT_SCR
				     , RANK() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC) AS MARK_RANK
				     , ROW_NUMBER() OVER(ORDER BY IFNULL(XXX.CAL_TOT_SCR, 0) DESC, XXX.STD_NO) AS RNO
				  FROM (
				   SELECT XX.CRS_CRE_CD
				        , XX.STD_NO
				        , LESSON_SCORE_AVG + MIDDLE_TEST_SCORE_AVG + LAST_TEST_SCORE_AVG + TEST_SCORE_AVG + ASSIGNMENT_SCORE_AVG + FORUM_SCORE_AVG + QUIZ_SCORE_AVG + RESH_SCORE_AVG AS CAL_TOT_SCR
				     FROM (
				   	 	   SELECT  X.CRS_CRE_CD
							     , X.STD_NO
							     , ROUND((X.LESSON_SCORE/100) * X.LESSON_SCORE_RATIO, 2) AS LESSON_SCORE_AVG
							     , ROUND((X.MIDDLE_TEST_SCORE/100) * X.MIDDLE_TEST_SCORE_RATIO, 2) AS MIDDLE_TEST_SCORE_AVG
							     , ROUND((X.LAST_TEST_SCORE/100) * X.LAST_TEST_SCORE_RATIO, 2) AS LAST_TEST_SCORE_AVG
							     , ROUND((X.TEST_SCORE/100) * X.TEST_SCORE_RATIO, 2) AS TEST_SCORE_AVG
							     , ROUND((X.ASSIGNMENT_SCORE/100) * X.ASSIGNMENT_SCORE_RATIO, 2) AS ASSIGNMENT_SCORE_AVG
							     , ROUND((X.FORUM_SCORE/100) * X.FORUM_SCORE_RATIO, 2) AS FORUM_SCORE_AVG
							     , ROUND((X.QUIZ_SCORE/100) * X.QUIZ_SCORE_RATIO, 2) AS QUIZ_SCORE_AVG
							     , ROUND((X.RESH_SCORE/100) * X.RESH_SCORE_RATIO, 2) AS RESH_SCORE_AVG
							  FROM 
							  (
								SELECT A.STD_NO
								     , C.CRS_CRE_CD
								     , A.SCORE_STATUS
								     , A.SCORE_GRADE 
								     , ((SELECT DEPT_NM FROM TB_HOME_USER_INFO  WHERE USER_ID = (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO))) AS DEPT_NM
								     , (SELECT USER_ID FROM TB_LMS_STD WHERE STD_NO = A.STD_NO) AS USER_ID
								     , ((SELECT X.USER_NM FROM TB_HOME_USER_INFO X  WHERE X.USER_ID = (SELECT XX.USER_ID FROM TB_LMS_STD XX WHERE XX.STD_NO = A.STD_NO))) AS USER_NM
								     , A.TOT_SCORE 
								     , A.FINAL_SCORE 
								     , A.ADD_SCORE AS ETC_SCORE
								     , A.PROF_MEMO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.GET_SCORE, '-')) AS LESSON_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', C.SCORE_RATIO , '-')) AS LESSON_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '1', B.SCORE_ITEM_ID, '-')) AS LESSON_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.GET_SCORE, '-')) AS MIDDLE_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', C.SCORE_RATIO, '-')) AS MIDDLE_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '2', B.SCORE_ITEM_ID, '-')) AS MIDDLE_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.GET_SCORE, '-')) AS LAST_TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', C.SCORE_RATIO, '-')) AS LAST_TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '3', B.SCORE_ITEM_ID, '-')) AS LAST_TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.GET_SCORE, '-')) AS TEST_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', C.SCORE_RATIO, '-')) AS TEST_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '4', B.SCORE_ITEM_ID, '-')) AS TEST_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.GET_SCORE, '-')) AS ASSIGNMENT_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', C.SCORE_RATIO, '-')) AS ASSIGNMENT_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '5', B.SCORE_ITEM_ID, '-')) AS ASSIGNMENT_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.GET_SCORE, '-')) AS FORUM_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', C.SCORE_RATIO, '-')) AS FORUM_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '6', B.SCORE_ITEM_ID, '-')) AS FORUM_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.GET_SCORE, '-')) AS QUIZ_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', C.SCORE_RATIO, '-')) AS QUIZ_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '7', B.SCORE_ITEM_ID, '-')) AS QUIZ_ITEM_ID
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.GET_SCORE, '-')) AS RESH_SCORE
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', C.SCORE_RATIO, '-')) AS RESH_SCORE_RATIO
								     , MAX(IF(C.SCORE_ITEM_ORDER = '8', B.SCORE_ITEM_ID, '-')) AS RESH_ITEM_ID
								  FROM TB_LMS_STD_SCORE A
								  JOIN TB_LMS_STD_SCORE_ITEM B ON (B.STD_NO = A.STD_NO)
								  JOIN TB_LMS_STD_SCORE_ITEM_CONF C ON (C.SCORE_ITEM_ID = B.SCORE_ITEM_ID)
								  JOIN TB_LMS_STD D ON (D.STD_NO = A.STD_NO)
								 GROUP BY A.STD_NO, C.CRS_CRE_CD
								) X
							WHERE 1=1
							  AND X.CRS_CRE_CD = IN_CRS_CRE_CD
						) XX
					) XXX
				) Y
		 		WHERE Y.MARK_RANK = V_MRKS_RANK
				ORDER BY Y.RNO DESC
			) YY;

        IF V_MRKS_RANK_TEMP IS NOT NULL THEN
            SET V_MRKS_RANK := V_MRKS_RANK_TEMP;
        END IF;
    END IF;

    RETURN IFNULL(V_MRKS_RANK,0); 
END