-- FN_SCOR_LATE_DMARK_SCR
CREATE FUNCTION FN_SCOR_LATE_DMARK_SCR (
		IN_CONT_CNT INT, 
		IN_ATTD_SCR FLOAT, 
		IN_LATE_CNT INT
	) RETURNS float(5,2)
	DETERMINISTIC
	COMMENT '성적 등급 비율 계산'
BEGIN
	DECLARE V_RESULT FLOAT(5,2) DEFAULT 0;
	DECLARE V_RATE   FLOAT(5,2) DEFAULT 0;

	IF IN_LATE_CNT <= 1 THEN
        SET V_RATE := 1; 
    ELSEIF IN_LATE_CNT >= 2 AND  IN_LATE_CNT <= 3 THEN
        SET V_RATE := 0.95;
    ELSEIF IN_LATE_CNT >= 4 AND  IN_LATE_CNT <= 5 THEN
        SET V_RATE := 0.90;    
    ELSEIF IN_LATE_CNT >= 6 AND  IN_LATE_CNT <= 7 THEN
        SET V_RATE := 0.80;
    ELSEIF IN_LATE_CNT >= 8 AND  IN_LATE_CNT <= 9 THEN
        SET V_RATE := 0.70;
    ELSEIF IN_LATE_CNT >= 10 AND  IN_LATE_CNT <= 11 THEN
        SET V_RATE := 0.60;
    ELSEIF IN_LATE_CNT >= 12 AND  IN_LATE_CNT <= 13 THEN
        SET V_RATE := 0.50;
    END IF;

    SET V_RESULT := IN_ATTD_SCR * V_RATE;

    RETURN V_RESULT;
END