-- 1. 엔터티 목록으로 조회
-- 2. 엑셀에서 테이블이름 중복체크하여 PK 셀을 합친다.
SELECT
    --T.TABLE_NAME              AS 테이블명,
    TC.COMMENTS               AS 테이블설명,
    TC.COMMENTS				  AS 테이블설명2,
    --PCC.COLUMN_NAME           AS PK컬럼명,
    CC.COMMENTS               AS PK컬럼설명
FROM ALL_TABLES T
LEFT JOIN ALL_TAB_COMMENTS TC
       ON T.OWNER = TC.OWNER
      AND T.TABLE_NAME = TC.TABLE_NAME
LEFT JOIN ALL_CONSTRAINTS PC
       ON T.OWNER = PC.OWNER
      AND T.TABLE_NAME = PC.TABLE_NAME
      AND PC.CONSTRAINT_TYPE = 'P'
LEFT JOIN ALL_CONS_COLUMNS PCC
       ON PC.OWNER = PCC.OWNER
      AND PC.CONSTRAINT_NAME = PCC.CONSTRAINT_NAME
LEFT JOIN ALL_COL_COMMENTS CC
       ON PCC.OWNER = CC.OWNER
      AND PCC.TABLE_NAME = CC.TABLE_NAME
      AND PCC.COLUMN_NAME = CC.COLUMN_NAME
WHERE T.OWNER = 'DEV_LMS'
ORDER BY T.TABLE_NAME, PCC.POSITION;

