/* 뷰는 제외 */

SELECT	--B.OWNER, B.TNAME TNAME, B.CNAME CNAME,
		B.T_COMMENTS 엔터티명
		, B.C_COMMENTS 속성명
		, CASE  WHEN B.C_COMMENTS LIKE '%아이디%' THEN '설계형'
				WHEN B.C_COMMENTS LIKE '%코드%' THEN '설계형'		
				WHEN B.C_COMMENTS LIKE '%순서%' THEN '설계형'			
				WHEN B.C_COMMENTS LIKE '%순번%' THEN '설계형'			
				WHEN B.C_COMMENTS LIKE '%번호%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%경로%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%최대크기%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%파일순번%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%변환파일%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%다운로드수%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%기타정보%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%파일확장자%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%파일크기%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%첨부파일최대수%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%학년%' THEN '설계형'				
				WHEN B.C_COMMENTS LIKE '%일정%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%좋아요수%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%학점%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%메모%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%일자%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%정원%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%시간%' THEN '기본형'			
				WHEN B.C_COMMENTS LIKE '%일시%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%제출%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%여부%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%사유%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%주소%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%대상자정보%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%접근시스템명%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%대역값%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%URL%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%내용%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%제목%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%아이피%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%점수%' THEN '기본형'
				WHEN B.C_COMMENTS LIKE '%URL%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%조회수%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%레벨%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%명%' THEN '기본형'				
				WHEN B.C_COMMENTS LIKE '%율%' THEN '추출형'
				WHEN B.C_COMMENTS LIKE '%률%' THEN '추출형'
				WHEN B.C_COMMENTS LIKE '%성공수%' THEN '추출형'
				WHEN B.C_COMMENTS LIKE '%대상수%' THEN '추출형'
        	ELSE ''
    		END AS 속성유형
		, CASE 	WHEN A.CONS_TYPE = 'PK' THEN 'PK'
				WHEN C.CONS_TYPE = 'FK' THEN 'FK' ELSE '' END AS 식별자여부
		, CASE	WHEN B.NULLABLE = 'N' THEN '필수' ELSE '' END AS 필수입력여부
		, C.FK_TCMMNT 참조엔터티명
		, B.C_COMMENTS 참조속성명
		, B.C_COMMENTS 속성설명
FROM 	( SELECT 	
					T.OWNER, T.TABLE_NAME TNAME, T.COMMENTS T_COMMENTS 
					, C.COLUMN_NAME CNAME, C.COMMENTS C_COMMENTS, TC.NULLABLE
			FROM 	ALL_TAB_COMMENTS T, ALL_COL_COMMENTS C, ALL_TAB_COLUMNS TC
			WHERE 	T.OWNER = 'DEV_LMS' AND T.OWNER = C.OWNER AND T.TABLE_NAME = C.TABLE_NAME
					AND C.TABLE_NAME = TC.TABLE_NAME AND C.COLUMN_NAME = TC.COLUMN_NAME
					AND T.TABLE_NAME NOT LIKE 'V_%'
					--AND 'LMS_ACCESS_LOGS' = C.TABLE_NAME 
			) B 
	/*PK*/	LEFT JOIN (
			SELECT 	'PK' AS CONS_TYPE,
					ACC.CONSTRAINT_NAME PKNAME,
					ACC.TABLE_NAME PK_TNAME,
					ACC.COLUMN_NAME PK_COL_NM
			FROM 	ALL_CONS_COLUMNS ACC
			WHERE 	ACC.OWNER = 'DEV_LMS'
					AND CONSTRAINT_NAME LIKE 'PK_%'
			) A ON A.PK_TNAME = B.TNAME AND A.PK_COL_NM = B.CNAME
	/*FK*/	LEFT JOIN (
			SELECT 	'FK' AS CONS_TYPE
					, ACC.TABLE_NAME FK_TNAME
					, ACC.COLUMN_NAME FK_CNAME
					, AC.TABLE_NAME SRC_TNAME
					, ATC.COMMENTS FK_TCMMNT
			FROM 	ALL_CONSTRAINTS AC
					, ALL_CONS_COLUMNS ACC
					, ALL_TAB_COMMENTS ATC
			WHERE 	AC.OWNER = 'DEV_LMS'
					AND AC.CONSTRAINT_NAME LIKE 'FK_%'
					AND AC.R_CONSTRAINT_NAME = ACC.CONSTRAINT_NAME
					AND ACC.TABLE_NAME = ATC.TABLE_NAME
			) C ON C.SRC_TNAME = B.TNAME AND C.FK_CNAME = B.CNAME
ORDER 	BY 	B.TNAME, B.CNAME;
