CREATE TABLE "FURLMS"."TB_LMS_LOG_LRN_ACTV_INQ_HSTRY" 
   (	"LRN_ACTV_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LRN_ACTV_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"ORGNM" VARCHAR2(200) NOT NULL ENABLE, 
	"DEPT_ID" VARCHAR2(30), 
	"USER_RPRS_ID" VARCHAR2(30), 
	"STDNT_NO" VARCHAR2(30), 
	"USERNM" VARCHAR2(200) NOT NULL ENABLE, 
	"INQ_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"RGRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_LOG_LRN_ACTV_INQ_HSTRY" PRIMARY KEY ("LRN_ACTV_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_FURLMS"  ENABLE, 
	 CONSTRAINT "FK_U_TO_LLAIH" FOREIGN KEY ("USER_ID")
	  REFERENCES "FURLMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_FURLMS" ;

CREATE UNIQUE INDEX "FURLMS"."PK_LOG_LRN_ACTV_INQ_HSTRY" ON "FURLMS"."TB_LMS_LOG_LRN_ACTV_INQ_HSTRY" ("LRN_ACTV_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_FURLMS" ;

COMMENT ON TABLE FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY IS '학습활동조회이력-KNOU_TB_0804030700';
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.LRN_ACTV_ID IS '학습활동아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.USER_ID IS '사용자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.LRN_ACTV_TYCD IS '학습활동유형코드'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.ORGNM IS '기관명'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.DEPT_ID IS '학과부서아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.USER_RPRS_ID IS '사용자대표아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.STDNT_NO IS '학생번호'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.USERNM IS '사용자이름'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.INQ_DTTM IS '조회일시'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.RGRT_ID IS '등록자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.REG_DTTM IS '등록일시'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LOG_LRN_ACTV_INQ_HSTRY.MOD_DTTM IS '수정일시'