CREATE TABLE "DEV_LMS"."TB_LMS_USER_SNS_LGN" 
   (	"USER_SNS_LINK_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SNSNM" VARCHAR2(200) NOT NULL ENABLE, 
	"SNS_KEY" VARCHAR2(30) NOT NULL ENABLE, 
	"SNS_TYCD" VARCHAR2(30), 
	"SND_RCV_CTS" VARCHAR2(4000), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_SNS_LGN" PRIMARY KEY ("USER_SNS_LINK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_SNS_LGN" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_SNS_LGN" ON "DEV_LMS"."TB_LMS_USER_SNS_LGN" ("USER_SNS_LINK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_SNS_LGN IS '사용자SNS로그인';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.USER_SNS_LINK_ID IS '사용자SNS로그인아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.SNSNM IS 'SNS명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.SNS_KEY IS 'SNS키'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.SNS_TYCD IS 'SNS유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.SND_RCV_CTS IS '송신수신내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_SNS_LGN.MOD_DTTM IS '수정일시'