CREATE TABLE "DEV_LMS"."TB_LMS_USER_TMP_PSWD" 
   (	"USER_TMP_PSWD_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TMP_PSWD" VARCHAR2(30) NOT NULL ENABLE, 
	"TMP_PSWD_REQ_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"TMP_PSWD_EXP_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"PSWD_CHG_CMPTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"PSWD_CHG_DTTM" VARCHAR2(14), 
	"USEYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_TMP_PSWD" PRIMARY KEY ("USER_TMP_PSWD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_TMP_PSWD" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_TMP_PSWD" ON "DEV_LMS"."TB_LMS_USER_TMP_PSWD" ("USER_TMP_PSWD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_TMP_PSWD IS '사용자임시비밀번호';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.USER_TMP_PSWD_ID IS '사용자임시비밀번호아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.TMP_PSWD IS '임시비밀번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.TMP_PSWD_REQ_DTTM IS '임시비밀번호요청일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.TMP_PSWD_EXP_DTTM IS '임시비밀번호만료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.PSWD_CHG_CMPTNYN IS '비밀번호변경완료여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.PSWD_CHG_DTTM IS '비밀번호변경일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TMP_PSWD.MOD_DTTM IS '수정일시'