CREATE TABLE "DEV_LMS"."TB_LMS_USER_CRDTS_EXCH" 
   (	"USER_CRDTS_EXCH_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"YR" CHAR(4) NOT NULL ENABLE, 
	"SMSTR_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCTNM" VARCHAR2(200) NOT NULL ENABLE, 
	"DVCLAS_NO" NUMBER(3,0) NOT NULL ENABLE, 
	"CRDTS_EXCH_UNVSTD_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CRDTS_EXCH_GBNCD" VARCHAR2(30), 
	"CRDTS_EXCH_GBNNM" VARCHAR2(200) NOT NULL ENABLE, 
	"CRDTS_EXCH_UNVSTDNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ATNDLC_APLY_CRDTS" NUMBER(3,0), 
	"ATNDLC_APLYYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CMCRS_GBNCD" VARCHAR2(10), 
	"CMCRS_GBNNM" VARCHAR2(200), 
	"URL" VARCHAR2(1000), 
	"URLNM" VARCHAR2(200), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_CRDTS_EXCH" PRIMARY KEY ("USER_CRDTS_EXCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_CRDTS_EXCH" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_CRDTS_EXCH" ON "DEV_LMS"."TB_LMS_USER_CRDTS_EXCH" ("USER_CRDTS_EXCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_CRDTS_EXCH IS '사용자학점교류';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.USER_CRDTS_EXCH_ID IS '사용자학점교류아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.YR IS '연도'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.SMSTR_TYCD IS '학기유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.SBJCTNM IS '과목명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.DVCLAS_NO IS '분반번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.CRDTS_EXCH_UNVSTD_ID IS '학점교류대학생아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.CRDTS_EXCH_GBNCD IS '학점교류구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.CRDTS_EXCH_GBNNM IS '학점교류구분명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.CRDTS_EXCH_UNVSTDNM IS '학점교류대학생명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.ATNDLC_APLY_CRDTS IS '수강신청학점'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.ATNDLC_APLYYN IS '수강신청여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.CMCRS_GBNCD IS '이수구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.CMCRS_GBNNM IS '이수구분명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.URL IS 'URL'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.URLNM IS 'URL명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CRDTS_EXCH.MOD_DTTM IS '수정일시'