CREATE TABLE "DEV_LMS"."TB_LMS_ATFL_REPO" 
   (	"ATFL_REPO_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ATFL_REPO_PATH" VARCHAR2(200) NOT NULL ENABLE, 
	"ATFL_REPO_EXPLN" VARCHAR2(200), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_ATFL_REPO" PRIMARY KEY ("ATFL_REPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ATFL_REPO" ON "DEV_LMS"."TB_LMS_ATFL_REPO" ("ATFL_REPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ATFL_REPO IS '첨부파일저장소';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.ATFL_REPO_ID IS '첨부파일저장소아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.ATFL_REPO_PATH IS '첨부파일저장소경로'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.ATFL_REPO_EXPLN IS '첨부파일저장소설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_REPO.MOD_DTTM IS '수정일시'