CREATE TABLE "DEV_LMS"."TB_LMS_EXAM_EVL_SBST" 
   (	"EXAM_EVL_SBST_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_BSC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_SBST_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"EXAM_SBST_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_EXAM_EVL_SBST" PRIMARY KEY ("EXAM_EVL_SBST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EXAM_BSC_TO_EXAM_EVL_SBST" FOREIGN KEY ("EXAM_BSC_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_BSC" ("EXAM_BSC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAM_EVL_SBST" ON "DEV_LMS"."TB_LMS_EXAM_EVL_SBST" ("EXAM_EVL_SBST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAM_EVL_SBST IS '시험평가대체';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.EXAM_EVL_SBST_ID IS '시험평가대체아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.EXAM_BSC_ID IS '시험기본아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.EXAM_SBST_TYCD IS '시험대체유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.EXAM_SBST_ID IS '시험대체아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_EVL_SBST.MOD_DTTM IS '수정일시'