CREATE TABLE "FURLMS"."TB_LMS_EXRCS_SDDN_QSTN_BSC" 
   (	"EXRCS_SDDN_QSTN_BSC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"QSTN_TTL" VARCHAR2(200) NOT NULL ENABLE, 
	"QSTN_CTS" CLOB NOT NULL ENABLE, 
	"QSTNS_CMPTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"QSTN_GRP_ID" VARCHAR2(30), 
	"LCTR_WKNO_SCHDL_ID" VARCHAR2(30), 
	"QSTN_GBNCD" VARCHAR2(30) NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"PREV_SMSTR_IMPORTYN" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "PK_TB_LMS_QSTN_MSTR" PRIMARY KEY ("EXRCS_SDDN_QSTN_BSC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SBJCT_TO_QSTN_MSTR" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "FURLMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE, 
	 CONSTRAINT "FK_EXAM_GRP_TO_QSTN_MSTR" FOREIGN KEY ("QSTN_GRP_ID")
	  REFERENCES "FURLMS"."TB_LMS_EXAM_GRP" ("EXAM_GRP_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("QSTN_CTS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "FURLMS"."PK_TB_LMS_QSTN_MSTR" ON "FURLMS"."TB_LMS_EXRCS_SDDN_QSTN_BSC" ("EXRCS_SDDN_QSTN_BSC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "FURLMS"."SYS_IL0001301487C00004$$" ON "FURLMS"."TB_LMS_EXRCS_SDDN_QSTN_BSC" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC IS '연습돌발문항기본';
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.EXRCS_SDDN_QSTN_BSC_ID IS '연습돌발문항기본아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.QSTN_TTL IS '문항제목'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.QSTN_CTS IS '문항내용'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.QSTNS_CMPTNYN IS '문제출제완료여부'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.QSTN_GRP_ID IS '문항그룹아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.LCTR_WKNO_SCHDL_ID IS '강의주차일정아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.QSTN_GBNCD IS '문항구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.DELYN IS '삭제여부'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.REG_DTTM IS '등록일시'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN FURLMS.TB_LMS_EXRCS_SDDN_QSTN_BSC.PREV_SMSTR_IMPORTYN IS '이전학기가져오기여부'