CREATE TABLE "FURLMS"."TB_LMS_SBJCT_TMPLT" 
   (	"SBJCT_TMPLT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_REF_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"RGLRYN" CHAR(1), 
	"CRS_MSTR_ID" VARCHAR2(30), 
	"SMSTR_CHRT_ID" VARCHAR2(30), 
	"SBJCT_GBNCD" VARCHAR2(10), 
	"CRCLMN_NO" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCTNM" VARCHAR2(200) NOT NULL ENABLE, 
	"SBJCT_EXPLN" VARCHAR2(4000), 
	"SBJCT_ENNM" VARCHAR2(200), 
	"SBJCT_YR" CHAR(4) NOT NULL ENABLE, 
	"SBJCT_SMSTR" CHAR(2) NOT NULL ENABLE, 
	"SBJCT_TYCD" VARCHAR2(30), 
	"EDU_MTHD_TYCD" VARCHAR2(10), 
	"CRDTS" NUMBER(7,0), 
	"RVW_PSBL_GBNCD" VARCHAR2(10), 
	"RVW_SDTTM" VARCHAR2(14), 
	"RVW_EDTTM" VARCHAR2(14), 
	"DVCLAS_NO" NUMBER(3,0), 
	"WHOL_WK_CNT" NUMBER(7,0), 
	"DEPT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CMCRS_GBNCD" VARCHAR2(30), 
	"CMCRS_GBNNM" VARCHAR2(100), 
	"LRN_CNTRL_GBNCD" VARCHAR2(10), 
	"FNSH_PROC_MTHD_CD" VARCHAR2(10), 
	"FNSH_SCR" NUMBER(7,0), 
	"FNSH_SCR_DELRT" NUMBER(5,2), 
	"ETC_DELRT" NUMBER(5,2), 
	"ATNDC_DELRT" NUMBER(5,2), 
	"ASMT_DELRT" NUMBER(5,2), 
	"DSCS_DELRT" NUMBER(5,2), 
	"EXAM_DELRT" NUMBER(5,2), 
	"TEAM_ACTV_DELRT" NUMBER(5,2), 
	"LCTR_SDTTM" VARCHAR2(14), 
	"LCTR_EDTTM" VARCHAR2(14), 
	"ATNDLC_CERT_PROC_MTHD_CD" VARCHAR2(10), 
	"ATNDLC_QUOTA" NUMBER(7,0), 
	"ATNDLC_CERT_STSCD" VARCHAR2(10), 
	"ATNDLC_APLY_SDTTM" VARCHAR2(14), 
	"ATNDLC_APLY_EDTTM" VARCHAR2(14), 
	"ATNDLC_SDTTM" VARCHAR2(14), 
	"ATNDLC_EDTTM" VARCHAR2(14), 
	"AUDIT_SDTTM" VARCHAR2(14), 
	"AUDIT_EDTTM" VARCHAR2(14), 
	"MRK_PROC_SDTTM" VARCHAR2(14), 
	"MRK_PROC_EDTTM" VARCHAR2(14), 
	"MRK_EVL_GBNCD" VARCHAR2(10), 
	"MRK_INQ_SRVY_ID" VARCHAR2(30), 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"UNIV_TYCD" VARCHAR2(30), 
	"UNIV_ID" VARCHAR2(10), 
	"SCR_EVL_GBNCD" VARCHAR2(10), 
	"KYWD" VARCHAR2(2000), 
	"LCTR_FRMT_GBNCD" VARCHAR2(10), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"LCTR_GBNCD" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_SBJCT_MSTR" PRIMARY KEY ("SBJCT_TMPLT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "FURLMS"."PK_TB_LMS_SBJCT" ON "FURLMS"."TB_LMS_SBJCT_TMPLT" ("SBJCT_TMPLT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "FURLMS"."SBJCT_TMPLT_UNIQ_IDX01" ON "FURLMS"."TB_LMS_SBJCT_TMPLT" (CASE  WHEN "DELYN"='N' THEN "SMSTR_CHRT_ID" END , CASE  WHEN "DELYN"='N' THEN LOWER(TRIM("SBJCTNM")) END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FURLMS" ;

COMMENT ON TABLE FURLMS.TB_LMS_SBJCT_TMPLT IS '과목템플릿';
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_TMPLT_ID IS '과목템플릿아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_REF_TYCD IS '과목참조유형코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.RGLRYN IS '정규여부'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.CRS_MSTR_ID IS '과정마스터아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SMSTR_CHRT_ID IS '학기기수아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_GBNCD IS '과목구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.CRCLMN_NO IS '교과목번호'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCTNM IS '과목명'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_EXPLN IS '과목설명'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_ENNM IS '과목영문명'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_YR IS '과목연도'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_SMSTR IS '과목학기'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SBJCT_TYCD IS '과목유형코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.EDU_MTHD_TYCD IS '교육방법유형코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.CRDTS IS '학점'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.RVW_PSBL_GBNCD IS '복습가능구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.RVW_SDTTM IS '복습시작일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.RVW_EDTTM IS '복습종료일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.DVCLAS_NO IS '분반번호'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.WHOL_WK_CNT IS '전체주차수'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.DEPT_ID IS '학과부서아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.CMCRS_GBNCD IS '이수구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.CMCRS_GBNNM IS '이수구분명'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.LRN_CNTRL_GBNCD IS '학습제어구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.FNSH_PROC_MTHD_CD IS '수료처리방법코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.FNSH_SCR IS '수료점수'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.FNSH_SCR_DELRT IS '수료점수삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ETC_DELRT IS '기타삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDC_DELRT IS '출석삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ASMT_DELRT IS '과제삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.DSCS_DELRT IS '토론삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.EXAM_DELRT IS '시험삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.TEAM_ACTV_DELRT IS '팀활동삭제비율'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.LCTR_SDTTM IS '강의시작일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.LCTR_EDTTM IS '강의종료일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_CERT_PROC_MTHD_CD IS '수강인증처리방법코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_QUOTA IS '수강정원'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_CERT_STSCD IS '수강인증상태코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_APLY_SDTTM IS '수강신청시작일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_APLY_EDTTM IS '수강신청종료일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_SDTTM IS '수강시작일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.ATNDLC_EDTTM IS '수강종료일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.AUDIT_SDTTM IS '청강시작일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.AUDIT_EDTTM IS '청강종료일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.MRK_PROC_SDTTM IS '성적처리시작일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.MRK_PROC_EDTTM IS '성적처리종료일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.MRK_EVL_GBNCD IS '성적평가구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.MRK_INQ_SRVY_ID IS '성적조회설문아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.USEYN IS '사용여부'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.DELYN IS '삭제여부'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.UNIV_TYCD IS '대학교유형코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.UNIV_ID IS '대학교아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.SCR_EVL_GBNCD IS '점수평가구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.KYWD IS '키워드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.LCTR_FRMT_GBNCD IS '강의형식구분코드'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_TMPLT.LCTR_GBNCD IS '강의구분코드'