CREATE TABLE "DEV_LMS"."TB_LMS_LCTR" 
   (	"LCTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_WKNO_SCHDL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTRNM" VARCHAR2(200) NOT NULL ENABLE, 
	"LCTR_SEQNO" NUMBER(7,0) NOT NULL ENABLE, 
	"LCTR_GBNCD" VARCHAR2(10) NOT NULL ENABLE, 
	"PRG_RFLTYN" CHAR(1), 
	"LCTR_SDTTM" VARCHAR2(14), 
	"LCTR_EDTTM" VARCHAR2(14), 
	"RCMD_ATNDLC_MNTS" NUMBER(7,0), 
	"PRGRT_GBNCD" VARCHAR2(30), 
	"INQYN" CHAR(1), 
	"OTSDPRD_ATNDLCYN" CHAR(1), 
	"OTSDPRD_ATNDLC_DAY_CNT" NUMBER(7,0), 
	"OTSDPRD_ATNDLC_RCG_STSCD" VARCHAR2(10), 
	"ATNDLC_STS_CHKYN" CHAR(1), 
	"ATNDLC_NWIN_USEYN" CHAR(1), 
	"ATNDLC_SCNDS" NUMBER(7,0), 
	"MKUP_CLAS_GBNCD" VARCHAR2(10), 
	"VDOCLAS_SDTTM" VARCHAR2(14), 
	"VDOCLAS_EDTTM" VARCHAR2(14), 
	"VDOCLAS_RM_PSWD" VARCHAR2(30), 
	"VDOCLAS_EXPLN" VARCHAR2(4000), 
	"VDOCLAS_RM_CNTN_ID" VARCHAR2(30), 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_LCTR" PRIMARY KEY ("LCTR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_LCTR_WKNO_SCHDL_TO_LCTR" FOREIGN KEY ("LCTR_WKNO_SCHDL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_LCTR_WKNO_SCHDL" ("LCTR_WKNO_SCHDL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_LCTR" ON "DEV_LMS"."TB_LMS_LCTR" ("LCTR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_LCTR IS '강의';
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTR_ID IS '강의아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTR_WKNO_SCHDL_ID IS '강의주차일정아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTRNM IS '강의명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTR_SEQNO IS '강의순서'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTR_GBNCD IS '강의구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.PRG_RFLTYN IS '진도반영여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTR_SDTTM IS '강의시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.LCTR_EDTTM IS '강의종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.RCMD_ATNDLC_MNTS IS '권장수강시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.PRGRT_GBNCD IS '진도율구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.INQYN IS '조회여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.OTSDPRD_ATNDLCYN IS '기간외수강여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.OTSDPRD_ATNDLC_DAY_CNT IS '기간외수강일수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.OTSDPRD_ATNDLC_RCG_STSCD IS '기간외수강인정상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.ATNDLC_STS_CHKYN IS '수강상태체크여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.ATNDLC_NWIN_USEYN IS '수강새창사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.ATNDLC_SCNDS IS '수강시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.MKUP_CLAS_GBNCD IS '휴보강수업구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.VDOCLAS_SDTTM IS '화상수업시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.VDOCLAS_EDTTM IS '화상수업종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.VDOCLAS_RM_PSWD IS '화상수업방비밀번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.VDOCLAS_EXPLN IS '화상수업설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.VDOCLAS_RM_CNTN_ID IS '화상수업방접속아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR.MOD_DTTM IS '수정일시'