CREATE TABLE "DEV_LMS"."TB_LMS_RLTM_EXAM" 
   (	"RLTM_EXAM_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_PLANDOC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"RLTM_EXAM_GBNCD" VARCHAR2(10) NOT NULL ENABLE, 
	"EXAM_QSTNS_DLGTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"QSTNS_TRGTR" VARCHAR2(30), 
	"RLTM_TKEXAM_GBNCD" VARCHAR2(10), 
	"EXAM_MNTS" NUMBER(5,0), 
	"MRK_OYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"END_EXAMPPR_OYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"OPEN_OPTN_GBNCD" VARCHAR2(10), 
	"AUTO_TRNSLTN_PRVNTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"VOICE_VDO_INCLDYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"EXAM_OP_AUTH_DLGTNYN" CHAR(1) DEFAULT 'N', 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_RLTM_EXAM" PRIMARY KEY ("RLTM_EXAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_LCTR_PLANDOC_TO_RLTM_EXAM" FOREIGN KEY ("LCTR_PLANDOC_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_LCTR_PLANDOC" ("LCTR_PLANDOC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_RLTM_EXAM" ON "DEV_LMS"."TB_LMS_RLTM_EXAM" ("RLTM_EXAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_RLTM_EXAM IS '실시간시험';
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.RLTM_EXAM_ID IS '실시간시험아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.LCTR_PLANDOC_ID IS '강의계획서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.EXAM_TYCD IS '시험유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.RLTM_EXAM_GBNCD IS '실시간시험구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.EXAM_QSTNS_DLGTNYN IS '시험문제출제위임여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.QSTNS_TRGTR IS '출제위임대상자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.RLTM_TKEXAM_GBNCD IS '실시간응시구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.EXAM_MNTS IS '시험시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.MRK_OYN IS '성적공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.END_EXAMPPR_OYN IS '종료후시험지공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.OPEN_OPTN_GBNCD IS '공개옵션구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.AUTO_TRNSLTN_PRVNTNYN IS '자동해석방지여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.VOICE_VDO_INCLDYN IS '음성동영상포함여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.EXAM_OP_AUTH_DLGTNYN IS '시험운영권한위임여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_RLTM_EXAM.MOD_DTTM IS '수정일시'