CREATE TABLE "DEV_LMS"."TB_LMS_USER_INFO_CHG_HSTRY" 
   (	"USER_INFO_CHG_HSTRY_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USERINFO_CHG_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"CHGBFR_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"CHGAFT_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"CNTN_IP" VARCHAR2(15) NOT NULL ENABLE, 
	"CNTN_BRWSR" VARCHAR2(1000) NOT NULL ENABLE, 
	"CNTN_DVC_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"CHG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_USER_INFO_CHG_HSTRY" PRIMARY KEY ("USER_INFO_CHG_HSTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_INFO_CHG_HSTRY" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_INFO_CHG_HSTRY" ON "DEV_LMS"."TB_LMS_USER_INFO_CHG_HSTRY" ("USER_INFO_CHG_HSTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY IS '사용자정보변경이력';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.USER_INFO_CHG_HSTRY_ID IS '사용자정보변경이력아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.USERINFO_CHG_TYCD IS '사용자정보변경유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.CHGBFR_CTS IS '변경전내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.CHGAFT_CTS IS '변경후내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.CNTN_IP IS '접속아이피'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.CNTN_BRWSR IS '접속브라우저'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.CNTN_DVC_TYCD IS '접속기기유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_INFO_CHG_HSTRY.CHG_DTTM IS '변경일시'