CREATE TABLE "DEV_LMS"."TB_LMS_ATNDC_SCR_CRTR_STNG" 
   (	"CRTR_STNG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SMSTR_CHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"STNG_SEQNO" NUMBER(3,0), 
	"STRT_AVG_PRGRT" NUMBER(5,2), 
	"END_AVG_PRGRT" NUMBER(5,2), 
	"ATNDC_SCR" NUMBER(3,0), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_ATNDC_SCR_CRTR_STNG" PRIMARY KEY ("CRTR_STNG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SC_TO_ASCS" FOREIGN KEY ("SMSTR_CHRT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SMSTR_CHRT" ("SMSTR_CHRT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ATNDC_SCR_CRTR_STNG" ON "DEV_LMS"."TB_LMS_ATNDC_SCR_CRTR_STNG" ("CRTR_STNG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG IS '출석점수기준설정';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.CRTR_STNG_ID IS '기준설정아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.SMSTR_CHRT_ID IS '학기기수아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.STNG_SEQNO IS '설정순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.STRT_AVG_PRGRT IS '시작평균진도율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.END_AVG_PRGRT IS '종료평균진도율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.ATNDC_SCR IS '출석점수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDC_SCR_CRTR_STNG.MOD_DTTM IS '수정일시'