CREATE TABLE "DEV_LMS"."TB_LMS_LCTR_CONTS_LRN_HSTRY" 
   (	"LCTR_CONTS_LRN_HSTRY_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_CONTS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTS_LRN_RND_CNT" NUMBER(3,0), 
	"CONTS_LRN_TOT_MNTS" NUMBER(22,0) NOT NULL ENABLE, 
	"CONTS_LRN_STSCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CONTS_LRN_SDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"CONTS_LRN_EDTTM" VARCHAR2(14), 
	"CONTS_LRN_RCNT_STTM" VARCHAR2(14) NOT NULL ENABLE, 
	"CONTS_LRN_RCNT_EDTTM" VARCHAR2(14), 
	"CONTS_LRN_RCNT_MNTS" NUMBER(7,0) NOT NULL ENABLE, 
	"CONTS_LRN_MAX_PSTN" VARCHAR2(1000), 
	"CONTS_LRN_RCNT_END_PSTN" VARCHAR2(1000), 
	"CONTS_LRN_PRGRT" NUMBER(5,2) NOT NULL ENABLE, 
	"CONTS_LRN_OTSDPRD_MNTS" NUMBER(7,0), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_LCTR_CONTS_LRN_HSTRY" PRIMARY KEY ("LCTR_CONTS_LRN_HSTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_LC_TO_LCLH" FOREIGN KEY ("LCTR_CONTS_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_LCTR_CONTS" ("LCTR_CONTS_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_LCLH" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_LCTR_CONTS_LRN_HSTRY" ON "DEV_LMS"."TB_LMS_LCTR_CONTS_LRN_HSTRY" ("LCTR_CONTS_LRN_HSTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY IS '강의콘텐츠학습이력';
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.LCTR_CONTS_LRN_HSTRY_ID IS '강의콘텐츠학습이력아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.LCTR_CONTS_ID IS '강의콘텐츠아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_RND_CNT IS '콘텐츠학습회차수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_TOT_MNTS IS '콘텐츠학습총시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_STSCD IS '콘텐츠학습상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_SDTTM IS '콘텐츠학습시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_EDTTM IS '콘텐츠학습종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_RCNT_STTM IS '콘텐츠학습최근시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_RCNT_EDTTM IS '콘텐츠학습최근종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_RCNT_MNTS IS '콘텐츠학습최근시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_MAX_PSTN IS '콘텐츠학습최대위치'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_RCNT_END_PSTN IS '콘텐츠학습최근종료위치'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_PRGRT IS '콘텐츠학습진도율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.CONTS_LRN_OTSDPRD_MNTS IS '콘텐츠학습기간외시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS_LRN_HSTRY.MOD_DTTM IS '수정일시'