CREATE TABLE "DEV_LMS"."TB_LMS_EXAM_BSC" 
   (	"EXAM_BSC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_WKNO_SCHDL_ID" VARCHAR2(30), 
	"EXAM_GRP_ID" VARCHAR2(30), 
	"EXAM_TYCD" VARCHAR2(10), 
	"EXAM_GBNCD" VARCHAR2(30), 
	"EXAM_TTL" VARCHAR2(200) NOT NULL ENABLE, 
	"EXAM_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"TKEXAM_MTHD_CD" VARCHAR2(10), 
	"QSTN_DSPLY_GBNCD" VARCHAR2(10), 
	"EXAMPPR_OYN" CHAR(1), 
	"AVG_MRK_OYN" CHAR(1), 
	"MRK_OPEN_SDTTM" VARCHAR2(14), 
	"PUSH_NOTIYN" CHAR(1), 
	"SEC_CERT_CD" VARCHAR2(10), 
	"IMDT_ANSW_SHT_INQYN" CHAR(1), 
	"MAX_TKEXAM_CNT" NUMBER(3,0), 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"REGYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"QSTNS_DLGTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MRK_OYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DVCLAS_REGYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_QSTNS_CMPTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"QSTN_RNDMYN" CHAR(1) NOT NULL ENABLE, 
	"QSTN_VWITM_RNDMYN" CHAR(1) NOT NULL ENABLE, 
	"QSTN_CNDDT_USEYN" CHAR(1) NOT NULL ENABLE, 
	"MRK_RFLTYN" CHAR(1) NOT NULL ENABLE, 
	"MRK_RFLTRT" NUMBER(5,2) NOT NULL ENABLE, 
	"EXAMTM_ALLOC_GBNCD" VARCHAR2(10) NOT NULL ENABLE, 
	"EXAMTM_EXPSR_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"LRN_GRP_SUBASMT_STNGYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"BYTEAM_SUBREXAM_USEYN" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "PK_TB_LMS_EXAM_BSC" PRIMARY KEY ("EXAM_BSC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EXAM_GRP_TO_EXAM_BSC" FOREIGN KEY ("EXAM_GRP_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_GRP" ("EXAM_GRP_ID") ENABLE, 
	 CONSTRAINT "FK_SBJCT_TO_EXAM_BSC" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "DEV_LMS"."IDX_EXAM_BSC_01" ON "DEV_LMS"."TB_LMS_EXAM_BSC" ("SBJCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAM_BSC" ON "DEV_LMS"."TB_LMS_EXAM_BSC" ("EXAM_BSC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAM_BSC IS '시험기본';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_BSC_ID IS '시험기본아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.LCTR_WKNO_SCHDL_ID IS '강의주차일정아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_GRP_ID IS '시험그룹아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_TYCD IS '시험유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_GBNCD IS '시험구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_TTL IS '시험제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_CTS IS '시험내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.TKEXAM_MTHD_CD IS '시험응시방법코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.QSTN_DSPLY_GBNCD IS '문항화면표시구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAMPPR_OYN IS '시험지공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.AVG_MRK_OYN IS '평균성적공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MRK_OPEN_SDTTM IS '성적공개시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.PUSH_NOTIYN IS '푸시알림여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.SEC_CERT_CD IS 'SEC인증코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.IMDT_ANSW_SHT_INQYN IS '즉시답안조회여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MAX_TKEXAM_CNT IS '최대응시횟수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.REGYN IS '등록여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.QSTNS_DLGTNYN IS '문제출제위임여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MRK_OYN IS '성적공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.DVCLAS_REGYN IS '분반등록여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAM_QSTNS_CMPTNYN IS '시험문제출제완료여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.QSTN_RNDMYN IS '문항무작위여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.QSTN_VWITM_RNDMYN IS '문항보기항목무작위여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.QSTN_CNDDT_USEYN IS '문항후보사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MRK_RFLTYN IS '성적반영여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.MRK_RFLTRT IS '성적반영비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAMTM_ALLOC_GBNCD IS '시험시간배정구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.EXAMTM_EXPSR_TYCD IS '시험시간노출유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.LRN_GRP_SUBASMT_STNGYN IS '학습그룹부과제설정여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_BSC.BYTEAM_SUBREXAM_USEYN IS '팀별부시험사용여부'