CREATE TABLE "DEV_LMS"."TB_LMS_SMSTR_CHRT" 
   (	"SMSTR_CHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"DGRS_YR" CHAR(4) NOT NULL ENABLE, 
	"DGRS_SMSTR_CHRT" CHAR(5) NOT NULL ENABLE, 
	"SMSTR_CHRT_GBNCD" VARCHAR2(10), 
	"SMSTR_CHRT_TYCD" VARCHAR2(10), 
	"SMSTR_CHRT_STSCD" VARCHAR2(10), 
	"SMSTR_CHRT_DATA_LNKGYN" CHAR(1), 
	"SMSTR_CHRTNM" VARCHAR2(200) NOT NULL ENABLE, 
	"SMSTR_CHRT_OP_SDTTM" VARCHAR2(14), 
	"SMSTR_CHRT_OP_EDTTM" VARCHAR2(14), 
	"OFLN_LRN_MNGYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"ATNDLC_APLY_SDTTM" VARCHAR2(14), 
	"ATNDLC_APLY_EDTTM" VARCHAR2(14), 
	"ATNDLC_MOD_SDTTM" VARCHAR2(14), 
	"ATNDLC_MOD_EDTTM" VARCHAR2(14), 
	"ATNDLC_SDTTM" VARCHAR2(14), 
	"ATNDLC_EDTTM" VARCHAR2(14), 
	"MRK_EVL_SDTTM" VARCHAR2(14), 
	"MRK_EVL_EDTTM" VARCHAR2(14), 
	"MRK_OPEN_SDTTM" VARCHAR2(14), 
	"MRK_OPEN_EDTTM" VARCHAR2(14), 
	"MBL_ATNDC_USEYN" CHAR(1), 
	"NOW_SMSTRYN" CHAR(1), 
	"RVW_EDTTM" VARCHAR2(14), 
	"PROF_ACCSS_PBL_SDTTM" VARCHAR2(14), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_SMSTR_CHRT" PRIMARY KEY ("SMSTR_CHRT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ORG_TO_SMSTR_CHRT" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_SMSTR_CHRT" ON "DEV_LMS"."TB_LMS_SMSTR_CHRT" ("SMSTR_CHRT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_SMSTR_CHRT IS '학기기수';
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_ID IS '학기기수아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.DGRS_YR IS '학위연도'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.DGRS_SMSTR_CHRT IS '학위학기기수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_GBNCD IS '학기기수구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_TYCD IS '학기기수유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_STSCD IS '학기기수상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_DATA_LNKGYN IS '학기기수자료연계여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRTNM IS '학기기수명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_OP_SDTTM IS '학기기수운영시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.SMSTR_CHRT_OP_EDTTM IS '학기기수운영종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.OFLN_LRN_MNGYN IS '오프라인학습관리여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ATNDLC_APLY_SDTTM IS '수강신청시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ATNDLC_APLY_EDTTM IS '수강신청종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ATNDLC_MOD_SDTTM IS '수강수정시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ATNDLC_MOD_EDTTM IS '수강수정종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ATNDLC_SDTTM IS '수강시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.ATNDLC_EDTTM IS '수강종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MRK_EVL_SDTTM IS '성적평가시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MRK_EVL_EDTTM IS '성적평가종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MRK_OPEN_SDTTM IS '성적공개시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MRK_OPEN_EDTTM IS '성적공개종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MBL_ATNDC_USEYN IS '모바일출석사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.NOW_SMSTRYN IS '현재학기여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.RVW_EDTTM IS '복습종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.PROF_ACCSS_PBL_SDTTM IS '교수접근가능시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SMSTR_CHRT.MOD_DTTM IS '수정일시'