CREATE TABLE "DEV_LMS"."TB_LMS_SBJCT" 
   (	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"PROF_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_REF_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CRS_MSTR_ID" VARCHAR2(30), 
	"SMSTR_CHRT_ID" VARCHAR2(30), 
	"SBJCT_GBNCD" VARCHAR2(10), 
	"SBJCT_TYCD" VARCHAR2(30), 
	"EDU_MTHD_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"RGLRYN" CHAR(1), 
	"CRCLMN_NO" VARCHAR2(30), 
	"SBJCTNM" VARCHAR2(200) NOT NULL ENABLE, 
	"SBJCT_EXPLN" VARCHAR2(4000) NOT NULL ENABLE, 
	"SBJCT_ENNM" VARCHAR2(200) NOT NULL ENABLE, 
	"SBJCT_YR" CHAR(4) NOT NULL ENABLE, 
	"SBJCT_SMSTR" CHAR(2) NOT NULL ENABLE, 
	"CRDTS" NUMBER(7,0), 
	"RVW_PSBL_GBNCD" VARCHAR2(10), 
	"RVW_SDTTM" VARCHAR2(14), 
	"RVW_EDTTM" VARCHAR2(14), 
	"DVCLAS_GRPCD" VARCHAR2(10), 
	"DVCLAS_NO" VARCHAR2(10), 
	"DVCLAS_NCKNM" VARCHAR2(200), 
	"WHOL_WK_CNT" NUMBER(7,0) NOT NULL ENABLE, 
	"DEPT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CMCRS_GBNCD" VARCHAR2(10), 
	"CMCRS_GBNNM" VARCHAR2(100), 
	"LRN_CNTRL_GBNCD" VARCHAR2(10), 
	"FNSH_PROC_MTHD_CD" VARCHAR2(10), 
	"FNSH_SCR" NUMBER(7,0), 
	"FNSH_SCR_DELRT" NUMBER(5,2), 
	"ETC_DELRT" NUMBER(5,2), 
	"ATNDC_DELRT" NUMBER(5,2), 
	"ASMT_DELRT" NUMBER(5,2), 
	"DSCS_DELRT" NUMBER(5,2), 
	"EXAM_DELRT" NUMBER(5,2), 
	"TEAM_ACTV_DELRT" NUMBER(5,2), 
	"LCTR_SDTTM" VARCHAR2(14), 
	"LCTR_EDTTM" VARCHAR2(14), 
	"ATNDLC_CERT_PROC_MTHD_CD" VARCHAR2(10), 
	"ATNDLC_QUOTA" NUMBER(7,0), 
	"ATNDLC_CERT_STSCD" VARCHAR2(10), 
	"ATNDLC_APLY_SDTTM" VARCHAR2(14), 
	"ATNDLC_APLY_EDTTM" VARCHAR2(14), 
	"ATNDLC_SDTTM" VARCHAR2(14), 
	"ATNDLC_EDTTM" VARCHAR2(14), 
	"AUDIT_SDTTM" VARCHAR2(14), 
	"AUDIT_EDTTM" VARCHAR2(14), 
	"MRK_PROC_SDTTM" VARCHAR2(14), 
	"MRK_PROC_EDTTM" VARCHAR2(14), 
	"MRK_EVL_GBNCD" VARCHAR2(10), 
	"MRK_INQ_SRVY_ID" VARCHAR2(30), 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SCR_EVL_GBNCD" VARCHAR2(10), 
	"KYWD" VARCHAR2(2000), 
	"LCTR_FRMT_GBNCD" VARCHAR2(10), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_SBJCT_OFRNG" PRIMARY KEY ("SBJCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_SBJCT_OFRNG" ON "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_SBJCT IS '과목';
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.PROF_ID IS '교수아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_REF_TYCD IS '과목참조유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.CRS_MSTR_ID IS '과정마스터아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SMSTR_CHRT_ID IS '학기기수아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_GBNCD IS '과목구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_TYCD IS '과목유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.EDU_MTHD_TYCD IS '교육방법유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.RGLRYN IS '정규여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.CRCLMN_NO IS '교과목번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCTNM IS '과목명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_EXPLN IS '과목설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_ENNM IS '과목영문명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_YR IS '과목연도'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SBJCT_SMSTR IS '과목학기'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.CRDTS IS '학점'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.RVW_PSBL_GBNCD IS '복습가능구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.RVW_SDTTM IS '복습시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.RVW_EDTTM IS '복습종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.DVCLAS_GRPCD IS '분반그룹코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.DVCLAS_NO IS '분반번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.DVCLAS_NCKNM IS '분반별칭'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.WHOL_WK_CNT IS '전체주차수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.DEPT_ID IS '학과부서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.CMCRS_GBNCD IS '이수구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.CMCRS_GBNNM IS '이수구분명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.LRN_CNTRL_GBNCD IS '학습제어구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.FNSH_PROC_MTHD_CD IS '수료처리방법코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.FNSH_SCR IS '수료점수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.FNSH_SCR_DELRT IS '수료점수삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ETC_DELRT IS '기타삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDC_DELRT IS '출석삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ASMT_DELRT IS '과제삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.DSCS_DELRT IS '토론삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.EXAM_DELRT IS '시험삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.TEAM_ACTV_DELRT IS '팀활동삭제비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.LCTR_SDTTM IS '강의시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.LCTR_EDTTM IS '강의종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_CERT_PROC_MTHD_CD IS '수강인증처리방법코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_QUOTA IS '수강정원'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_CERT_STSCD IS '수강인증상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_APLY_SDTTM IS '수강신청시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_APLY_EDTTM IS '수강신청종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_SDTTM IS '수강시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.ATNDLC_EDTTM IS '수강종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.AUDIT_SDTTM IS '청강시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.AUDIT_EDTTM IS '청강종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.MRK_PROC_SDTTM IS '성적처리시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.MRK_PROC_EDTTM IS '성적처리종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.MRK_EVL_GBNCD IS '성적평가구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.MRK_INQ_SRVY_ID IS '성적조회설문아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.SCR_EVL_GBNCD IS '점수평가구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.KYWD IS '키워드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.LCTR_FRMT_GBNCD IS '강의형식구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT.MOD_DTTM IS '수정일시'