CREATE TABLE "DEV_LMS"."TB_LMS_USER_AUTHRT" 
   (	"USER_AUTHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_AUTHRT" PRIMARY KEY ("USER_AUTHRT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_AUTHRT" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_AUTHRT_TO_USER_AUTHRT" FOREIGN KEY ("AUTHRT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_AUTHRT" ("AUTHRT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_AUTHRT" ON "DEV_LMS"."TB_LMS_USER_AUTHRT" ("USER_AUTHRT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_AUTHRT IS '사용자권한';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.USER_AUTHRT_ID IS '사용자권한아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.AUTHRT_ID IS '권한아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_AUTHRT.MOD_DTTM IS '수정일시'