CREATE TABLE "DEV_LMS"."TB_LMS_LOG_USER_ACTV" 
   (	"USER_ACTV_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30), 
	"REQ_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_REQ_URL" VARCHAR2(1000) NOT NULL ENABLE, 
	"USER_REQ_MENU" VARCHAR2(1000) NOT NULL ENABLE, 
	"USER_REQ_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"USER_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CNTN_IP" VARCHAR2(15) NOT NULL ENABLE, 
	"CNTN_DVC_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CNTN_BRWSR" VARCHAR2(1000) NOT NULL ENABLE, 
	"ACTV_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"SESS_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"SESS_SDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"SESS_EDTTM" VARCHAR2(14), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"ACTV_DATETIME" DATE, 
	 CONSTRAINT "PK_TB_LMS_LOG_USER_ACTV" PRIMARY KEY ("USER_ACTV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_LOG_USER_ACTV" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_LOG_USER_ACTV" ON "DEV_LMS"."TB_LMS_LOG_USER_ACTV" ("USER_ACTV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_LOG_USER_ACTV IS '로그사용자활동';
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.USER_ACTV_ID IS '사용자활동아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.REQ_TYCD IS '요청유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.USER_REQ_URL IS '사용자요청URL'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.USER_REQ_MENU IS '사용자요청메뉴'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.USER_REQ_CTS IS '사용자요청내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.USER_TYCD IS '사용자유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.CNTN_IP IS '접속아이피'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.CNTN_DVC_TYCD IS '접속기기유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.CNTN_BRWSR IS '접속브라우저'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.ACTV_DTTM IS '활동일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.SESS_ID IS '세션아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.SESS_SDTTM IS '세션시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.SESS_EDTTM IS '세션종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LOG_USER_ACTV.MOD_DTTM IS '수정일시'