CREATE TABLE "DEV_LMS"."TB_LMS_USER" 
   (	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_RPRS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USERNM" VARCHAR2(200) NOT NULL ENABLE, 
	"USER_ENNM" VARCHAR2(200), 
	"USER_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"USER_STNG_CTS" VARCHAR2(4000), 
	"DEPT_ID" VARCHAR2(30), 
	"PHOTO_FILE_ID" VARCHAR2(30), 
	"USER_STSCD" VARCHAR2(10), 
	"MN_DSBL_CD" VARCHAR2(10), 
	"MN_DSBL_GRDCD" VARCHAR2(10), 
	"SCND_DSBL_CD" VARCHAR2(10), 
	"SCND_DSBL_GRDCD" VARCHAR2(10), 
	"EXAM_SPRT_APLY_TYCD" VARCHAR2(10), 
	"SNRYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"GNDR_TYCD" CHAR(1), 
	"USER_ENV_STNG_CTS" VARCHAR2(4000), 
	"USER_ID_ENCPSWD" VARCHAR2(100) NOT NULL ENABLE, 
	"USER_ID_APLY_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"LGN_CNTNU_FAIL_CNT" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID_LOCKYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"LGN_MTHD_GBNCD" VARCHAR2(30) DEFAULT 'Y' NOT NULL ENABLE, 
	"USER_ID_APRV_DTTM" VARCHAR2(14), 
	"USER_ID_LEAVE_DTTM" VARCHAR2(14), 
	"USER_ID_STSCD" VARCHAR2(10) DEFAULT 'N' NOT NULL ENABLE, 
	"USER_ID_MIGYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DUP_LGN_PRMYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"AUTO_LGN_USEYN" CHAR(1), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"PUSH_TALK_SMS_FLAG" VARCHAR2(10) DEFAULT '0000000111' NOT NULL ENABLE, 
	"SHRTNT_ALIM_RCVYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"EML_ALIM_RCVYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"USE_EML_GBNCD" VARCHAR2(10), 
	"USER_NCNM" VARCHAR2(100), 
	"STDNT_NO" VARCHAR2(30), 
	"DSBLYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_RPRS_TO_USER" FOREIGN KEY ("USER_RPRS_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER_RPRS" ("USER_RPRS_ID") ENABLE, 
	 CONSTRAINT "FK_TB_LMS_ORG_TO_TB_LMS_USER" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER" ON "DEV_LMS"."TB_LMS_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER IS '사용자';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_RPRS_ID IS '사용자대표아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USERNM IS '사용자명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ENNM IS '사용자영문명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_TYCD IS '사용자유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_STNG_CTS IS '사용자설정내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.DEPT_ID IS '학과부서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.PHOTO_FILE_ID IS '사진파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_STSCD IS '사용자상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.MN_DSBL_CD IS '주장애코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.MN_DSBL_GRDCD IS '주장애등급코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.SCND_DSBL_CD IS '부장애코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.SCND_DSBL_GRDCD IS '부장애등급코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.EXAM_SPRT_APLY_TYCD IS '시험지원신청유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.SNRYN IS '고령자여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.GNDR_TYCD IS '성별유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ENV_STNG_CTS IS '사용자환경설정내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_ENCPSWD IS '사용자아이디암호화비밀번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_APLY_DTTM IS '사용자아이디신청일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.LGN_CNTNU_FAIL_CNT IS '로그인연속실패수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_LOCKYN IS '사용자아이디잠금여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.LGN_MTHD_GBNCD IS '로그인방법구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_APRV_DTTM IS '사용자아이디승인일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_LEAVE_DTTM IS '사용자아이디탈퇴일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_STSCD IS '사용자아이디상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_ID_MIGYN IS '사용자아이디데이터마이그레이션여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.DUP_LGN_PRMYN IS '중복로그인허용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.AUTO_LGN_USEYN IS '자동로그인사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.PUSH_TALK_SMS_FLAG IS '푸시톡문자수신플래그'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.SHRTNT_ALIM_RCVYN IS '쪽지알림수신여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.EML_ALIM_RCVYN IS '이메일알림수신여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USE_EML_GBNCD IS '사용이메일구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.USER_NCNM IS '사용자별칭'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.STDNT_NO IS '학생번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER.DSBLYN IS '장애여부'