CREATE TABLE "FURLMS"."TB_LMS_LCTR_CONTS" 
   (	"LCTR_CONTS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTS_SEQNO" NUMBER(7,0) NOT NULL ENABLE, 
	"UP_LCTR_CONTS_ID" VARCHAR2(30), 
	"CONTS_FILE_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTSNM" VARCHAR2(200) NOT NULL ENABLE, 
	"LCTR_CONTS_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CONTS_URL" VARCHAR2(1000) NOT NULL ENABLE, 
	"CONTS_PATH" VARCHAR2(1000) NOT NULL ENABLE, 
	"CONTS_PSTN_CD" VARCHAR2(10) NOT NULL ENABLE, 
	"CONTS_FILE_EXT" VARCHAR2(10), 
	"VDO_MNTS" NUMBER(7,0), 
	"ATNDC_RFLTYN" CHAR(1) NOT NULL ENABLE, 
	"OYN" CHAR(1) NOT NULL ENABLE, 
	"EXRCS_QSTN_ID" VARCHAR2(30), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"SDDN_QSTN_ID" VARCHAR2(30), 
	"SDDN_QSTN_PLY_SEC" NUMBER(7,0), 
	"LANG_CD" VARCHAR2(10), 
	"HTML_SRC" CLOB, 
	"LRN_TOC_TTL" VARCHAR2(200), 
	"LRN_TOC_CTS" CLOB, 
	"ADM_REG_CONTSYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N', 
	"VDO_QLTY_GBNCD" VARCHAR2(10), 
	 CONSTRAINT "PK_TB_LMS_LCTR_CONTS" PRIMARY KEY ("LCTR_CONTS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_LCTR_TO_LCTR_CONTS" FOREIGN KEY ("LCTR_ID")
	  REFERENCES "FURLMS"."TB_LMS_LCTR" ("LCTR_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("HTML_SRC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LRN_TOC_CTS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "FURLMS"."PK_TB_LMS_LCTR_CONTS" ON "FURLMS"."TB_LMS_LCTR_CONTS" ("LCTR_CONTS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "FURLMS"."SYS_IL0001301497C00023$$" ON "FURLMS"."TB_LMS_LCTR_CONTS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "FURLMS"."SYS_IL0001301497C00025$$" ON "FURLMS"."TB_LMS_LCTR_CONTS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE FURLMS.TB_LMS_LCTR_CONTS IS '강의콘텐츠';
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.LCTR_CONTS_ID IS '강의콘텐츠아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.LCTR_ID IS '강의아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTS_SEQNO IS '콘텐츠순번'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.UP_LCTR_CONTS_ID IS '상위강의콘텐츠아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTS_FILE_ID IS '콘텐츠파일아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTSNM IS '콘텐츠명'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.LCTR_CONTS_TYCD IS '강의콘텐츠유형코드'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTS_URL IS '콘텐츠URL'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTS_PATH IS '콘텐츠경로'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTS_PSTN_CD IS '콘텐츠위치코드'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.CONTS_FILE_EXT IS '콘텐츠파일확장자'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.VDO_MNTS IS '동영상시간'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.ATNDC_RFLTYN IS '출석반영여부'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.OYN IS '공개여부'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.EXRCS_QSTN_ID IS '연습문제아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.REG_DTTM IS '등록일시'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.SDDN_QSTN_ID IS '돌발퀴즈아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.SDDN_QSTN_PLY_SEC IS '돌발퀴즈재생시간'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.LANG_CD IS '언어코드'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.HTML_SRC IS 'HTML소스'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.LRN_TOC_TTL IS '학습목차제목'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.LRN_TOC_CTS IS '학습목차내용'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.ADM_REG_CONTSYN IS '관리자등록콘텐츠여부'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.DELYN IS '삭제여부'
COMMENT ON COLUMN FURLMS.TB_LMS_LCTR_CONTS.VDO_QLTY_GBNCD IS '동영상화질구분코드'