CREATE TABLE "DEV_LMS"."TB_LMS_ATFL_MAXSZ" 
   (	"ATFL_MAXSZ_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MAXSZ" NUMBER(22,0) NOT NULL ENABLE, 
	"MAXSZ_ACTV_GRP_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"MAXSZ_ACTV_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_ATFL_MAXSZ" PRIMARY KEY ("ATFL_MAXSZ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ATFL_MAXSZ" ON "DEV_LMS"."TB_LMS_ATFL_MAXSZ" ("ATFL_MAXSZ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ATFL_MAXSZ IS '첨부파일최대크기';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.ATFL_MAXSZ_ID IS '첨부파일최대크기아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.MAXSZ IS '최대크기'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.MAXSZ_ACTV_GRP_TYCD IS '최대크기활동그룹유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.MAXSZ_ACTV_TYCD IS '최대크기활동유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_MAXSZ.MOD_DTTM IS '수정일시'