CREATE TABLE "DEV_LMS"."TB_LMS_MENU_OPTN" 
   (	"MENU_OPTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_OPTN_CTGRCD" VARCHAR2(10) NOT NULL ENABLE, 
	"MENU_OPTN_CD" VARCHAR2(10) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_MENU_OPTN" PRIMARY KEY ("MENU_OPTN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MENU_TO_MENU_OPTN" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_MENU_OPTN" ON "DEV_LMS"."TB_LMS_MENU_OPTN" ("MENU_OPTN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_MENU_OPTN IS '메뉴옵션';
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.MENU_OPTN_ID IS '메뉴옵션아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.MENU_OPTN_CTGRCD IS '메뉴옵션분류코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.MENU_OPTN_CD IS '메뉴옵션코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_OPTN.MOD_DTTM IS '수정일시'