CREATE TABLE "DEV_LMS"."TB_LMS_USER_ONSLF_VRFCTN" 
   (	"USER_ONSLF_VRFCTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ONSLF_VRFCTN_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"ONSLF_VRFCTN_REQ_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"RSLT_CD" VARCHAR2(10), 
	"ONSLF_VRFCTN_CTS" VARCHAR2(4000), 
	"TTL" VARCHAR2(4000), 
	"CTS" VARCHAR2(4000), 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_ONSLF_VRFCTN" PRIMARY KEY ("USER_ONSLF_VRFCTN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_ONSLF_VRFCTN" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_ONSLF_VRFCTN" ON "DEV_LMS"."TB_LMS_USER_ONSLF_VRFCTN" ("USER_ONSLF_VRFCTN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN IS '사용자본인확인';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.USER_ONSLF_VRFCTN_ID IS '사용자본인확인아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.ONSLF_VRFCTN_TYCD IS '본인확인유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.ONSLF_VRFCTN_REQ_DTTM IS '본인확인요청일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.RSLT_CD IS '결과코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.ONSLF_VRFCTN_CTS IS '본인확인내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.TTL IS '제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.CTS IS '내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_ONSLF_VRFCTN.MOD_DTTM IS '수정일시'