CREATE TABLE "DEV_LMS"."TB_LMS_LCTR_CONTS" 
   (	"LCTR_CONTS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTS_SEQNO" NUMBER(7,0) NOT NULL ENABLE, 
	"UP_LCTR_CONTS_ID" VARCHAR2(30), 
	"CONTS_FILE_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTSNM" VARCHAR2(200) NOT NULL ENABLE, 
	"LCTR_CONTS_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CONTS_URL" VARCHAR2(1000) NOT NULL ENABLE, 
	"CONTS_PATH" VARCHAR2(1000) NOT NULL ENABLE, 
	"CONTS_PSTN_CD" VARCHAR2(10) NOT NULL ENABLE, 
	"CONTS_FILE_EXT" VARCHAR2(10), 
	"VDO_MNTS" NUMBER(7,0), 
	"ATNDC_RFLTYN" CHAR(1) NOT NULL ENABLE, 
	"OYN" CHAR(1) NOT NULL ENABLE, 
	"EXRCS_QSTN_ID" VARCHAR2(30), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_LCTR_CONTS" PRIMARY KEY ("LCTR_CONTS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_LCTR_TO_LCTR_CONTS" FOREIGN KEY ("LCTR_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_LCTR" ("LCTR_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_LCTR_CONTS" ON "DEV_LMS"."TB_LMS_LCTR_CONTS" ("LCTR_CONTS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_LCTR_CONTS IS '강의콘텐츠';
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.LCTR_CONTS_ID IS '강의콘텐츠아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.LCTR_ID IS '강의아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTS_SEQNO IS '콘텐츠순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.UP_LCTR_CONTS_ID IS '상위강의콘텐츠아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTS_FILE_ID IS '콘텐츠파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTSNM IS '콘텐츠명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.LCTR_CONTS_TYCD IS '강의콘텐츠유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTS_URL IS '콘텐츠URL'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTS_PATH IS '콘텐츠경로'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTS_PSTN_CD IS '콘텐츠위치코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.CONTS_FILE_EXT IS '콘텐츠파일확장자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.VDO_MNTS IS '동영상시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.ATNDC_RFLTYN IS '출석반영여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.OYN IS '공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.EXRCS_QSTN_ID IS '연습문제아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_CONTS.MOD_DTTM IS '수정일시'