CREATE TABLE "DEV_LMS"."TB_LMS_BBS_ATCL_OPTN" 
   (	"ATCL_OPTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ATCL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"OPTN_CD" VARCHAR2(10) NOT NULL ENABLE, 
	"OPTNNM" VARCHAR2(200) NOT NULL ENABLE, 
	"OPTN_USEYN" CHAR(1) NOT NULL ENABLE, 
	"OPTN_SDTTM" VARCHAR2(14), 
	"OPTN_EDTTM" VARCHAR2(14), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_BBS_ATCL_OPTN" PRIMARY KEY ("ATCL_OPTN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_BBS_ATCL_TO_BBS_ATCL_OPTN" FOREIGN KEY ("ATCL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_BBS_ATCL" ("ATCL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_BBS_ATCL_OPTN" ON "DEV_LMS"."TB_LMS_BBS_ATCL_OPTN" ("ATCL_OPTN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_BBS_ATCL_OPTN IS '게시판게시글옵션';
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.ATCL_OPTN_ID IS '게시글옵션아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.ATCL_ID IS '게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.OPTN_CD IS '옵션코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.OPTNNM IS '옵션명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.OPTN_USEYN IS '옵션사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.OPTN_SDTTM IS '옵션시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.OPTN_EDTTM IS '옵션종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_OPTN.MOD_DTTM IS '수정일시'