CREATE TABLE "DEV_LMS"."TB_LMS_MENU_LYOT" 
   (	"MENU_LYOT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_LYOT_USEYN" CHAR(1) NOT NULL ENABLE, 
	"MENU_LYOT_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"MENU_IMG_FILE_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_TTL" VARCHAR2(200) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_MENU_LYOT" PRIMARY KEY ("MENU_LYOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MENU_TO_MENU_LYOT" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_MENU_LYOT" ON "DEV_LMS"."TB_LMS_MENU_LYOT" ("MENU_LYOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_MENU_LYOT IS '메뉴레이아웃';
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MENU_LYOT_ID IS '메뉴레이아웃아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MENU_LYOT_USEYN IS '메뉴레이아웃사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MENU_LYOT_TYCD IS '메뉴레이아웃유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MENU_IMG_FILE_ID IS '메뉴이미지파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MENU_TTL IS '메뉴제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_LYOT.MOD_DTTM IS '수정일시'