CREATE TABLE "DEV_LMS"."TB_LMS_BBS_ATCL_INQ_RCD" 
   (	"VWER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ATCL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"INQ_CNT" NUMBER(5,0) NOT NULL ENABLE, 
	"LST_INQ_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"FRST_INQ_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_BBS_ATCL_INQ_RCD" PRIMARY KEY ("VWER_ID", "ATCL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_BA_TO_BAIR" FOREIGN KEY ("ATCL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_BBS_ATCL" ("ATCL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_BBS_ATCL_INQ_RCD" ON "DEV_LMS"."TB_LMS_BBS_ATCL_INQ_RCD" ("VWER_ID", "ATCL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD IS '게시판게시글조회기록';
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.VWER_ID IS '조회자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.ATCL_ID IS '게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.INQ_CNT IS '조회수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.LST_INQ_DTTM IS '최종조회일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.FRST_INQ_DTTM IS '최초조회일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_INQ_RCD.MOD_DTTM IS '수정일시'