CREATE TABLE "DEV_LMS"."TB_LMS_CMMN_CD" 
   (	"CMMN_CD_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LANG_CD" VARCHAR2(10) NOT NULL ENABLE, 
	"UP_CD" VARCHAR2(50) NOT NULL ENABLE, 
	"CD" VARCHAR2(50) NOT NULL ENABLE, 
	"CD_SEQNO" NUMBER(7,0), 
	"CDNM" VARCHAR2(200) NOT NULL ENABLE, 
	"CD_VL" VARCHAR2(100), 
	"CD_ENNM" VARCHAR2(200), 
	"CD_EXPLN" VARCHAR2(300), 
	"GRPCD" VARCHAR2(30), 
	"USEYN" CHAR(1) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_CMMN_CD" PRIMARY KEY ("CMMN_CD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_TB_LMS_CMMN_CD_01" UNIQUE ("ORG_ID", "LANG_CD", "UP_CD", "CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ORG_TO_CMMN_CD" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."UK_TB_LMS_CMMN_CD_01" ON "DEV_LMS"."TB_LMS_CMMN_CD" ("ORG_ID", "LANG_CD", "UP_CD", "CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_CMMN_CD" ON "DEV_LMS"."TB_LMS_CMMN_CD" ("CMMN_CD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_CMMN_CD IS '공통코드';
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CMMN_CD_ID IS '공통코드아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.LANG_CD IS '언어코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.UP_CD IS '상위코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CD IS '코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CD_SEQNO IS '코드순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CDNM IS '코드명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CD_VL IS '코드값'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CD_ENNM IS '코드영문명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.CD_EXPLN IS '코드설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.GRPCD IS '그룹코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_CMMN_CD.MOD_DTTM IS '수정일시'