CREATE TABLE "DEV_LMS"."TB_LMS_USER_CONTS_REACT" 
   (	"USER_CONTS_REACT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CONTS_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"REACT_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"REACT_CNCLYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_CONTS_REACT" PRIMARY KEY ("USER_CONTS_REACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_CONTS_REACT" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_CONTS_REACT" ON "DEV_LMS"."TB_LMS_USER_CONTS_REACT" ("USER_CONTS_REACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_CONTS_REACT IS '사용자콘텐츠반응';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.USER_CONTS_REACT_ID IS '사용자콘텐츠반응아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.CONTS_ID IS '콘텐츠아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.CONTS_TYCD IS '콘텐츠유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.REACT_TYCD IS '반응유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.REACT_CNCLYN IS '반응취소여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_CONTS_REACT.MOD_DTTM IS '수정일시'