CREATE TABLE "DEV_LMS"."TB_LMS_USER_TELNO_CHG_HSTRY" 
   (	"USER_TELNO_CHG_HSTRY_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CHGBFR_MBL_TELNO" VARCHAR2(30) NOT NULL ENABLE, 
	"CHGAFT_MBL_TELNO" VARCHAR2(30) NOT NULL ENABLE, 
	"DGRS_YR" CHAR(4), 
	"DGRS_SMSTR_CHRT" CHAR(5), 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_RPRS_ID" VARCHAR2(30), 
	"STDNT_NO" VARCHAR2(30), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"CHG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_USER_TELNO_CHG_HSTRY" PRIMARY KEY ("USER_TELNO_CHG_HSTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_U_TO_UTELNO_CHG_HSTRY" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_TELNO_CHG_HSTRY" ON "DEV_LMS"."TB_LMS_USER_TELNO_CHG_HSTRY" ("USER_TELNO_CHG_HSTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY IS '사용자전화번호변경이력';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.USER_TELNO_CHG_HSTRY_ID IS '사용자전화번호변경이력아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.CHGBFR_MBL_TELNO IS '변경전모바일전화번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.CHGAFT_MBL_TELNO IS '변경후모바일전화번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.DGRS_YR IS '학위년도'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.DGRS_SMSTR_CHRT IS '학위학기기수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.USER_RPRS_ID IS '사용자대표아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.STDNT_NO IS '학번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.RGTR_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_TELNO_CHG_HSTRY.CHG_DTTM IS '변경일시'