CREATE TABLE "DEV_LMS"."TB_LMS_BBS_ATCL" 
   (	"ATCL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"BBS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"UP_ATCL_ID" VARCHAR2(30), 
	"DVCLAS_REG_ATCL_ID" VARCHAR2(30), 
	"ATCL_TTL" VARCHAR2(1000) NOT NULL ENABLE, 
	"ATCL_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"ATCL_HASH_TAG_CTS" VARCHAR2(200), 
	"ATCL_LV" NUMBER(5,0) NOT NULL ENABLE, 
	"ATCL_SEQNO" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"FVRT_CNT" NUMBER(10,0) NOT NULL ENABLE, 
	"INQ_CNT" NUMBER(10,0) NOT NULL ENABLE, 
	"REF_CMNT_ID" VARCHAR2(30), 
	"THMB_FILE_ID" VARCHAR2(30), 
	"PROC_STSCD" VARCHAR2(10) NOT NULL ENABLE, 
	"HDR_TYCD" VARCHAR2(10), 
	"ATHR_ID" VARCHAR2(30), 
	"DSCSN_PROF_ID" VARCHAR2(30), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"DELYN" CHAR(1) DEFAULT 'N', 
	"RGTRNM" VARCHAR2(200), 
	"OYN" CHAR(1), 
	"RSRVYN" CHAR(1), 
	"RSRV_SDTTM" VARCHAR2(14), 
	"RSRV_EDTTM" VARCHAR2(14), 
	"CMNT_PRMYN" CHAR(1), 
	"NTC_GBNCD" VARCHAR2(10), 
	"AUTO_ALIM_SDTTM" VARCHAR2(14), 
	"AUTO_ALIM_EDTTM" VARCHAR2(14), 
	"SRC_ATCL_ID" VARCHAR2(30), 
	"AUTO_ALIMYN" CHAR(1), 
	"ORG_ID" VARCHAR2(30), 
	"DEPT_ID" VARCHAR2(30), 
	"SBJCT_ID" VARCHAR2(30), 
	"DVCLAS_NO" VARCHAR2(10), 
	 CONSTRAINT "PK_TB_LMS_BBS_ATCL" PRIMARY KEY ("ATCL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_BBS_TO_BBS_ATCL" FOREIGN KEY ("BBS_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_BBS" ("BBS_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_BBS_ATCL" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "DEV_LMS"."IDX_BBS_ATCL_01" ON "DEV_LMS"."TB_LMS_BBS_ATCL" ("BBS_ID", "ATCL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "DEV_LMS"."IDX_BBS_ATCL_09" ON "DEV_LMS"."TB_LMS_BBS_ATCL" ("BBS_ID", "DELYN", "UP_ATCL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "DEV_LMS"."IDX_TB_LMS_BBS_ATCL01" ON "DEV_LMS"."TB_LMS_BBS_ATCL" ("REG_DTTM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_BBS_ATCL" ON "DEV_LMS"."TB_LMS_BBS_ATCL" ("ATCL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_BBS_ATCL IS '게시판게시글';
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATCL_ID IS '게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.BBS_ID IS '게시판아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.UP_ATCL_ID IS '상위게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.DVCLAS_REG_ATCL_ID IS '분반등록게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATCL_TTL IS '게시글제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATCL_CTS IS '게시글내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATCL_HASH_TAG_CTS IS '게시글해시태그내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATCL_LV IS '게시글레벨'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATCL_SEQNO IS '게시글순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.FVRT_CNT IS '좋아요수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.INQ_CNT IS '조회수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.REF_CMNT_ID IS '참조댓글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.THMB_FILE_ID IS '썸네일파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.PROC_STSCD IS '처리상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.HDR_TYCD IS '말머리유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ATHR_ID IS '원작자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.DSCSN_PROF_ID IS '상담교수아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.RGTRNM IS '등록자명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.OYN IS '공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.RSRVYN IS '등록예약여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.RSRV_SDTTM IS '등록예약시작일자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.RSRV_EDTTM IS '등록예약종료일자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.CMNT_PRMYN IS '댓글허용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.NTC_GBNCD IS '공지사항구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.AUTO_ALIM_SDTTM IS '자동알림시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.AUTO_ALIM_EDTTM IS '자동알림종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.SRC_ATCL_ID IS '원본게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.AUTO_ALIMYN IS '자동 알림 여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.DEPT_ID IS '부서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL.DVCLAS_NO IS '분반번호'