CREATE TABLE "DEV_LMS"."TB_LMS_USER_LGN_HSTRY" 
   (	"USER_LGN_HSTRY_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_SNS_ID" VARCHAR2(30), 
	"ACSR_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"LGN_IP" VARCHAR2(15) NOT NULL ENABLE, 
	"LGN_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"LGT_DTTM" VARCHAR2(14), 
	"LGN_SCSYN" CHAR(1) NOT NULL ENABLE, 
	"CNTN_DVC_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"LGN_CNTN_BRWSR" VARCHAR2(1000) NOT NULL ENABLE, 
	"SESS_ID" VARCHAR2(100), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_USER_LGN_HSTRY" PRIMARY KEY ("USER_LGN_HSTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_USER_LGN_HSTRY" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_USER_LGN_HSTRY" ON "DEV_LMS"."TB_LMS_USER_LGN_HSTRY" ("USER_LGN_HSTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_USER_LGN_HSTRY IS '사용자로그인이력';
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.USER_LGN_HSTRY_ID IS '사용자로그인이력아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.USER_SNS_ID IS '사용자SNS연결아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.ACSR_TYCD IS '접속자유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.LGN_IP IS '로그인아이피'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.LGN_DTTM IS '로그인일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.LGT_DTTM IS '로그아웃일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.LGN_SCSYN IS '로그인성공여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.CNTN_DVC_TYCD IS '접속기기유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.LGN_CNTN_BRWSR IS '로그인접속브라우저'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.SESS_ID IS '세션아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_USER_LGN_HSTRY.MOD_DTTM IS '수정일시'