CREATE TABLE "DEV_LMS"."TB_LMS_MENU_USE_SBJCT" 
   (	"MENU_USE_SBJCT" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"MENU_AUTH_TYCD" VARCHAR2(30), 
	"MENU_GBNCD" VARCHAR2(30), 
	 CONSTRAINT "PK_TB_LMS_MENU_USE_SBJCT" PRIMARY KEY ("MENU_USE_SBJCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MENU_TO_MENU_USE_SBJCT" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_MENU_USE_SBJCT" ON "DEV_LMS"."TB_LMS_MENU_USE_SBJCT" ("MENU_USE_SBJCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_MENU_USE_SBJCT IS '메뉴사용과목';
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.MENU_USE_SBJCT IS '메뉴사용과목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.MDFR_ID IS '수정자자이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.MENU_AUTH_TYCD IS '메뉴권한유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_SBJCT.MENU_GBNCD IS '메뉴구분코드'