CREATE TABLE "DEV_LMS"."TB_LMS_DSCS_FDBK" 
   (	"DSCS_FDBK_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"DSCS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"UP_DSCS_FDBK_ID" VARCHAR2(30), 
	"TEAM_ID" VARCHAR2(10), 
	"FDBK_CTS" CLOB, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_DSCS_FDBK" PRIMARY KEY ("DSCS_FDBK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_D_TO_DF" FOREIGN KEY ("DSCS_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_DSCS" ("DSCS_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_DSCS_FDBK" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FDBK_CTS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "DEV_LMS"."SYS_IL0000036806C00006$$" ON "DEV_LMS"."TB_LMS_DSCS_FDBK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_DSCS_FDBK" ON "DEV_LMS"."TB_LMS_DSCS_FDBK" ("DSCS_FDBK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_DSCS_FDBK IS '토론피드백';
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.DSCS_FDBK_ID IS '토론피드백아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.DSCS_ID IS '토론아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.UP_DSCS_FDBK_ID IS '상위토론피드백아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.TEAM_ID IS '팀아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.FDBK_CTS IS '피드백내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_FDBK.MOD_DTTM IS '수정일시'