CREATE TABLE "DEV_LMS"."TB_LMS_AUTHRT" 
   (	"AUTHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHRT_CD" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHRT_GRPCD" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHRTNM" VARCHAR2(100) NOT NULL ENABLE, 
	"AUTHRT_EXPLN" VARCHAR2(1000), 
	"AUTHRT_SEQ" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"LANG_CD" VARCHAR2(10) DEFAULT 'KO' NOT NULL ENABLE, 
	"ATFL_MAXSZ" NUMBER(22,0) DEFAULT 0 NOT NULL ENABLE, 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_AUTHRT" PRIMARY KEY ("AUTHRT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_TB_LMS_ORG_TO_TB_LMS_AUTHRT" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_AUTHRT" ON "DEV_LMS"."TB_LMS_AUTHRT" ("AUTHRT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_AUTHRT IS '권한';
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.AUTHRT_ID IS '권한아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.AUTHRT_CD IS '권한코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.AUTHRT_GRPCD IS '권한그룹코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.AUTHRTNM IS '권한명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.AUTHRT_EXPLN IS '권한설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.AUTHRT_SEQ IS '권한순서'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.LANG_CD IS '언어코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.ATFL_MAXSZ IS '첨부파일최대크기'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT.MOD_DTTM IS '수정일시'