CREATE TABLE "FURLMS"."TB_LMS_SMSTR_CHRT_SCHDL" 
   (	"SMSTR_CHRT_SCHDL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SMSTR_CHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SCHDL_WKNO" NUMBER(3,0) NOT NULL ENABLE, 
	"TOC_SEQNO" NUMBER(7,0) NOT NULL ENABLE, 
	"SMSTR_CHRT_SYMD" CHAR(8) NOT NULL ENABLE, 
	"SMSTR_CHRT_EYMD" CHAR(8) NOT NULL ENABLE, 
	"SMSTR_CHRT_ATNDC_RCG_SYMD" CHAR(8) NOT NULL ENABLE, 
	"SMSTR_CHRT_ATNDC_RCG_EYMD" CHAR(8) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"SCHDL_WKNONM" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_SMSTR_CHRT_SCHDL" PRIMARY KEY ("SMSTR_CHRT_SCHDL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SC_TO_SCS" FOREIGN KEY ("SMSTR_CHRT_ID")
	  REFERENCES "FURLMS"."TB_LMS_SMSTR_CHRT" ("SMSTR_CHRT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "FURLMS"."PK_TB_LMS_SMSTR_CHRT_SCHDL" ON "FURLMS"."TB_LMS_SMSTR_CHRT_SCHDL" ("SMSTR_CHRT_SCHDL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE FURLMS.TB_LMS_SMSTR_CHRT_SCHDL IS '학기기수일정';
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SMSTR_CHRT_SCHDL_ID IS '학기기수일정아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SMSTR_CHRT_ID IS '학기기수아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SCHDL_WKNO IS '일정주차'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.TOC_SEQNO IS '목차순번'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SMSTR_CHRT_SYMD IS '학기기수시작일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SMSTR_CHRT_EYMD IS '학기기수종료일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SMSTR_CHRT_ATNDC_RCG_SYMD IS '학기기수출석인정시작일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SMSTR_CHRT_ATNDC_RCG_EYMD IS '학기기수출석인정종료일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SMSTR_CHRT_SCHDL.SCHDL_WKNONM IS '일정주차명'