CREATE TABLE "DEV_LMS"."TB_LMS_SBJCT_ADM" 
   (	"SBJCT_ADM_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ADM_TYCD" VARCHAR2(10), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"SBJCT_ADM_SEQNO" NUMBER(3,0), 
	 CONSTRAINT "PK_TB_LMS_SBJCT_ADM" PRIMARY KEY ("SBJCT_ADM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_SBJCT_ADM" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_SBJCT_TO_SBJCT_ADM" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_SBJCT_ADM" ON "DEV_LMS"."TB_LMS_SBJCT_ADM" ("SBJCT_ADM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_SBJCT_ADM IS '과목관리자';
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.SBJCT_ADM_ID IS '과목관리자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.SBJCT_ADM_TYCD IS '과목관리자유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_SBJCT_ADM.SBJCT_ADM_SEQNO IS '과목관리자순번'