CREATE TABLE "DEV_LMS"."TB_LMS_LCTR_WKNO_SCHDL" 
   (	"LCTR_WKNO_SCHDL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_PLANDOC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_WKNO" NUMBER(5,0) NOT NULL ENABLE, 
	"LCTR_WKNO_CD" VARCHAR2(10), 
	"LCTR_WKNONM" VARCHAR2(200) NOT NULL ENABLE, 
	"LCTR_WKNO_EXPLN" VARCHAR2(4000) NOT NULL ENABLE, 
	"LCTR_WKNO_SEQNO" NUMBER(7,0) NOT NULL ENABLE, 
	"LCTR_GOAL" VARCHAR2(4000) NOT NULL ENABLE, 
	"LCTR_CTS" VARCHAR2(4000), 
	"LCTR_OTLN" VARCHAR2(4000), 
	"LCTR_REF_DATA" VARCHAR2(4000), 
	"LCTR_WKNO_SYMD" CHAR(8) NOT NULL ENABLE, 
	"LCTR_WKNO_EYMD" CHAR(8) NOT NULL ENABLE, 
	"ATNDC_RCG_SYMD" CHAR(8) NOT NULL ENABLE, 
	"ATNDC_RCG_EYMD" CHAR(8) NOT NULL ENABLE, 
	"LCTR_TOC_LRN_SCNDS" NUMBER(7,0), 
	"OYN" CHAR(1), 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"LCTR_TYCD" VARCHAR2(30), 
	"LCTR_TTL" VARCHAR2(2000), 
	 CONSTRAINT "PK_TB_LMS_LCTR_WKNO_SCHDL" PRIMARY KEY ("LCTR_WKNO_SCHDL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_LP_TO_LCTR_WKNO_SCHDL" FOREIGN KEY ("LCTR_PLANDOC_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_LCTR_PLANDOC" ("LCTR_PLANDOC_ID") ENABLE, 
	 CONSTRAINT "FK_SO_TO_LWS" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_LCTR_WKNO_SCHDL" ON "DEV_LMS"."TB_LMS_LCTR_WKNO_SCHDL" ("LCTR_WKNO_SCHDL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL IS '강의주차일정';
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO_SCHDL_ID IS '강의주차일정아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_PLANDOC_ID IS '강의계획서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO IS '강의주차'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO_CD IS '강의주차코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNONM IS '강의주차명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO_EXPLN IS '강의주차설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO_SEQNO IS '강의주차순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_GOAL IS '강의목표'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_CTS IS '강의내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_OTLN IS '강의개요'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_REF_DATA IS '강의참조자료'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO_SYMD IS '강의주차시작일자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_WKNO_EYMD IS '강의주차종료일자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.ATNDC_RCG_SYMD IS '출석인정시작일자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.ATNDC_RCG_EYMD IS '출석인정종료일자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_TOC_LRN_SCNDS IS '강의목차학습시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.OYN IS '공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_TYCD IS '강의유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_WKNO_SCHDL.LCTR_TTL IS '강의제목'