CREATE TABLE "DEV_LMS"."TB_LMS_EXAM_DTL" 
   (	"EXAM_DTL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_BSC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_MNTS" NUMBER(7,0) NOT NULL ENABLE, 
	"EXAMTM_LMTYN" CHAR(1) NOT NULL ENABLE, 
	"EXAM_PSBL_SDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"EXAM_PSBL_EDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"EXAM_QSTNS_CMPTNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"PASS_SCR" NUMBER(5,2), 
	"EXAM_TTL" VARCHAR2(200), 
	"EXAM_CTS" VARCHAR2(4000), 
	"CNSDR_ADD_MNTS" NUMBER(7,0) NOT NULL ENABLE, 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"REEXAMYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"REEXAM_PSBL_SDTTM" VARCHAR2(14), 
	"REEXAM_PSBL_EDTTM" VARCHAR2(14), 
	"REEXAM_MRK_RFLTRT" NUMBER(5,2), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_EXAM_DTL" PRIMARY KEY ("EXAM_DTL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EXAM_BSC_TO_EXAM_DTL" FOREIGN KEY ("EXAM_BSC_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_BSC" ("EXAM_BSC_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "DEV_LMS"."IDX_EXAM_DTL_09" ON "DEV_LMS"."TB_LMS_EXAM_DTL" ("EXAM_BSC_ID", "DELYN", "USEYN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAM_DTL" ON "DEV_LMS"."TB_LMS_EXAM_DTL" ("EXAM_DTL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAM_DTL IS '시험상세';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_DTL_ID IS '시험상세아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_BSC_ID IS '시험기본아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_MNTS IS '시험시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAMTM_LMTYN IS '시험시간제한여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_PSBL_SDTTM IS '시험가능시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_PSBL_EDTTM IS '시험가능종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_QSTNS_CMPTNYN IS '시험문제출제완료여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.PASS_SCR IS '통과점수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_TTL IS '시험제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.EXAM_CTS IS '시험내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.CNSDR_ADD_MNTS IS '배려추가시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.REEXAMYN IS '재시험여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.REEXAM_PSBL_SDTTM IS '재시험가능시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.REEXAM_PSBL_EDTTM IS '재시험가능종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.REEXAM_MRK_RFLTRT IS '재시험성적반영비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_DTL.MOD_DTTM IS '수정일시'