CREATE TABLE "DEV_LMS"."TB_LMS_MENU_USE_ORG" 
   (	"MENU_USE_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"MENU_AUTH_TYCD" VARCHAR2(30), 
	"MENU_GBNCD" VARCHAR2(30), 
	 CONSTRAINT "PK_TB_LMS_MENU_USE" PRIMARY KEY ("MENU_USE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MENU_TO_MENU_USE" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_MENU_USE" ON "DEV_LMS"."TB_LMS_MENU_USE_ORG" ("MENU_USE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."IDX1_TB_LMS_MENU_USE_ORG" ON "DEV_LMS"."TB_LMS_MENU_USE_ORG" ("MENU_ID", "ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_MENU_USE_ORG IS '메뉴사용';
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.MENU_USE_ID IS '메뉴사용아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.MENU_AUTH_TYCD IS '메뉴권한유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE_ORG.MENU_GBNCD IS '메뉴구분코드'