CREATE TABLE "FURLMS"."TB_LMS_SBJCT_SCHDL" 
   (	"SBJCT_SCHDL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SMSTR_CHRT_SCHDL_ID" VARCHAR2(30), 
	"SBJCT_SCHDL_WKNO" NUMBER(3,0) NOT NULL ENABLE, 
	"TOC_SEQNO" NUMBER(7,0) NOT NULL ENABLE, 
	"SBJCT_SYMD" CHAR(8) NOT NULL ENABLE, 
	"SBJCT_EYMD" CHAR(8) NOT NULL ENABLE, 
	"SBJCT_ATNDC_RCG_SYMD" CHAR(8) NOT NULL ENABLE, 
	"SBJCT_ATNDC_RCG_EYMD" CHAR(8) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"SBJCT_SCHDL_WKNONM" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_SBJCT_SCHDL" PRIMARY KEY ("SBJCT_SCHDL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SO_TO_SBJCT_SCHDL" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "FURLMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FURLMS" ;

CREATE UNIQUE INDEX "FURLMS"."PK_TB_LMS_SBJCT_SCHDL" ON "FURLMS"."TB_LMS_SBJCT_SCHDL" ("SBJCT_SCHDL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE FURLMS.TB_LMS_SBJCT_SCHDL IS '과목일정';
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_SCHDL_ID IS '과목일정아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SMSTR_CHRT_SCHDL_ID IS '학기기수일정아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_SCHDL_WKNO IS '과목일정주차'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.TOC_SEQNO IS '목차순번'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_SYMD IS '과목시작일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_EYMD IS '과목종료일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_ATNDC_RCG_SYMD IS '과목출석인정시작일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_ATNDC_RCG_EYMD IS '과목출석인정종료일자'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN FURLMS.TB_LMS_SBJCT_SCHDL.SBJCT_SCHDL_WKNONM IS '과목일정주차명'