CREATE TABLE "DEV_LMS"."TB_LMS_LCTR_PLANDOC" 
   (	"LCTR_PLANDOC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CRCLMN_OTLN" VARCHAR2(4000) NOT NULL ENABLE, 
	"LCTR_GOAL" VARCHAR2(4000) NOT NULL ENABLE, 
	"LCTR_OP_GDLN" VARCHAR2(4000) NOT NULL ENABLE, 
	"LCTR_OP_PLAN" VARCHAR2(4000) NOT NULL ENABLE, 
	"RLTD_SBJCT_CTS" VARCHAR2(4000), 
	"REMAKRS" VARCHAR2(4000), 
	"PLYR_SHRTCT_KEY_PVSNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SCRPT_PVSNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SBTTLS_PVSNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"PLYR_SPD_ADJST_PVSNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_LCTR_PLANDOC" PRIMARY KEY ("LCTR_PLANDOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SO_TO_LP" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_LCTR_PLANDOC" ON "DEV_LMS"."TB_LMS_LCTR_PLANDOC" ("LCTR_PLANDOC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_LCTR_PLANDOC IS '강의계획서';
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.LCTR_PLANDOC_ID IS '강의계획서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.CRCLMN_OTLN IS '교과목개요'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.LCTR_GOAL IS '강의목표'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.LCTR_OP_GDLN IS '운영방침'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.LCTR_OP_PLAN IS '운영계획'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.RLTD_SBJCT_CTS IS '관련과목내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.REMAKRS IS '참고사항'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.PLYR_SHRTCT_KEY_PVSNYN IS '플레이어단축키제공여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.SCRPT_PVSNYN IS '스크립트제공여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.SBTTLS_PVSNYN IS '자막제공여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.PLYR_SPD_ADJST_PVSNYN IS '재생속도조절제공여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_LCTR_PLANDOC.MOD_DTTM IS '수정일시'