CREATE TABLE "DEV_LMS"."TB_LMS_DEPT" 
   (	"DEPT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"UP_DEPT_ID" VARCHAR2(30), 
	"DEPTNM" VARCHAR2(200) NOT NULL ENABLE, 
	"DEPT_ENNM" VARCHAR2(200), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14), 
	"MDFR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_DEPT" PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_TB_LMS_ORG_TO_TB_LMS_DEPT" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_DEPT" ON "DEV_LMS"."TB_LMS_DEPT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_DEPT IS '학과부서';
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.DEPT_ID IS '학과부서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.UP_DEPT_ID IS '상위학과부서아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.DEPTNM IS '학과부서명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.DEPT_ENNM IS '학과부서영문명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DEPT.MOD_DTTM IS '수정일시'