package knou.lms.score.dao;

import java.util.List;

import org.egovframe.rte.psl.dataaccess.mapper.Mapper;
import org.egovframe.rte.psl.dataaccess.util.EgovMap;
import knou.lms.erp.vo.ErpScoreTestVO;
import knou.lms.score.vo.ScoreOverallScoreCalVO;
import knou.lms.score.vo.ScoreOverallVO;
import knou.lms.score.vo.StdScoreHistVO;

@Mapper("scoreOverallDAO")
public interface ScoreOverallDAO {
    public List<ScoreOverallVO> selectOverallList(ScoreOverallVO vo) throws Exception;
    public int selectOverallTotalCnt(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallExcelList(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectOverallStdInfo(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectOverallScoreDtl(ScoreOverallVO vo) throws Exception;
    
    public List<ScoreOverallVO> selectRankList(ScoreOverallScoreCalVO vo) throws Exception;
    public void updateRankList(ScoreOverallVO rankPVo) throws Exception;
    public ScoreOverallVO selectDenseRankMax(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectDenseRankMaxForRank(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectDenseRankMaxForRankPlus(ScoreOverallVO vo) throws Exception;
    public int selectRankRcnt(ScoreOverallVO vo) throws Exception;
    public String selectMrksRankTemp(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectMrksRankList(ScoreOverallScoreCalVO vo) throws Exception;
    public List<ScoreOverallVO> selectMrksNotRankList(ScoreOverallScoreCalVO vo) throws Exception;
    public int selectScoreMustF(ScoreOverallScoreCalVO vo) throws Exception;
    public ScoreOverallVO selectStdDetailScore(ScoreOverallVO vo) throws Exception;
   
    public void updateOverallScoreStatus(ScoreOverallVO vo) throws Exception;
    public void updateTbLmsStdScoreItem(List<ScoreOverallVO> scoreItemList) throws Exception;
    public void updateTbLmsStdScore(List<ScoreOverallVO> scoreList) throws Exception;
    public String selectCreCrsEval(ScoreOverallVO vo) throws Exception;
    public int selectStdTotCnt(ScoreOverallScoreCalVO vo) throws Exception;
    public ScoreOverallScoreCalVO selectScoreRelConf(ScoreOverallScoreCalVO vo) throws Exception;
    public void mergeScoreRel(ScoreOverallScoreCalVO vo) throws Exception;
    public ScoreOverallScoreCalVO selectScoreRel(ScoreOverallScoreCalVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallStdList(ScoreOverallVO listVo) throws Exception;
    public void updateStdScoreGrade(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallGraphList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallGraphListByGrade(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectOverallGridCase1(ScoreOverallVO vo) throws Exception;
    public String selectOverallGridCase2(ScoreOverallVO vo) throws Exception;
    public void updateOverallScoreOpenYn(ScoreOverallVO vo) throws Exception;
    public String selectOverallScoreOpenYn(ScoreOverallVO vo) throws Exception;
    
    public List<ScoreOverallVO> chartScoreList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> listScoreItemConfNoZero(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO avgScorebyItem(ScoreOverallVO scoreOverallVO) throws Exception;
    public int selectExamAbsentCnt(ScoreOverallVO pVo) throws Exception;
    public int selectScoreZeroCnt(ScoreOverallVO pVo) throws Exception;
    public int selectReExamStdCnt(ScoreOverallVO pVo) throws Exception;
    public String[] selectReExamStd(ScoreOverallVO pVo) throws Exception;
    public String[] selectExamAbsent(ScoreOverallVO pVo) throws Exception;
    public String[] selectScoreZero(ScoreOverallVO pVo) throws Exception;
    public int selectSysJobSchCnt(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectOverallBaseTchInfo(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectOverallBaseStdInfo(ScoreOverallVO vo) throws Exception;
    public void insertStdScoreObjt(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectScoreObjtList(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectScoreObjtCtnt(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectScoreObjtRegInfo(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectScoreObjtRegList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectScoreObjtProcList(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectStdScorePrvInfo(ScoreOverallVO vo) throws Exception;
    public String selectRelativePrvGrade(ScoreOverallVO vo) throws Exception;
    public String selectRelativeMaxGrade(ScoreOverallVO vo) throws Exception;
    public void updateScoreObjtProc(ScoreOverallVO updVo) throws Exception;
    public void updateScoreObjtCfm(ScoreOverallVO updVo) throws Exception;
    public ScoreOverallVO selectStdMemo(ScoreOverallVO vo) throws Exception;
    public void updateStdMemo(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectCurDateFmt() throws Exception;
    public int selectLessonTotCnt(ScoreOverallVO vo) throws Exception;
    public int selectLessonAbsentTotCnt(ScoreOverallVO vo) throws Exception;
    public int selectLessonLateTotCnt(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectTestsDtlList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectQuizDtlList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectTestDtlList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectAsmntDtlList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectForumDtlList(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectObjtProcCfmInfo(ScoreOverallVO vo) throws Exception;
    public int selectStdCnt(ScoreOverallVO vo) throws Exception;
    public void updateOverallExchData(List<ScoreOverallVO> exchPList) throws Exception;
    public ScoreOverallVO selectAbsoluteBaseInfo(ScoreOverallVO basePVo) throws Exception;
    public ScoreOverallVO selectAbsoluteCalc(String flExchScr) throws Exception;
    public void insertTbLmsStdScoreHist(StdScoreHistVO pVo) throws Exception;
    public void updateOverallScoreInit(String crsCreCd) throws Exception;
    public double selectFnScorGradeRcntCal(ScoreOverallVO test) throws Exception;
    public float selectFnScorCint(ScoreOverallVO pVo) throws Exception;
    public List<ScoreOverallVO> selectMrksList(ScoreOverallScoreCalVO vo) throws Exception;
    public String selectLmsLessonScore(ScoreOverallVO pVo) throws Exception;
    public String selectLmsTestsScore(ScoreOverallVO pVo) throws Exception;
    public String selectLmsAsmntScore(ScoreOverallVO pVo) throws Exception;
    public String selectLmsForumScore(ScoreOverallVO pVo) throws Exception;
    public String selectLmsReshScore(ScoreOverallVO pVo) throws Exception;
    public String selectLmsQuizScore(ScoreOverallVO pVo) throws Exception;
    public String selectLmsTestScore(ScoreOverallVO pVo) throws Exception;
    public void deleteOverallScoreInit(String crsCreCd) throws Exception;
    public void deleteOverallScoreItemInit(String crsCreCd) throws Exception;
    public void insertOverallScoreItem(List<ScoreOverallVO> scoreItemList) throws Exception;
    public void insertOverallScore(ScoreOverallVO pVo3) throws Exception;
    public ScoreOverallVO selectScoreOverallStd(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectOverallModStdInfo(ScoreOverallVO vo) throws Exception;
    public void updateStdScoreObjt(ScoreOverallVO vo) throws Exception;
    public String selectStdScore(ScoreOverallVO pVo) throws Exception;
    public List<ScoreOverallVO> selectScoreObjtListAdmin(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectStdScoreObjtList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallStdInfoAdmin(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectScoreItemConfList(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectStdScoreObjt(ScoreOverallVO vo) throws Exception;
    public ScoreOverallVO selectBtnStatus(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectScoreHistList(ScoreOverallVO vo) throws Exception;
    public int selectInvalidRatioCntQuiz(ScoreOverallVO vo) throws Exception;
    public int selectInvalidRatioCntForum(ScoreOverallVO vo) throws Exception;
    public int selectInvalidRatioCntAsmnt(ScoreOverallVO vo) throws Exception;
    public List<ErpScoreTestVO> selectErpTestScoreList(ScoreOverallVO vo) throws Exception;
    public EgovMap selectScoreExistsYnByUniCd(ScoreOverallVO vo) throws Exception;
    public String selectOriginScoreItem(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallMainList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallExamNoStareStdList(ScoreOverallVO vo) throws Exception;
    public List<ScoreOverallVO> selectOverallInitScoreList(ScoreOverallVO vo) throws Exception;
    public void updateScoreItemConfList(List<ScoreOverallVO> list) throws Exception;
}