GRANT SELECT ON VW_USER TO IO_ONTEST;
GRANT SELECT ON VW_SBJCT_ADM TO IO_ONTEST;

DB접속 정보
IP 61.43.90.131
PORT 1521
ID KNOU_ONTEST
PWD KNOU_ONTEST1234


마지막 과목별 팀 수강생 ( 팀별시험 응시자 )는 VW_SBJCT_TEAM 과 VW_SBJCT_ATNDLC 를 조인해서 사용하시면 될듯합니다.

CREATE OR REPLACE VIEW VW_USER AS
SELECT 	U.USER_ID 	USER_ID
		, A.AUTHRT_ID 	AUTHRT_ID
		, A.AUTHRTNM 	AUTHRTNM
		, UA.ORG_ID		ORG_ID
		, O.ORGNM		ORGNM
FROM 	TB_LMS_USER U
JOIN	TB_LMS_USER_AUTHRT UA 	ON 	U.USER_ID = UA.USER_ID
JOIN	TB_LMS_ORG O 			ON 	UA.ORG_ID = O.ORG_ID
JOIN	TB_LMS_AUTHRT	A 		ON	UA.AUTHRT_ID = A.AUTHRT_ID;



CREATE OR REPLACE VIEW VW_USER_SMSTR_CHRT AS
SELECT 		SMSTR.USER_ID
		, A.AUTHRT_ID
		, UA.ORG_ID
		, O.ORGNM
		, SC.SMSTR_CHRT_ID	
		, SC.DGRS_YR
		, SC.DGRS_SMSTR_CHRT
		, SC.SMSTR_CHRTNM
		, SC.SMSTR_CHRT_OP_SDTTM
		, SC.SMSTR_CHRT_OP_EDTTM
		, SC.PROF_ACCSS_PBL_SDTTM	PROF_ACCSS_PBL_SDTTM
FROM
( 
	SELECT	 DISTINCT SC.ORG_ID
			, U.USER_ID
			, SC.SMSTR_CHRT_ID	
			, SC.DGRS_YR
			, SC.DGRS_SMSTR_CHRT
	FROM 	TB_LMS_USER U
	INNER 	JOIN (	SELECT USER_ID, SBJCT_ID
	        		FROM TB_LMS_ATNDLC
	        		UNION ALL
			        SELECT USER_ID, SBJCT_ID
			        FROM TB_LMS_SBJCT_ADM
				) X ON X.USER_ID = U.USER_ID
	INNER JOIN TB_LMS_SBJCT S 			ON X.SBJCT_ID = S.SBJCT_ID AND S.USEYN = 'Y' AND S.DELYN = 'N'
	INNER JOIN TB_LMS_SMSTR_CHRT SC		ON SC.SMSTR_CHRT_ID = S.SMSTR_CHRT_ID
) SMSTR 
INNER JOIN TB_LMS_ORG O  			ON SMSTR.ORG_ID = O.ORG_ID
INNER JOIN TB_LMS_USER_AUTHRT UA	ON SMSTR.USER_ID = UA.USER_ID AND SMSTR.ORG_ID = UA.ORG_ID
INNER JOIN TB_LMS_AUTHRT A			ON UA.AUTHRT_ID = A.AUTHRT_ID
INNER JOIN TB_LMS_SMSTR_CHRT SC		ON SMSTR.SMSTR_CHRT_ID = SC.SMSTR_CHRT_ID;


CREATE OR REPLACE VIEW VW_USER_SMSTR_CHRT_SBJCT AS
SELECT	U.USER_ID
		, A.AUTHRT_ID
		, UA.ORG_ID
		, SC.SMSTR_CHRT_ID
		, S.CRCLMN_NO
		, S.SBJCT_ID
		, S.SBJCTNM
		, S.SBJCT_YR
		, S.SBJCT_SMSTR
		, S.DVCLAS_GRPCD
		, S.DVCLAS_NO
		, S.ATNDLC_SDTTM
		, S.ATNDLC_EDTTM
FROM 	TB_LMS_USER U
INNER 	JOIN (	SELECT USER_ID, SBJCT_ID
        		FROM TB_LMS_ATNDLC
        		UNION ALL
		        SELECT USER_ID, SBJCT_ID
		        FROM TB_LMS_SBJCT_ADM
			) X ON X.USER_ID = U.USER_ID
INNER JOIN TB_LMS_SBJCT S 	ON X.SBJCT_ID = S.SBJCT_ID AND S.USEYN = 'Y' AND S.DELYN = 'N'
INNER JOIN TB_LMS_USER_AUTHRT UA	ON U.USER_ID = UA.USER_ID 
INNER JOIN TB_LMS_ORG O  			ON UA.ORG_ID = O.ORG_ID
INNER JOIN TB_LMS_AUTHRT A			ON UA.AUTHRT_ID = A.AUTHRT_ID
INNER JOIN TB_LMS_SMSTR_CHRT SC		ON O.ORG_ID = SC.ORG_ID AND SC.SMSTR_CHRT_ID = S.SMSTR_CHRT_ID;


CREATE OR REPLACE VIEW VW_SBJCT_ADM AS
SELECT	S.SBJCT_ID
		, S.CRCLMN_NO
		, SA.SBJCT_ADM_TYCD
		, C.CDNM
		, U.USER_ID
		, U.USERNM
FROM	TB_LMS_SBJCT	S
INNER	JOIN	TB_LMS_SBJCT_ADM	SA	ON	S.SBJCT_ID = SA.SBJCT_ID
INNER	JOIN	TB_LMS_USER			U 	ON	SA.USER_ID = U.USER_ID
JOIN	TB_LMS_CMMN_CD				C	ON  C.LANG_CD = 'ko' 
										AND C.UP_CD = 'SBJCT_ADM_TYCD' AND C.CD = SA.SBJCT_ADM_TYCD;							
											
CREATE OR REPLACE VIEW VW_SBJCT_ATNDLC AS
SELECT	 ATND.SBJCT_ID
		, S.CRCLMN_NO
		, U.USER_ID
		, U.USERNM
		, U.DSBLYN
		, EB.EXAM_BSC_ID
		-- 1. 시험 디테일 분수(분) 직접 조회
		, (SELECT MIN(ED.CNSDR_ADD_MNTS) 
		   FROM TB_LMS_EXAM_DTL ED 
		   WHERE ED.EXAM_DTL_ID = EB.EXAM_BSC_ID) AS CNSDR_ADD_MNTS
		-- 2. 시험 디테일 비율 계산 (서브쿼리 중복을 피하기 위해 안에서 연산 처리)
		, (SELECT CASE WHEN MIN(ED.EXAM_MNTS) IS NULL OR MIN(ED.EXAM_MNTS) = 0 THEN 100
					   ELSE (MIN(ED.CNSDR_ADD_MNTS) / MIN(ED.EXAM_MNTS)) END
		   FROM TB_LMS_EXAM_DTL ED 
		   WHERE ED.EXAM_DTL_ID = EB.EXAM_BSC_ID) AS CNSDR_ADD_MNTS_RATE
		-- 3. 결시원 제출 여부 조회 (존재 여부만 파악하므로EXISTS나 MIN/MAX 활용)
		, CASE WHEN EXISTS (
					SELECT 1 
					FROM TB_LMS_EXAM_ABSNCE EA 
					WHERE EA.EXAM_BSC_ID = EB.EXAM_BSC_ID 
					  AND EA.USER_ID = ATND.USER_ID 
					  AND EA.ABSNCE_APLY_STSCD = 'APRV'
			   ) THEN '결시원제출'
			   ELSE '결시원미제출' 
		  END AS EXAM_ABSNCE_SBMSN_TYNM
FROM	TB_LMS_ATNDLC	ATND
INNER JOIN TB_LMS_SBJCT S	ON ATND.SBJCT_ID = S.SBJCT_ID
INNER JOIN TB_LMS_USER	U	ON ATND.USER_ID = U.USER_ID
INNER JOIN TB_LMS_EXAM_BSC EB ON ATND.SBJCT_ID = EB.SBJCT_ID 
                             AND EB.DELYN = 'N' 
                             AND EB.EXAM_TYCD = 'EXAM';

[ 추가 ]
    운영과목별 수강생 목록 ( 가칭 : VW_SBJECT_STD )
     - 과목ID
     - 학생ID
     - 학생이름

CREATE OR REPLACE VIEW VW_SBJCT_STD AS
SELECT	S.SBJCT_ID
		, S.CRCLMN_NO
		, ATNDLC.USER_ID
		, U.USERNM
FROM	TB_LMS_SBJCT	S
INNER	JOIN	TB_LMS_ATNDLC	ATNDLC	ON	S.SBJCT_ID = ATNDLC.SBJCT_ID
INNER	JOIN	TB_LMS_USER	U			ON	U.USER_ID  = ATNDLC.USER_ID
WHERE	S.USEYN = 'Y' AND S.DELYN = 'N'


[ 수정 ] 
    운영과목별 팀 목록 ( VW_SBJCT_TEAM )
     - [삭제] 학생ID 
     - [삭제] 학생이름 
     * 수강생정보 제외 요청
     
CREATE OR REPLACE VIEW VW_SBJCT_TEAM AS
SELECT	S.CRCLMN_NO
		, TG.SBJCT_ID
		, TG.TEAM_GRP_ID
		, TG.TEAM_GRPNM
		, T.TEAM_ID
		, T.TEAMNM
FROM	TB_LMS_TEAM_GRP			TG
INNER	JOIN	TB_LMS_TEAM		T		ON	TG.TEAM_GRP_ID = T.TEAM_GRP_ID
INNER	JOIN 	TB_LMS_SBJCT	S		ON  TG.SBJCT_ID = S.SBJCT_ID;