DELETE FROM TB_LMS_CMMN_CD WHERE ORG_ID IN ('ORG0000001', 'ORG0000002', 'ORG0000003', 'ORG0000004', 'ORG0000005', 'ORG0000006', 'ORG0000007');

INSERT INTO FURLMS.TB_LMS_CMMN_CD
(CMMN_CD_ID, ORG_ID, LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, RGTR_ID, REG_DTTM)
SELECT 'CMMN_CD' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 23) AS CMMN_CD_ID, 
    'ORG0000001', LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, 'admin' AS RGTR_ID,
    TO_CHAR( SYSDATE, 'YYYYMMDDHH24MISS')  AS REG_DTTM
FROM FURLMS.TB_LMS_CMMN_CD
WHERE ORG_ID = 'LMSBASIC';

INSERT INTO FURLMS.TB_LMS_CMMN_CD
(CMMN_CD_ID, ORG_ID, LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, RGTR_ID, REG_DTTM)
SELECT 'CMMN_CD' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 23) AS CMMN_CD_ID, 
    'ORG0000002', LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, 'admin' AS RGTR_ID,
    TO_CHAR( SYSDATE, 'YYYYMMDDHH24MISS')   AS REG_DTTM
FROM FURLMS.TB_LMS_CMMN_CD
WHERE ORG_ID = 'LMSBASIC';

INSERT INTO FURLMS.TB_LMS_CMMN_CD
(CMMN_CD_ID, ORG_ID, LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, RGTR_ID, REG_DTTM)
SELECT 'CMMN_CD' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 23) AS CMMN_CD_ID, 
    'ORG0000003', LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, 'admin' AS RGTR_ID,
    TO_CHAR( SYSDATE, 'YYYYMMDDHH24MISS')   AS REG_DTTM
FROM FURLMS.TB_LMS_CMMN_CD
WHERE ORG_ID = 'LMSBASIC';

INSERT INTO FURLMS.TB_LMS_CMMN_CD
(CMMN_CD_ID, ORG_ID, LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, RGTR_ID, REG_DTTM)
SELECT 'CMMN_CD' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 23) AS CMMN_CD_ID, 
    'ORG0000004', LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, 'admin' AS RGTR_ID,
    TO_CHAR( SYSDATE, 'YYYYMMDDHH24MISS')   AS REG_DTTM
FROM FURLMS.TB_LMS_CMMN_CD
WHERE ORG_ID = 'LMSBASIC';

INSERT INTO FURLMS.TB_LMS_CMMN_CD
(CMMN_CD_ID, ORG_ID, LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, RGTR_ID, REG_DTTM)
SELECT 'CMMN_CD' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 23) AS CMMN_CD_ID, 
    'ORG0000005', LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, 'admin' AS RGTR_ID,
    TO_CHAR( SYSDATE, 'YYYYMMDDHH24MISS')   AS REG_DTTM
FROM FURLMS.TB_LMS_CMMN_CD
WHERE ORG_ID = 'LMSBASIC';

INSERT INTO FURLMS.TB_LMS_CMMN_CD
(CMMN_CD_ID, ORG_ID, LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, RGTR_ID, REG_DTTM)
SELECT 'CMMN_CD' || SUBSTR(RAWTOHEX(SYS_GUID()), 1, 23) AS CMMN_CD_ID, 
    'ORG0000006', LANG_CD, UP_CD, CD, CD_SEQNO, CDNM, CD_VL, CD_ENNM, CD_EXPLN, GRPCD, USEYN, 'admin' AS RGTR_ID,
    TO_CHAR( SYSDATE, 'YYYYMMDDHH24MISS')   AS REG_DTTM
FROM FURLMS.TB_LMS_CMMN_CD
WHERE ORG_ID = 'LMSBASIC';