CREATE TABLE "DEV_LMS"."TB_LMS_QSTN" 
   (	"QSTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_DTL_ID" VARCHAR2(30), 
	"QSTN_TTL" VARCHAR2(200) NOT NULL ENABLE, 
	"QSTN_CTS" CLOB NOT NULL ENABLE, 
	"QSTN_SEQNO" NUMBER(3,0) NOT NULL ENABLE, 
	"QSTN_CNDDT_SEQNO" NUMBER(3,0) NOT NULL ENABLE, 
	"QSTN_GBNCD" VARCHAR2(10), 
	"QSTN_RSPNS_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"QSTN_SCR" NUMBER(5,2) DEFAULT 0 NOT NULL ENABLE, 
	"QSTN_DFCTLV_TYCD" VARCHAR2(10) DEFAULT 'NONE' NOT NULL ENABLE, 
	"EDTR_USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CRANS_TYCD" VARCHAR2(30), 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_QSTN" PRIMARY KEY ("QSTN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EXAM_DTL_TO_QSTN" FOREIGN KEY ("EXAM_DTL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_DTL" ("EXAM_DTL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("QSTN_CTS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "DEV_LMS"."SYS_IL0000036678C00004$$" ON "DEV_LMS"."TB_LMS_QSTN" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_QSTN" ON "DEV_LMS"."TB_LMS_QSTN" ("QSTN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_QSTN IS '문항';
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_ID IS '문항아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.EXAM_DTL_ID IS '시험상세아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_TTL IS '문항제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_CTS IS '문항내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_SEQNO IS '문항순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_CNDDT_SEQNO IS '문항후보순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_GBNCD IS '문항구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_RSPNS_TYCD IS '문항답변유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_SCR IS '문항점수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.QSTN_DFCTLV_TYCD IS '문항난이도유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.EDTR_USEYN IS '편집기사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.CRANS_TYCD IS '정답유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN.MOD_DTTM IS '수정일시'