CREATE TABLE "DEV_LMS"."TB_LMS_BBS_ATCL_CMNT" 
   (	"ATCL_CMNT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ATCL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"UP_ATCL_CMNT_ID" VARCHAR2(30), 
	"ATCL_CMNT_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"EMTICN_NO" VARCHAR2(30), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"RGTRNM" VARCHAR2(200), 
	"DELYN" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "PK_TB_LMS_BBS_ATCL_CMNT" PRIMARY KEY ("ATCL_CMNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_BBS_ATCL_TO_BBS_ATCL_CMNT" FOREIGN KEY ("ATCL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_BBS_ATCL" ("ATCL_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_BBS_ATCL_CMNT" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_BBS_ATCL_CMNT" ON "DEV_LMS"."TB_LMS_BBS_ATCL_CMNT" ("ATCL_CMNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_BBS_ATCL_CMNT IS '게시판게시글댓글';
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.ATCL_CMNT_ID IS '게시글댓글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.ATCL_ID IS '게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.UP_ATCL_CMNT_ID IS '상위게시글댓글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.ATCL_CMNT_CTS IS '게시글댓글내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.EMTICN_NO IS '이모티콘번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.RGTRNM IS '등록자명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS_ATCL_CMNT.DELYN IS '삭제여부'