CREATE TABLE "DEV_LMS"."TB_LMS_EXAM_TRGTR" 
   (	"EXAM_TRGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_DTL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TEAM_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_EXAM_TRGTR" PRIMARY KEY ("EXAM_TRGTR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EXAM_DTL_TO_EXAM_TRGTR" FOREIGN KEY ("EXAM_DTL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_DTL" ("EXAM_DTL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAM_TRGTR" ON "DEV_LMS"."TB_LMS_EXAM_TRGTR" ("EXAM_TRGTR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAM_TRGTR IS '시험대상자';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.EXAM_TRGTR_ID IS '시험대상자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.EXAM_DTL_ID IS '시험상세아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.TEAM_ID IS '팀아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_TRGTR.MOD_DTTM IS '수정일시'