CREATE TABLE "DEV_LMS"."TB_LMS_EXAM_SPRT_APLY" 
   (	"EXAM_SPRT_APLY_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_BSC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"APLY_STSCD" VARCHAR2(10) NOT NULL ENABLE, 
	"AUTZR_ID" VARCHAR2(30), 
	"APRVDTTM" VARCHAR2(14), 
	"ADD_MNTS" NUMBER(7,0) NOT NULL ENABLE, 
	"EXTDTM_CHGYN" CHAR(1), 
	"CNCL_APLY_STSCD" VARCHAR2(10), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_EXAM_SPRT_APLY" PRIMARY KEY ("EXAM_SPRT_APLY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EB_TO_ESA" FOREIGN KEY ("EXAM_BSC_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_BSC" ("EXAM_BSC_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_EXAM_SPRT_APLY" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAM_SPRT_APLY" ON "DEV_LMS"."TB_LMS_EXAM_SPRT_APLY" ("EXAM_SPRT_APLY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAM_SPRT_APLY IS '시험지원신청';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.EXAM_SPRT_APLY_ID IS '시험지원신청아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.EXAM_BSC_ID IS '시험기본아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.APLY_STSCD IS '신청상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.AUTZR_ID IS '승인자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.APRVDTTM IS '승인일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.ADD_MNTS IS '추가시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.EXTDTM_CHGYN IS '연장시간변경여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.CNCL_APLY_STSCD IS '취소신청상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_SPRT_APLY.MOD_DTTM IS '수정일시'