CREATE TABLE "DEV_LMS"."TB_LMS_MENU_USE" 
   (	"MENU_USE_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_REF_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_REF_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"MENT_USE_STNG_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_MENU_USE" PRIMARY KEY ("MENU_USE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MENU_TO_MENU_USE" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_MENU_USE" ON "DEV_LMS"."TB_LMS_MENU_USE" ("MENU_USE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_MENU_USE IS '메뉴사용';
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MENU_USE_ID IS '메뉴사용아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MENU_REF_ID IS '메뉴참조아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MENU_REF_TYCD IS '메뉴참조유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MENT_USE_STNG_CTS IS '메뉴사용설정내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU_USE.MOD_DTTM IS '수정일시'