CREATE TABLE "DEV_LMS"."TB_LMS_ATFL_BOX" 
   (	"ATFL_BOX_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"UP_ATFL_BOX_ID" VARCHAR2(30), 
	"ATFL_BOXNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ATFL_BOX_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"ATFL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_ATFL_BOX" PRIMARY KEY ("ATFL_BOX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_ATFL_BOX" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ATFL_BOX" ON "DEV_LMS"."TB_LMS_ATFL_BOX" ("ATFL_BOX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ATFL_BOX IS '첨부파일함';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.ATFL_BOX_ID IS '첨부파일함아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.UP_ATFL_BOX_ID IS '상위첨부파일함아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.ATFL_BOXNM IS '첨부파일함명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.ATFL_BOX_TYCD IS '첨부파일함유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.ATFL_ID IS '첨부파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL_BOX.MOD_DTTM IS '수정일시'