CREATE TABLE "DEV_LMS"."TB_LMS_TKEXAM_ANSW_SHT" 
   (	"TKEXAM_ANSW_SHT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAMPPR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"QSTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ANSW_SHT_CTS" VARCHAR2(4000), 
	"SCR" NUMBER(5,2) NOT NULL ENABLE, 
	"FDBK_CTS" VARCHAR2(4000), 
	"FDBK_DTTM" VARCHAR2(14), 
	"FDBKR_ID" VARCHAR2(30), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_TKEXAM_ANSW_SHT" PRIMARY KEY ("TKEXAM_ANSW_SHT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_E_TO_TAS" FOREIGN KEY ("EXAMPPR_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAMPPR" ("EXAMPPR_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_TKEXAM_ANSW_SHT" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_TKEXAM_ANSW_SHT" ON "DEV_LMS"."TB_LMS_TKEXAM_ANSW_SHT" ("TKEXAM_ANSW_SHT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT IS '시험응시답안';
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.TKEXAM_ANSW_SHT_ID IS '시험응시답안아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.EXAMPPR_ID IS '시험지아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.QSTN_ID IS '문항아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.ANSW_SHT_CTS IS '답안내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.SCR IS '점수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.FDBK_CTS IS '피드백내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.FDBK_DTTM IS '피드백일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.FDBKR_ID IS '피드백자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM_ANSW_SHT.MOD_DTTM IS '수정일시'