CREATE TABLE "DEV_LMS"."TB_LMS_EXAMPPR" 
   (	"EXAMPPR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TKEXAM_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"QSTN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"QSTN_DSPLY_SEQNO" NUMBER(3,0) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"QSTN_VWITM_DSPLY_SEQ" VARCHAR2(30), 
	 CONSTRAINT "PK_TB_LMS_EXAMPPR" PRIMARY KEY ("EXAMPPR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_QSTN_TO_EXAMPPR" FOREIGN KEY ("QSTN_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_QSTN" ("QSTN_ID") ENABLE, 
	 CONSTRAINT "FK_TKEXAM_TO_EXAMPPR" FOREIGN KEY ("TKEXAM_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_TKEXAM" ("TKEXAM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAMPPR" ON "DEV_LMS"."TB_LMS_EXAMPPR" ("EXAMPPR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAMPPR IS '시험지';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.EXAMPPR_ID IS '시험지아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.TKEXAM_ID IS '시험응시아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.QSTN_ID IS '문항아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.QSTN_DSPLY_SEQNO IS '문항화면표시순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAMPPR.QSTN_VWITM_DSPLY_SEQ IS '문항보기항목화면표시순서'