CREATE TABLE "DEV_LMS"."TB_LMS_ORG" 
   (	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_REG_NO" VARCHAR2(30), 
	"ORGNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ORG_SHRTNM" VARCHAR2(200), 
	"ORG_NCNM" VARCHAR2(200) NOT NULL ENABLE, 
	"ORG_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"ZIP_CD" VARCHAR2(10), 
	"ADDR1" VARCHAR2(300) NOT NULL ENABLE, 
	"ADDR2" VARCHAR2(300) NOT NULL ENABLE, 
	"DMNNM" VARCHAR2(300), 
	"SDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"EDTTM" VARCHAR2(14) DEFAULT '99991231235959' NOT NULL ENABLE, 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"BSC_LANG_CD" VARCHAR2(10) DEFAULT 'ko' NOT NULL ENABLE, 
	"OFC_TELNO" VARCHAR2(11), 
	"RPRS_TELNO" VARCHAR2(11), 
	"CHRGRNM" VARCHAR2(200) NOT NULL ENABLE, 
	"CHRGR_CNTCT" VARCHAR2(11) NOT NULL ENABLE, 
	"CHRGR_EML" VARCHAR2(300) NOT NULL ENABLE, 
	"MLT_LGNYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"PSWD_CHG_USEYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"PSWD_USE_DAY_CNT" NUMBER(10,0), 
	"MBRID_TYCD" VARCHAR2(10), 
	"JOIN_USEYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SITE_USG_CD" VARCHAR2(10), 
	"CPRGHT_CTS" VARCHAR2(300), 
	"HMPG_URL" VARCHAR2(300), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_ORG" PRIMARY KEY ("ORG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ORG" ON "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ORG IS '기관';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ORG_REG_NO IS '기관등록번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ORGNM IS '기관명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ORG_SHRTNM IS '기관약어명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ORG_NCNM IS '기관별칭'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ORG_TYCD IS '기관유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ZIP_CD IS '우편번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ADDR1 IS '주소1'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.ADDR2 IS '주소2'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.DMNNM IS '도메인명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.SDTTM IS '시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.EDTTM IS '종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.BSC_LANG_CD IS '기본언어코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.OFC_TELNO IS '사무실전화번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.RPRS_TELNO IS '대표전화번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.CHRGRNM IS '담당자명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.CHRGR_CNTCT IS '담당자연락처'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.CHRGR_EML IS '담당자이메일'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.MLT_LGNYN IS '다중로그인여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.PSWD_CHG_USEYN IS '비밀번호변경사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.PSWD_USE_DAY_CNT IS '비밀번호사용일수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.MBRID_TYCD IS '회원아이디유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.JOIN_USEYN IS '회원가입사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.SITE_USG_CD IS '사이트용도코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.CPRGHT_CTS IS '저작권내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.HMPG_URL IS '홈페이지URL'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG.MOD_DTTM IS '수정일시'