CREATE TABLE "DEV_LMS"."TB_LMS_MENU" 
   (	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"UP_MENU_ID" VARCHAR2(30), 
	"MENUNM" VARCHAR2(200) NOT NULL ENABLE, 
	"MENU_ENNM" VARCHAR2(200), 
	"MENU_EXPLN" VARCHAR2(1000) NOT NULL ENABLE, 
	"MENU_URL" VARCHAR2(1000), 
	"MENU_PATH" VARCHAR2(1000), 
	"MENU_LV" NUMBER(3,0), 
	"MENU_SEQ" NUMBER(3,0), 
	"MENU_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"MENU_TTL" VARCHAR2(200) NOT NULL ENABLE, 
	"MENU_INQYN" CHAR(1), 
	"MENU_USEYN" CHAR(1), 
	"BSCYN" CHAR(1), 
	"BRDRLN_USEYN" CHAR(1), 
	"SSL_USEYN" CHAR(1), 
	"RGTR_ID" VARCHAR2(30), 
	"REG_DTTM" VARCHAR2(14), 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"MENU_IMG_FILE_ID" VARCHAR2(30), 
	 CONSTRAINT "PK_TB_LMS_MENU" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_MENU" ON "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_MENU IS '메뉴';
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.UP_MENU_ID IS '상위메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENUNM IS '메뉴명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_ENNM IS '메뉴영문명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_EXPLN IS '메뉴설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_URL IS '메뉴URL'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_PATH IS '메뉴경로'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_LV IS '메뉴레벨'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_SEQ IS '메뉴순서'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_TYCD IS '메뉴유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_TTL IS '메뉴제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_INQYN IS '메뉴조회여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_USEYN IS '메뉴사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.BSCYN IS '기본여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.BRDRLN_USEYN IS '경계선사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.SSL_USEYN IS 'SSL사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_MENU.MENU_IMG_FILE_ID IS '이미지 파일 아이디'