CREATE TABLE "DEV_LMS"."TB_LMS_ATNDLC" 
   (	"ATNDLC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"RPTYN" CHAR(1) NOT NULL ENABLE, 
	"ATNDLC_APLY_DTTM" VARCHAR2(14), 
	"ATNDLC_CNCL_DTTM" VARCHAR2(14), 
	"ATNDLC_CERT_DTTM" VARCHAR2(14), 
	"ATNDLC_FNSH_DTTM" VARCHAR2(14), 
	"FNSH_NO" VARCHAR2(30), 
	"ACQS_CRDTS" NUMBER(3,0), 
	"SCYR" NUMBER(3,0), 
	"CMCRS_GBNCD" VARCHAR2(30), 
	"DGRS_CRS_GBNCD" VARCHAR2(10), 
	"AUDITYN" CHAR(1), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"ATNDLC_STSCD" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_ATNDLC" PRIMARY KEY ("ATNDLC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_ATNDLC" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_SBJCT_TO_ATNDLC" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "DEV_LMS"."IDX_ATNDLC_01" ON "DEV_LMS"."TB_LMS_ATNDLC" ("SBJCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ATNDLC" ON "DEV_LMS"."TB_LMS_ATNDLC" ("ATNDLC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ATNDLC IS '수강';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ATNDLC_ID IS '수강아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.RPTYN IS '재수강여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ATNDLC_APLY_DTTM IS '수강신청일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ATNDLC_CNCL_DTTM IS '수강취소일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ATNDLC_CERT_DTTM IS '수강인증일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ATNDLC_FNSH_DTTM IS '수강수료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.FNSH_NO IS '수료번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ACQS_CRDTS IS '취득학점'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.SCYR IS '학년'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.CMCRS_GBNCD IS '이수구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.DGRS_CRS_GBNCD IS '학위과정구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.AUDITYN IS '청강여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATNDLC.ATNDLC_STSCD IS '수강상태코드'