CREATE TABLE "DEV_LMS"."TB_LMS_DSCS" 
   (	"DSCS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LCTR_WKNO_SCHDL_ID" VARCHAR2(30), 
	"DSCS_GRP_ID" VARCHAR2(30), 
	"DSCS_TYCD" VARCHAR2(10), 
	"DSCS_GBNCD" VARCHAR2(10), 
	"DSCS_UNIT_TYCD" VARCHAR2(10), 
	"EVL_SCR_TYCD" VARCHAR2(30), 
	"DSCS_TTL" VARCHAR2(4000) NOT NULL ENABLE, 
	"DSCS_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"DSCS_SDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"DSCS_EDTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"EVL_SDTTM" VARCHAR2(14), 
	"EVL_EDTTM" VARCHAR2(14), 
	"EXTD_SDTTM" VARCHAR2(14), 
	"EXTD_EDTTM" VARCHAR2(14), 
	"EXTD_EVL_SDTTM" VARCHAR2(14), 
	"EXTD_EVL_EDTTM" VARCHAR2(14), 
	"DVCLS_NO" VARCHAR2(30), 
	"LRN_GRP_ID" VARCHAR2(30), 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"OATCL_INQYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"OKNOKRT_OYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"OKNOK_MODYN" CHAR(1) DEFAULT 'N', 
	"MLT_OPNN_REGYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"EXTD_USEYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CMNT_RSPNS_REQYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MRK_RFLTYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MRK_OYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MRK_OPEN_SDTTM" VARCHAR2(14), 
	"MRK_OPEN_EDTTM" VARCHAR2(14), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"SBJCT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"OKNOK_RGTR_OYN" CHAR(1) DEFAULT 'N', 
	"OKNOK_STNGYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MRK_RFLTRT" NUMBER(5,2) NOT NULL ENABLE, 
	"BYTEAM_DSCS_USEYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"TEAM_ID" VARCHAR2(30), 
	"UP_DSCS_ID" VARCHAR2(30), 
	"TEAM_DSCS_OYN" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "PK_TB_LMS_DSCS" PRIMARY KEY ("DSCS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_DSCS_GRP_TO_DSCS" FOREIGN KEY ("DSCS_GRP_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_DSCS_GRP" ("DSCS_GRP_ID") ENABLE, 
	 CONSTRAINT "FK_SBJCT_TO_DSCS" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_DSCS" ON "DEV_LMS"."TB_LMS_DSCS" ("DSCS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_DSCS IS '토론';
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_ID IS '토론아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.LCTR_WKNO_SCHDL_ID IS '강의주차일정아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_GRP_ID IS '토론그룹아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_TYCD IS '토론유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_GBNCD IS '토론구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_UNIT_TYCD IS '토론단위유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EVL_SCR_TYCD IS '평가점수유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_TTL IS '토론제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_CTS IS '토론내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_SDTTM IS '토론시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DSCS_EDTTM IS '토론종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EVL_SDTTM IS '평가시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EVL_EDTTM IS '평가종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EXTD_SDTTM IS '연장시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EXTD_EDTTM IS '연장종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EXTD_EVL_SDTTM IS '연장평가시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EXTD_EVL_EDTTM IS '연장평가종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DVCLS_NO IS '분반번호'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.LRN_GRP_ID IS '학습그룹아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.OATCL_INQYN IS '타게시글조회여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.OKNOKRT_OYN IS '찬성반대비율공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.OKNOK_MODYN IS '찬성반대수정여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MLT_OPNN_REGYN IS '다중의견등록여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.EXTD_USEYN IS '연장사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.CMNT_RSPNS_REQYN IS '댓글답변요청여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MRK_RFLTYN IS '성적반영여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MRK_OYN IS '성적공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MRK_OPEN_SDTTM IS '성적공개시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MRK_OPEN_EDTTM IS '성적공개종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.OKNOK_RGTR_OYN IS '찬성반대등록자공개여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.OKNOK_STNGYN IS '찬성반대설정여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.MRK_RFLTRT IS '성적반영비율'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.BYTEAM_DSCS_USEYN IS '팀별토론사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.TEAM_ID IS '팀아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.UP_DSCS_ID IS '상위토론아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS.TEAM_DSCS_OYN IS '팀토론공개여부'