CREATE TABLE "DEV_LMS"."TB_LMS_TKEXAM" 
   (	"TKEXAM_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_DTL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"TKEXAM_CNT" NUMBER(3,0) NOT NULL ENABLE, 
	"TKEXAM_MNTS" NUMBER(5,0) NOT NULL ENABLE, 
	"TKEXAM_CMPTNYN" CHAR(1) NOT NULL ENABLE, 
	"TKEXAM_SDTTM" VARCHAR2(14), 
	"TKEXAM_EDTTM" VARCHAR2(14), 
	"RETKEXAM_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_TKEXAM" PRIMARY KEY ("TKEXAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_USER_TO_TKEXAM" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_EXAM_DTL_TO_TKEXAM" FOREIGN KEY ("EXAM_DTL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_DTL" ("EXAM_DTL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_TKEXAM" ON "DEV_LMS"."TB_LMS_TKEXAM" ("TKEXAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_TKEXAM IS '시험응시';
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.TKEXAM_ID IS '시험응시아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.EXAM_DTL_ID IS '시험상세아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.TKEXAM_CNT IS '시험응시수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.TKEXAM_MNTS IS '시험응시시간'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.TKEXAM_CMPTNYN IS '시험응시완료여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.TKEXAM_SDTTM IS '시험응시시작일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.TKEXAM_EDTTM IS '시험응시종료일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.RETKEXAM_YN IS '재응시여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_TKEXAM.MOD_DTTM IS '수정일시'