CREATE TABLE "DEV_LMS"."TB_LMS_EXAM_ABSNCE" 
   (	"EXAM_ABSNCE_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"EXAM_BSC_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ABSNCE_TTL" VARCHAR2(200), 
	"ABSNCE_CTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"APLY_STSCD" VARCHAR2(10), 
	"AUTZR_ID" VARCHAR2(30), 
	"APRVDTTM" VARCHAR2(14), 
	"APRV_CTS" VARCHAR2(4000), 
	"MNGR_OPNN" VARCHAR2(4000), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_EXAM_ABSNCE" PRIMARY KEY ("EXAM_ABSNCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_EB_TO_EA" FOREIGN KEY ("EXAM_BSC_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_EXAM_BSC" ("EXAM_BSC_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_EXAM_ABSNCE" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_EXAM_ABSNCE" ON "DEV_LMS"."TB_LMS_EXAM_ABSNCE" ("EXAM_ABSNCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_EXAM_ABSNCE IS '시험결시';
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.EXAM_ABSNCE_ID IS '시험결시아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.EXAM_BSC_ID IS '시험기본아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.ABSNCE_TTL IS '결시제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.ABSNCE_CTS IS '결시내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.APLY_STSCD IS '신청상태코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.AUTZR_ID IS '승인자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.APRVDTTM IS '승인일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.APRV_CTS IS '승인내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.MNGR_OPNN IS '매니져의견'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_EXAM_ABSNCE.MOD_DTTM IS '수정일시'