CREATE TABLE "DEV_LMS"."TB_LMS_AUTHRT_MENU" 
   (	"AUTHRT_MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHRT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHRT_MENU_GBNCD" VARCHAR2(10) NOT NULL ENABLE, 
	"CRUD_CD" VARCHAR2(4) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_AUTHRT_MENU" PRIMARY KEY ("AUTHRT_MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_AUTHRT_TO_AUTHRT_MENU" FOREIGN KEY ("AUTHRT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_AUTHRT" ("AUTHRT_ID") ENABLE, 
	 CONSTRAINT "FK_MENU_TO_AUTHRT_MENU" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_MENU" ("MENU_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_AUTHRT_MENU" ON "DEV_LMS"."TB_LMS_AUTHRT_MENU" ("AUTHRT_MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_AUTHRT_MENU IS '권한메뉴';
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.AUTHRT_MENU_ID IS '권한메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.AUTHRT_ID IS '권한아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.AUTHRT_MENU_GBNCD IS '권한메뉴구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.CRUD_CD IS '크루드코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_AUTHRT_MENU.MOD_DTTM IS '수정일시'