CREATE TABLE "DEV_LMS"."TB_LMS_DSCS_CMNT" 
   (	"DSCS_CMNT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"DSCS_ATCL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"UP_CMNT_ID" VARCHAR2(30), 
	"CMNT_CTS" CLOB NOT NULL ENABLE, 
	"CMNT_CTS_LEN" NUMBER(20,0) NOT NULL ENABLE, 
	"RSPNS_REQYN" CHAR(1) DEFAULT 'Y', 
	"EMT_TYCD" VARCHAR2(10), 
	"DELYN" CHAR(1) DEFAULT 'N', 
	"RGTR_ID" VARCHAR2(30), 
	"REG_DTTM" VARCHAR2(14), 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_DSCS_CMNT" PRIMARY KEY ("DSCS_CMNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_DA_TO_DC" FOREIGN KEY ("DSCS_ATCL_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_DSCS_ATCL" ("DSCS_ATCL_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_DSCS_CMNT" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CMNT_CTS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "DEV_LMS"."SYS_IL0000036810C00005$$" ON "DEV_LMS"."TB_LMS_DSCS_CMNT" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_DSCS_CMNT" ON "DEV_LMS"."TB_LMS_DSCS_CMNT" ("DSCS_CMNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_DSCS_CMNT IS '토론댓글';
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.DSCS_CMNT_ID IS '토론댓글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.DSCS_ATCL_ID IS '토론게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.UP_CMNT_ID IS '상위댓글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.CMNT_CTS IS '댓글내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.CMNT_CTS_LEN IS '댓글내용길이'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.RSPNS_REQYN IS '답변요청여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.EMT_TYCD IS '이모티콘유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_CMNT.MOD_DTTM IS '수정일시'