CREATE TABLE "DEV_LMS"."TB_LMS_DSCS_ATCL" 
   (	"DSCS_ATCL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"DSCS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"UP_DSCS_ATCL_ID" VARCHAR2(30), 
	"ATCL_LV" NUMBER(7,0), 
	"ATCL_SEQNO" NUMBER(7,0), 
	"DSCS_ATCL_TYCD" VARCHAR2(10), 
	"OKNOK_GBNCD" VARCHAR2(10), 
	"ATCL_TTL" VARCHAR2(4000), 
	"ATCL_CTS" VARCHAR2(4000), 
	"ATCL_CTS_LEN" NUMBER(20,0), 
	"INQ_CNT" NUMBER(7,0), 
	"EDTR_USEYN" CHAR(1) NOT NULL ENABLE, 
	"DELYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_DSCS_ATCL" PRIMARY KEY ("DSCS_ATCL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_DSCS_TO_DSCS_ATCL" FOREIGN KEY ("DSCS_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_DSCS" ("DSCS_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_DSCS_ATCL" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_DSCS_ATCL" ON "DEV_LMS"."TB_LMS_DSCS_ATCL" ("DSCS_ATCL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_DSCS_ATCL IS '토론게시글';
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.DSCS_ATCL_ID IS '토론게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.DSCS_ID IS '토론아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.UP_DSCS_ATCL_ID IS '상위토론게시글아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.ATCL_LV IS '게시글레벨'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.ATCL_SEQNO IS '게시글순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.DSCS_ATCL_TYCD IS '토론게시글유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.OKNOK_GBNCD IS '찬성반대구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.ATCL_TTL IS '게시글제목'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.ATCL_CTS IS '게시글내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.ATCL_CTS_LEN IS '게시글내용길이'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.INQ_CNT IS '조회수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.EDTR_USEYN IS '에디터사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_ATCL.MOD_DTTM IS '수정일시'