CREATE TABLE "DEV_LMS"."TB_LMS_QSTN_VWITM" 
   (	"QSTN_VWITM_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"QSTN_ID" VARCHAR2(30), 
	"QSTN_VWITM_GBNCD" VARCHAR2(10), 
	"QSTN_VWITM_CTS" VARCHAR2(4000), 
	"CRANS_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"EDTR_USEYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"QSTN_VWITM_SEQNO" NUMBER(3,0), 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_QSTN_VWITM" PRIMARY KEY ("QSTN_VWITM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_QSTN_TO_QSTN_VWITM" FOREIGN KEY ("QSTN_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_QSTN" ("QSTN_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_QSTN_VWITM" ON "DEV_LMS"."TB_LMS_QSTN_VWITM" ("QSTN_VWITM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_QSTN_VWITM IS '문항보기항목';
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.QSTN_VWITM_ID IS '문항보기항목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.QSTN_ID IS '문항아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.QSTN_VWITM_GBNCD IS '문항보기항목구분코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.QSTN_VWITM_CTS IS '문항보기항목내용'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.CRANS_YN IS '정답여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.EDTR_USEYN IS '편집기사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.QSTN_VWITM_SEQNO IS '문항보기항목순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_QSTN_VWITM.MOD_DTTM IS '수정일시'