CREATE TABLE "DEV_LMS"."TB_LMS_DSCS_PTCP" 
   (	"DSCS_PTCP_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"DSCS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TEAM_ID" VARCHAR2(30), 
	"SCR" NUMBER(7,0), 
	"EVLYN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"PROF_MEMO" VARCHAR2(4000), 
	"DELYN" CHAR(1) DEFAULT 'N', 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_DSCS_PTCP" PRIMARY KEY ("DSCS_PTCP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_D_TO_DP" FOREIGN KEY ("DSCS_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_DSCS" ("DSCS_ID") ENABLE, 
	 CONSTRAINT "FK_USER_TO_DSCS_PTCP" FOREIGN KEY ("USER_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_DSCS_PTCP" ON "DEV_LMS"."TB_LMS_DSCS_PTCP" ("DSCS_PTCP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_DSCS_PTCP IS '토론참여';
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.DSCS_PTCP_ID IS '토론참여아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.USER_ID IS '사용자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.DSCS_ID IS '토론아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.TEAM_ID IS '팀아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.SCR IS '점수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.EVLYN IS '평가여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.PROF_MEMO IS '교수메모'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_DSCS_PTCP.MOD_DTTM IS '수정일시'