CREATE TABLE "DEV_LMS"."TB_LMS_ATFL" 
   (	"ATFL_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REF_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ATFL_REPO_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ATFL_SEQNO" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"FILENM" VARCHAR2(200) NOT NULL ENABLE, 
	"FILE_EXT" VARCHAR2(10) NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(1000) NOT NULL ENABLE, 
	"FILE_SAVNM" VARCHAR2(200) NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER(22,0) NOT NULL ENABLE, 
	"FILE_TYCD" VARCHAR2(30) NOT NULL ENABLE, 
	"CNVSN_FILE" VARCHAR2(1000), 
	"ETC_INFO1" VARCHAR2(1000), 
	"ETC_INFO2" VARCHAR2(1000), 
	"ETC_INFO3" VARCHAR2(1000), 
	"MIME_TYCD" VARCHAR2(1000), 
	"THMB_FILE_PATH" VARCHAR2(1000), 
	"THMB_FILENM" VARCHAR2(200), 
	"DWLD_CNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"DELYN" CHAR(1) DEFAULT 'N', 
	"SRC_ATFL_ID" VARCHAR2(30), 
	 CONSTRAINT "PK_TB_LMS_ATFL01" PRIMARY KEY ("ATFL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ATFL_REPO_TO_ATFL" FOREIGN KEY ("ATFL_REPO_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ATFL_REPO" ("ATFL_REPO_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "DEV_LMS"."IDX_TB_LMS_ATFL_01" ON "DEV_LMS"."TB_LMS_ATFL" ("ATFL_ID", "REF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ATFL01" ON "DEV_LMS"."TB_LMS_ATFL" ("ATFL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "DEV_LMS"."IDX_TB_LMS_ATFL_02" ON "DEV_LMS"."TB_LMS_ATFL" ("SRC_ATFL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ATFL IS '첨부파일';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.ATFL_ID IS '첨부파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.REF_ID IS '참조아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.ATFL_REPO_ID IS '첨부파일저장소아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.ATFL_SEQNO IS '파일순번'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.FILENM IS '파일명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.FILE_EXT IS '파일확장자'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.FILE_PATH IS '파일경로'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.FILE_SAVNM IS '파일저장명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.FILE_SIZE IS '파일크기'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.FILE_TYCD IS '파일유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.CNVSN_FILE IS '변환파일'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.ETC_INFO1 IS '기타정보1'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.ETC_INFO2 IS '기타정보2'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.ETC_INFO3 IS '기타정보3'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.MIME_TYCD IS '마임유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.THMB_FILE_PATH IS '썸네일파일경로'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.THMB_FILENM IS '썸네일파일명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.DWLD_CNT IS '다운로드수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ATFL.SRC_ATFL_ID IS '원본첨부파일아이디'