CREATE TABLE "DEV_LMS"."TB_LMS_ORG_STNG" 
   (	"ORG_STNG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"STNG_CTGRCD" VARCHAR2(30) NOT NULL ENABLE, 
	"STNG_CD" VARCHAR2(30) NOT NULL ENABLE, 
	"STNGNM" VARCHAR2(200) NOT NULL ENABLE, 
	"STNG_VL" VARCHAR2(100) NOT NULL ENABLE, 
	"STNG_EXPLN" VARCHAR2(200) NOT NULL ENABLE, 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	 CONSTRAINT "PK_TB_LMS_ORG_STNG" PRIMARY KEY ("ORG_STNG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ORG_TO_ORG_STNG" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_ORG_STNG" ON "DEV_LMS"."TB_LMS_ORG_STNG" ("ORG_STNG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_ORG_STNG IS '기관설정';
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.ORG_STNG_ID IS '기관설정아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.STNG_CTGRCD IS '설정분류코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.STNG_CD IS '설정코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.STNGNM IS '설정명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.STNG_VL IS '설정값'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.STNG_EXPLN IS '설정설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.USEYN IS '사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_ORG_STNG.MOD_DTTM IS '수정일시'