CREATE TABLE "DEV_LMS"."TB_LMS_BBS" 
   (	"BBS_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SBJCT_ID" VARCHAR2(30), 
	"BBS_REF_TYPE_ID" VARCHAR2(30), 
	"BBS_REF_TYCD" VARCHAR2(10), 
	"BBSNM" VARCHAR2(200) NOT NULL ENABLE, 
	"BBS_ENNM" VARCHAR2(200), 
	"BBS_EXPLN" VARCHAR2(4000), 
	"BBS_TYCD" VARCHAR2(10) NOT NULL ENABLE, 
	"BBS_LANG_CD" VARCHAR2(10) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(30), 
	"MN_IMG_FILE_ID" VARCHAR2(30), 
	"LIST_CNT" NUMBER(5,0) NOT NULL ENABLE, 
	"ATFL_MAX_CNT" NUMBER(3,0) NOT NULL ENABLE, 
	"ATFL_MAXSZ" NUMBER(22,0) NOT NULL ENABLE, 
	"ATFL_USEYN" CHAR(1) NOT NULL ENABLE, 
	"DELYN" CHAR(1) NOT NULL ENABLE, 
	"RGTR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"REG_DTTM" VARCHAR2(14) NOT NULL ENABLE, 
	"MDFR_ID" VARCHAR2(30), 
	"MOD_DTTM" VARCHAR2(14), 
	"USEYN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_LMS_BBS" PRIMARY KEY ("BBS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_TB_LMS_ORG_TO_TB_LMS_BBS" FOREIGN KEY ("ORG_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_ORG" ("ORG_ID") ENABLE, 
	 CONSTRAINT "FK_SBJCT_TO_BBS" FOREIGN KEY ("SBJCT_ID")
	  REFERENCES "DEV_LMS"."TB_LMS_SBJCT" ("SBJCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE INDEX "DEV_LMS"."IDX_BBS_01" ON "DEV_LMS"."TB_LMS_BBS" ("SBJCT_ID", "BBS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "DEV_LMS"."IDX_BBS_02" ON "DEV_LMS"."TB_LMS_BBS" ("BBS_ID", "DELYN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE INDEX "DEV_LMS"."IDX_BBS_QNA_09" ON "DEV_LMS"."TB_LMS_BBS" ("BBS_TYCD", "SBJCT_ID", "DELYN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "DEV_LMS"."PK_TB_LMS_BBS" ON "DEV_LMS"."TB_LMS_BBS" ("BBS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE DEV_LMS.TB_LMS_BBS IS '게시판';
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_ID IS '게시판아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.ORG_ID IS '기관아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.SBJCT_ID IS '과목아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_REF_TYPE_ID IS '게시판참조유형아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_REF_TYCD IS '게시판참조유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBSNM IS '게시판명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_ENNM IS '게시판영문명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_EXPLN IS '게시판설명'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_TYCD IS '게시판유형코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.BBS_LANG_CD IS '게시판언어코드'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.MENU_ID IS '메뉴아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.MN_IMG_FILE_ID IS '메인이미지파일아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.LIST_CNT IS '목록수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.ATFL_MAX_CNT IS '첨부파일최대수'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.ATFL_MAXSZ IS '첨부파일최대크기'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.ATFL_USEYN IS '첨부파일사용여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.DELYN IS '삭제여부'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.RGTR_ID IS '등록자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.REG_DTTM IS '등록일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.MDFR_ID IS '수정자아이디'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.MOD_DTTM IS '수정일시'
COMMENT ON COLUMN DEV_LMS.TB_LMS_BBS.USEYN IS '사용여부'