############################################
# LMS DATABASE_INFO
############################################

# LMS Local
#lms.database.url=ENC(jj/O8Acw9K5Y/ZQgsxUWygFlexfTu3qB8qVeIx7bemfxOXLbuwby3BlsniTfXBPY9a+Xv0GjQ5vHLnZ2vXogX3pqtnXg52ke+3OwTLMK2bhUmlPx3qZ/vzDBm/FDnmCaK/dAzs4moOFjvBQiu+pdhLFwGlReoRkuDdZ+EK8Ll31ElPoUesp6gP7ct3zIHI+B)
#lms.database.username=ENC(mDfDQ5PYmZxJzKCur2T5x5Gdq7e3AMqL)
#lms.database.password=ENC(9WUhvWt7VsJXLPmRy+97OPmqGnxtJne8)
#lms.database.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#lms.database.url=jdbc:log4jdbc:mysql://182.252.182.15:3307/lmsdev1?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
#lms.database.username=lmsuser1
#lms.database.password=lmspass
#lms.database.validationQuery=select 1
#lms.database.testWhileIdle=true
#lms.database.testOnBorrow=false
#lms.database.timeBetweenEvictionRunsMillis=7200000

#lms.database.vendor=oracle.jdbc.driver.OracleDriver
#lms.database.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
#lms.database.serverAddress=127.0.0.1
#lms.database.portNo=1521
#lms.database.sid=xe
#lms.database.user=lmsuser1
#lms.database.password=lmspass
#lms.database.maxconns=20
#lms.database.initconns=5
#lms.database.timeout=5
#lms.database.doConnectionCheck=true
#lms.database.testQueryString=select 1 from dual

# LMS Dev
lms.database.vendor=oracle.jdbc.driver.OracleDriver
lms.database.url=jdbc:oracle:thin:@61.43.90.131:1521:xe
lms.database.serverAddress=61.43.90.131
lms.database.portNo=1521
lms.database.sid=xe
lms.database.user=DEV_LMS
lms.database.password=DEV_LMS_KNOU
lms.database.maxconns=20
lms.database.initconns=5
lms.database.timeout=5
lms.database.doConnectionCheck=true
lms.database.testQueryString=select 1 from dual

# LMS Dev
#lms.database.driver=com.mysql.cj.jdbc.Driver
#lms.database.url=ENC((3rb7Pr+dxf7DvY4jVtwjSawMhkjwiEXbCZCW9rSzVScHEF5IBwq0ahELQLTE0xxv8ThRIXrNMeYAAXHCGBOLCFTSn0exBovGcSJsKk0oio18FR7V9p2/mBdhmwuy+p/rp6Ts1YYpi3uBUK1Y/2VQkNYwsL4l426qcUAL5iP/L1VthMgI+edviA==)
#lms.database.username=ENC(mDfDQ5PYmZxJzKCur2T5x5Gdq7e3AMqL)
#lms.database.password=ENC(9WUhvWt7VsJXLPmRy+97OPmqGnxtJne8)
#lms.database.validationQuery=select 1
#lms.database.testWhileIdle=true
#lms.database.testOnBorrow=false
#lms.database.timeBetweenEvictionRunsMillis=150000
#lms.database.minEvictableIdleTimeMillis=-1
#lms.database.numTestsPerEvictionRun=4
#lms.database.initialSize=10
#lms.database.maxTotal=20
#lms.database.minIdle=10
#lms.database.maxIdle=20
#lms.database.maxWaitMillis=30000


# LMS Pro
#lms.database.driver=com.mysql.cj.jdbc.Driver
#lms.database.url=ENC(JlgJZ4tLZqtVyLJXFvxao9JGXlz/Mo4WPsLSyEDTmi1+4dp5EJVjI1+qn5yJz5ZSRANLyAfwym5MNO+hsaRtxQGhZYBHkSLla8+p7eWU3tcagcJecgFFk6IrDCcDf5wt1juIomG6p7zpQeJZwXcykfXwuBmwW75XC/3n/OmeHaADJ6Ym1ij+Pw==)
#lms.database.username=ENC(mDfDQ5PYmZxJzKCur2T5x5Gdq7e3AMqL)
#lms.database.password=ENC(AtcMn0LSlSx913rq1hTtxBgCBPp1epdEo+8k0TCngCU=)
#lms.database.validationQuery=select 1
#lms.database.testWhileIdle=true
#lms.database.testOnBorrow=false
#lms.database.timeBetweenEvictionRunsMillis=150000
#lms.database.minEvictableIdleTimeMillis=-1
#lms.database.numTestsPerEvictionRun=4
#lms.database.initialSize=20
#lms.database.maxTotal=100
#lms.database.minIdle=20
#lms.database.maxIdle=100
#lms.database.maxWaitMillis=30000


############################################
# ERP DATABASE_INFO
############################################

# ERP Local
erp.database.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
erp.database.url=ENC(DFgicEf3yWDTBqXvZ0741Unw0aA2RhQecQJBIfkAP90n4ByBcjHO4dGXWj+2j6eRB9yHqMmQU/1LwhWCRUjxkQ==)
erp.database.username=ENC(kygahTFXXh39HdJ8q5b7UA==)
erp.database.password=ENC(70YsW7wLe+f+KWFZ3wIUUGwSuRdFufZC)
erp.database.validationQuery=select 1 from dual
erp.database.testWhileIdle=true
erp.database.testOnBorrow=false
erp.database.timeBetweenEvictionRunsMillis=7200000

# ERP Dev
#erp.database.driver=oracle.jdbc.driver.OracleDriver
#erp.database.url=ENC(06Hu7yD2rCAOolGhO+yrJdrVmF9KDF1nmXzmFc9xjhNVQMZyFPv8KwdG5GyLMeTif25Kj/gLNyg=)
#erp.database.username=ENC(kygahTFXXh39HdJ8q5b7UA==)
#erp.database.password=ENC(70YsW7wLe+f+KWFZ3wIUUGwSuRdFufZC)
#erp.database.validationQuery=select 1 from dual
#erp.database.testWhileIdle=true
#erp.database.testOnBorrow=false
#erp.database.timeBetweenEvictionRunsMillis=150000
#erp.database.minEvictableIdleTimeMillis=-1
#erp.database.numTestsPerEvictionRun=4
#erp.database.initialSize=10
#erp.database.maxTotal=20
#erp.database.minIdle=10
#erp.database.maxIdle=20
#erp.database.maxWaitMillis=30000

# ERP Pro
#erp.database.driver=oracle.jdbc.driver.OracleDriver
#erp.database.url=ENC(HjvqIhEgOGW4DauPpua2n+ewclBzUBm1EtKGiLNJ0FKuYC+KLXac5bODknH7mxAvqqKY66qUw03rR0Y4x36d7zMDSRnCP6XXcOhhmKf/G3wepSwJBtbStuqrwOyetBgdB3k76z1uEPlZlnoCKCqw3+2OhSoNJjq3PsJTA8k57muVv6x9eeJlctqT72/37nKrxF1xMxtLWSgjuMTBJGDErH6byEqceJTzQHMcXzHhQQgRgdHG9yFKUFhXhg03jo2HGNPAmnP6GQpz/D96V2fp9rB4sYz6Snlmi9f4f7nrK6VeWxFTxKK16tixzOqdCkl+MhU0loIln5h7c0nv1cX3XA==)
#erp.database.username=ENC(kygahTFXXh39HdJ8q5b7UA==)
#erp.database.password=ENC(xuRjvu/Pu+Jlhy95GOx1Vz5XKnC33Bmin1VkEM/deek=)
#erp.database.validationQuery=select 1 from dual
#erp.database.testWhileIdle=true
#erp.database.testOnBorrow=false
#erp.database.timeBetweenEvictionRunsMillis=150000
#erp.database.minEvictableIdleTimeMillis=-1
#erp.database.numTestsPerEvictionRun=4
#erp.database.initialSize=20
#erp.database.maxTotal=100
#erp.database.minIdle=20
#erp.database.maxIdle=100
#erp.database.maxWaitMillis=30000