/*
 * TB_LMS_SRVC_ACTN 샘플 데이터
 * - SRVC_ACTN_GBNCD는 공통코드 SRVC_ACTN_GBNCD의 실제 코드값으로 조정해서 사용한다.
 * - USER_REQ_URL, REQ_TYCD는 TB_LMS_LOG_USER_ACTV.USER_REQ_URL, REQ_TYCD와 동일한 값으로 관리한다.
 */

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160001', 'DASH', '/dashboard/stuWidgetQna.do', 'GET', '학습자 대시보드 질문답변 위젯 조회', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160002', 'DASH', '/dashboard/stuWidgetPds.do', 'GET', '학습자 대시보드 자료실 위젯 조회', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160003', 'SBJCT', '/subject/subject.do', 'GET', '강의실 과목 진입', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160004', 'SMNR', '/smnr/pltfrm/mngrZoomAuthrtUserMngView.do', 'GET', 'Zoom 권한 사용자 관리 화면 조회', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160005', 'DASH', '/dashboard/profDashboard.do', 'GET', '교수 대시보드 조회', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160006', 'MRK', '/mrk/stdMrkObjctAplyRegistViewPop.do', 'GET', '성적 이의신청 등록 팝업 조회', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160007', 'MRK', '/mrk/stdMrkObjctAplyRegist.do', 'POST', '성적 이의신청 등록', 'C', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

INSERT INTO FURLMS.TB_LMS_SRVC_ACTN
(SRVC_ACTN_ID, SRVC_ACTN_GBNCD, USER_REQ_URL, REQ_TYCD, SRVC_ACTN_EXPLN, SRVC_ACTN_TYCD, RGTR_ID, REG_DTTM)
VALUES
('SRVACT202604160008', 'ALIM', '/alimUnrdCntSelectAjax.do', 'POST', '미확인 알림 건수 조회', 'R', 'SYSTEM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

COMMIT;
