INSERT INTO DEV_LMS.TB_LMS_ATFL_REPO
(ATFL_REPO_ID, ATFL_REPO_PATH, UP_CLMNNM, UP_TBLNM,
 RGTR_ID, REG_DTTM)
VALUES
('REPO_001', '/lms/upload/lecture', 'SBJCT_ID', 'TB_LMS_SBJCT',
 'admin', '20260202121110');