CREATE OR REPLACE FUNCTION LMSUSER.FN_DTTM_ADD_SEC (sec IN INT)
    RETURN VARCHAR2
IS
BEGIN
    /**
     * 현재일시에 초를 더하여 문자열 가져오기 
     */
    RETURN TO_CHAR(SYSTIMESTAMP + NUMTODSINTERVAL(sec, 'SECOND'), 'YYYYMMDDHH24MISS');
END;
