CREATE OR REPLACE FUNCTION DEV_LMS.FN_REF_FILE_CNT(
	refId      VARCHAR2
)
RETURN NUMBER
IS
	attachFileCnt NUMBER;
BEGIN
	SELECT COUNT(1) INTO attachFileCnt
	FROM TB_LMS_ATFL
	WHERE REF_ID = refId;

	RETURN attachFileCnt;
END;
