############################################
# LMS DATABASE_INFO
############################################
lms.database.driver=oracle.jdbc.OracleDriver
#lms.database.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
lms.database.url=ENC(JASYPT_ENCRYPTED_URL)
lms.database.username=ENC(JASYPT_ENCRYPTED_USERNAME)
lms.database.password=ENC(JASYPT_ENCRYPTED_PASSWORD)
lms.database.validationQuery=select 1 from dual
lms.database.testWhileIdle=true
lms.database.testOnBorrow=false
lms.database.timeBetweenEvictionRunsMillis=150000
lms.database.minEvictableIdleTimeMillis=-1
lms.database.numTestsPerEvictionRun=4
lms.database.initialSize=10
lms.database.maxTotal=20
lms.database.minIdle=10
lms.database.maxIdle=20
lms.database.maxWaitMillis=30000




############################################
# ERP(HAKSA) DATABASE_INFO
############################################
erp.database.driver=oracle.jdbc.OracleDriver
#erp.database.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
erp.database.url=ENC(JASYPT_ENCRYPTED_URL)
erp.database.username=ENC(JASYPT_ENCRYPTED_USERNAME)
erp.database.password=ENC(JASYPT_ENCRYPTED_PASSWORD)
erp.database.validationQuery=select 1 from dual
erp.database.testWhileIdle=true
erp.database.testOnBorrow=false
erp.database.timeBetweenEvictionRunsMillis=150000
erp.database.minEvictableIdleTimeMillis=-1
erp.database.numTestsPerEvictionRun=4
erp.database.initialSize=10
erp.database.maxTotal=20
erp.database.minIdle=10
erp.database.maxIdle=20
erp.database.maxWaitMillis=30000